/**
 * Style Cards action types
 */
export const RECEIVE_STYLE_CARDS = 'RECEIVE_STYLE_CARDS';
export const SAVE_STYLE_CARDS = 'SAVE_STYLE_CARDS';
export const SET_ACTIVE_STYLE_CARD = 'SET_ACTIVE_STYLE_CARD';
export const SET_SELECTED_STYLE_CARD = 'SET_SELECTED_STYLE_CARD';
export const REMOVE_STYLE_CARD = 'REMOVE_STYLE_CARD';
export const UPDATE_STYLE_CARD = 'UPDATE_STYLE_CARD';
export const RESET_STYLE_CARDS = 'RESET_STYLE_CARDS';
export const SAVE_CUSTOM_COLORS = 'SAVE_CUSTOM_COLORS';

// Additional action types used by const definitions
export const UPDATE_BLOCK_STYLE_CARDS = 'UPDATE_BLOCK_STYLE_CARDS';
export const GET_ACTIVE_STYLE_CARD = 'GET_ACTIVE_STYLE_CARD';
export const SET_INIT_SC = 'SET_INIT_SC';
export const SAVE_MAXI_SELECTED_STYLE_CARD = 'SAVE_MAXI_SELECTED_STYLE_CARD';
export const SAVE_MAXI_STYLE_CARDS = 'SAVE_MAXI_STYLE_CARDS';
export const UPDATE_SC_ON_EDITOR = 'UPDATE_SC_ON_EDITOR';
export const REMOVE_MAXI_STYLE_CARDS = 'REMOVE_MAXI_STYLE_CARDS';
