export const shortcut1 = {
	'motion-delay-rotate-general': 0,
	'motion-easing-rotate-general': 'ease',
	'motion-rotate-end-rotate-general': 360,
	'motion-rotate-mid-rotate-general': 180,
	'motion-rotate-start-rotate-general': 0,
	'motion-speed-rotate-general': 500,
	'motion-status-reverse-rotate-general': true,
	'motion-status-rotate-general': true,
	'motion-viewport-bottom-rotate-general': 'bottom',
	'motion-viewport-middle-rotate-general': 'mid',
	'motion-viewport-top-rotate-general': 'top',
	'motion-active-general': 'fade',
	'motion-delay-fade-general': 100,
	'motion-easing-fade-general': 'ease',
	'motion-opacity-end-fade-general': 0,
	'motion-opacity-mid-fade-general': 50,
	'motion-opacity-start-fade-general': 100,
	'motion-speed-fade-general': 650,
	'motion-status-fade-general': true,
	'motion-status-reverse-fade-general': true,
	'motion-viewport-bottom-fade-general': 'bottom',
	'motion-viewport-middle-fade-general': 'mid',
	'motion-viewport-start-fade-general': 'mid',
	'motion-viewport-top-fade-general': 'top',
	'motion-status-vertical-general': false,
	'motion-status-horizontal-general': false,
	'motion-status-scale-general': false,
	'motion-status-blur-general': false,
};
export const shortcut2 = {};
export const shortcut3 = {};

export const rotate = {
	shortcut1: {
		'motion-delay-rotate-general': 0,
		'motion-easing-rotate-general': 'ease',
		'motion-rotate-end-rotate-general': 360,
		'motion-rotate-mid-rotate-general': 180,
		'motion-rotate-start-rotate-general': 0,
		'motion-speed-rotate-general': 500,
		'motion-status-reverse-rotate-general': true,
		'motion-status-rotate-general': true,
		'motion-viewport-bottom-rotate-general': 'bottom',
		'motion-viewport-middle-rotate-general': 'mid',
		'motion-viewport-top-rotate-general': 'top',
	},
};
