import getContainerStyles from '../getContainerStyles';
import '@wordpress/block-editor';

describe('getContainerStyles', () => {
	it('Get a correct Container Styles', () => {
		const object = {
			'container-min-width-unit-general': 'px',
			'container-min-width-general': 1000,
			'container-max-height-unit-general': 'px',
			'container-max-height-general': 400,
			'container-height-unit-general': 'px',
			'container-height-general': 390,
			'container-min-height-unit-general': 'px',
			'container-min-height-general': 100,
			///
			'container-min-width-unit-xxl': 'px',
			'container-min-width-xxl': 1,
			'container-max-height-unit-xxl': 'px',
			'container-max-height-xxl': 2,
			'container-height-unit-xxl': 'px',
			'container-height-xxl': 3,
			'container-min-height-unit-xxl': 'px',
			'container-min-height-xxl': 4,
			//
			'container-min-width-unit-xl': 'px',
			'container-min-width-xl': 1,
			'container-max-height-unit-xl': 'px',
			'container-max-height-xl': 2,
			'container-height-unit-xl': 'px',
			'container-height-xl': 3,
			'container-min-height-unit-xl': 'px',
			'container-min-height-xl': 4,
			//
			'container-min-width-unit-l': 'px',
			'container-min-width-l': 1,
			'container-max-height-unit-l': 'px',
			'container-max-height-l': 2,
			'container-height-unit-l': 'px',
			'container-height-l': 3,
			'container-min-height-unit-l': 'px',
			'container-min-height-l': 4,
			//
			'container-min-width-unit-m': 'px',
			'container-min-width-m': 1,
			'container-max-height-unit-m': 'px',
			'container-max-height-m': 2,
			'container-height-unit-m': 'px',
			'container-height-m': 3,
			'container-min-height-unit-m': 'px',
			'container-min-height-m': 4,
			//
			'container-min-width-unit-s': 'px',
			'container-min-width-s': 1,
			'container-max-height-unit-s': 'px',
			'container-max-height-s': 2,
			'container-height-unit-s': 'px',
			'container-height-s': 3,
			'container-min-height-unit-s': 'px',
			'container-min-height-s': 4,
			//
			'container-min-width-unit-xs': 'px',
			'container-min-width-xs': 1,
			'container-max-height-unit-xs': 'px',
			'container-max-height-xs': 2,
			'container-height-unit-xs': 'px',
			'container-height-xs': 3,
			'container-min-height-unit-xs': 'px',
			'container-min-height-xs': 4,
			'container-size-advanced-options': 'false',
			'container-max-width-general': 1170,
			'container-max-width-xl': 1170,
			'container-max-width-l': 90,
			'container-max-width-m': 90,
			'container-max-width-s': 90,
			'container-max-width-xs': 90,
			'container-max-width-unit-general': 'px',
			'container-max-width-unit-xxl': 'px',
			'container-max-width-unit-xl': 'px',
			'container-max-width-unit-l': '%',
			'container-max-width-unit-m': '%',
			'container-max-width-unit-s': '%',
			'container-max-width-unit-xs': '%',
			'container-width-l': 1170,
			'container-width-unit-l': 'px',
			'container-width-m': 1000,
			'container-width-unit-m': 'px',
			'container-width-s': 700,
			'container-width-unit-s': 'px',
			'container-width-xs': 460,
			'container-width-unit-xs': 'px',
			'container-max-width-xxl': 1790,
		};

		const result = getContainerStyles(object);
		expect(result).toMatchSnapshot();
	});
});
