import getCustomFormatsStyles from '../getCustomFormatsStyles';

describe('getCustomFormatsStyles', () => {
	it('Get a correct custom formats styles', () => {
		const object = {
			'maxi-text-block__custom-format--0': {
				'_cc-g': 'rgba(57,28,202,1)',
				'_fst-g': 'italic',
				'_fwe-g': 800,
			},
			'maxi-text-block__custom-format--1': {
				'_td-g': 'underline',
			},
		};
		const objectTypography = {
			'_ff-g': 'roboto',
			'_cc-g': 'rgb(255, 99, 71)',
			'_fs.u-g': 'px',
			'_fs-g': 1,
			'_lhe.u-g': 'px',
			'_lhe-g': 1,
			'_ls.u-g': 'px',
			'_ls-g': 2,
			'_fwe-g': 3,
			'_ttr-g': 'none',
			'_fst-g': 'bold',
			'_td-g': 'underline',
			'_tsh-g': 'none',
			'_va-g': 'none',
			'_ff-xxl': 'roboto',
			'_cc-xxl': 'red',
			'_fs.u-xxl': 'px',
			'_fs-xxl': 1,
			'_lhe.u-xxl': 'px',
			'_lhe-xxl': 2,
			'_ls.u-xxl': 'px',
			'_ls-xxl': 3,
			'_fwe-xxl': '4',
			'_ttr-xxl': 'none',
			'_fst-xxl': 'bold',
			'_td-xxl': 'underline',
			'_tsh-xxl': 'none',
			'_va-xxl': 'none',
			'_ff-xl': 'roboto',
			'_cc-xl': 'red',
			'_fs.u-xl': 'px',
			'_fs-xl': 1,
			'_lhe.u-xl': 'px',
			'_lhe-xl': 2,
			'_ls.u-xl': 'px',
			'_ls-xl': 3,
			'_fwe-xl': '4',
			'_ttr-xl': 'none',
			'_fst-xl': 'bold',
			'_td-xl': 'underline',
			'_tsh-xl': 'none',
			'_va-xl': 'none',
			'_ff-l': 'roboto',
			'_cc-l': 'red',
			'_fs.u-l': 'px',
			'_fs-l': 1,
			'_lhe.u-l': 'px',
			'_lhe-l': 2,
			'_ls.u-l': 'px',
			'_ls-l': 3,
			'_fwe-l': '4',
			'_ttr-l': 'none',
			'_fst-l': 'bold',
			'_td-l': 'underline',
			'_tsh-l': 'none',
			'_va-l': 'none',
			'_ff-m': 'roboto',
			'_cc-m': 'red',
			'_fs.u-m': 'px',
			'_fs-m': 1,
			'_lhe.u-m': 'px',
			'_lhe-m': 2,
			'_ls.u-m': 'px',
			'_ls-m': 3,
			'_fwe-m': '4',
			'_ttr-m': 'none',
			'_fst-m': 'bold',
			'_td-m': 'underline',
			'_tsh-m': 'none',
			'_va-m': 'none',
			'_ff-s': 'roboto',
			'_cc-s': 'red',
			'_fs.u-s': 'px',
			'_fs-s': 1,
			'_lhe.u-s': 'px',
			'_lhe-s': 2,
			'_ls.u-s': 'px',
			'_ls-s': 3,
			'_fwe-s': '4',
			'_ttr-s': 'none',
			'_fst-s': 'bold',
			'_td-s': 'underline',
			'_tsh-s': 'none',
			'_va-s': 'none',
			'_ff-xs': 'roboto',
			'_cc-xs': 'red',
			'_fs.u-xs': 'px',
			'_fs-xs': 1,
			'_lhe.u-xs': 'px',
			'_lhe-xs': 2,
			'_ls.u-xs': 'px',
			'_ls-xs': 3,
			'_fwe-xs': '4',
			'_ttr-xs': 'none',
			'_fst-xs': 'bold',
			'_td-xs': 'underline',
			'_tsh-xs': 'none',
			'_va-xs': 'none',
			_cf: 'object',
		};
		const target = 'test';
		const isHover = false;
		const textLevel = 'p';

		const result = getCustomFormatsStyles(
			target,
			object,
			isHover,
			objectTypography,
			textLevel
		);
		expect(result).toMatchSnapshot();
	});
});
