import getIconStyles from '../getIconStyles';

describe('getIconStyles', () => {
	it('Get a correct icon styles', () => {
		const object = {
			'icon-name': 'icon',
			'icon-spacing': 1,
			'icon-color': 'rgb(255, 99, 71)',
			'icon-background-color': 'rgb(255, 99, 71)',
			'icon-background-active-media': 'none',
			'icon-background-gradient': 'none',
			'icon-background-gradient-opacity': 0.99,
			'icon-position': 'top',
			'icon-custom-padding': true,
			'icon-size-general': 3,
			'icon-size-unit-general': 'px',
			'icon-padding-top-general': 'none',
			'icon-padding-right-general': 'none',
			'icon-padding-bottom-general': 'none',
			'icon-padding-left-general': 'none',
			'icon-border-top-left-radius-general': 1,
			'icon-border-top-right-radius-general': 2,
			'icon-border-bottom-right-radius-general': 3,
			'icon-border-bottom-left-radius-general': 4,
			'icon-border-sync-radius-general': false,
			'icon-border-unit-radius-general': 'none',
			'icon-size-xxl': 3,
			'icon-size-unit-xxl': 'px',
			'icon-padding-top-xxl': 'none',
			'icon-padding-right-xxl': 'none',
			'icon-padding-bottom-xxl': 'none',
			'icon-padding-left-xxl': 'none',
			'icon-border-top-left-radius-xxl': 1,
			'icon-border-top-right-radius-xxl': 2,
			'icon-border-bottom-right-radius-xxl': 3,
			'icon-border-bottom-left-radius-xxl': 4,
			'icon-border-sync-radius-xxl': false,
			'icon-border-unit-radius-xxl': 'none',
			'icon-size-xl': 3,
			'icon-size-unit-xl': 'px',
			'icon-padding-top-xl': 'none',
			'icon-padding-right-xl': 'none',
			'icon-padding-bottom-xl': 'none',
			'icon-padding-left-xl': 'none',
			'icon-border-top-left-radius-xl': 1,
			'icon-border-top-right-radius-xl': 2,
			'icon-border-bottom-right-radius-xl': 3,
			'icon-border-bottom-left-radius-xl': 4,
			'icon-border-sync-radius-xl': false,
			'icon-border-unit-radius-xl': 'px',
			'icon-size-l': 3,
			'icon-size-unit-l': 'px',
			'icon-padding-top-l': 'none',
			'icon-padding-right-l': 'none',
			'icon-padding-bottom-l': 'none',
			'icon-padding-left-l': 'none',
			'icon-border-top-left-radius-l': 1,
			'icon-border-top-right-radius-l': 2,
			'icon-border-bottom-right-radius-l': 3,
			'icon-border-bottom-left-radius-l': 4,
			'icon-border-sync-radius-l': false,
			'icon-border-unit-radius-l': 'px',
			'icon-size-m': 3,
			'icon-size-unit-m': 'px',
			'icon-padding-top-m': 'none',
			'icon-padding-right-m': 'none',
			'icon-padding-bottom-m': 'none',
			'icon-padding-left-m': 'none',
			'icon-border-top-left-radius-m': 1,
			'icon-border-top-right-radius-m': 2,
			'icon-border-bottom-right-radius-m': 3,
			'icon-border-bottom-left-radius-m': 4,
			'icon-border-sync-radius-m': false,
			'icon-border-unit-radius-m': 'px',
			'icon-size-s': 3,
			'icon-size-unit-s': 'px',
			'icon-padding-top-s': 'none',
			'icon-padding-right-s': 'none',
			'icon-padding-bottom-s': 'none',
			'icon-padding-left-s': 'none',
			'icon-border-top-left-radius-s': 1,
			'icon-border-top-right-radius-s': 2,
			'icon-border-bottom-right-radius-s': 3,
			'icon-border-bottom-left-radius-s': 4,
			'icon-border-sync-radius-s': false,
			'icon-border-unit-radius-s': 'px',
			'icon-size-xs': 3,
			'icon-size-unit-xs': 'px',
			'icon-padding-top-xs': 'none',
			'icon-padding-right-xs': 'none',
			'icon-padding-bottom-xs': 'none',
			'icon-padding-left-xs': 'none',
			'icon-border-top-left-radius-xs': 1,
			'icon-border-top-right-radius-xs': 2,
			'icon-border-bottom-right-radius-xs': 3,
			'icon-border-bottom-left-radius-xs': 4,
			'icon-border-sync-radius-xs': false,
			'icon-border-unit-radius-xs': 'px',
			'icon-border-top-width-general': 1,
			'icon-border-right-width-general': 2,
			'icon-border-bottom-width-general': 3,
			'icon-border-left-width-general': 4,
			'icon-border-sync-width-general': true,
			'icon-border-unit-width-general': 'px',
			'icon-border-top-width-xxl': 1,
			'icon-border-right-width-xxl': 2,
			'icon-border-bottom-width-xxl': 3,
			'icon-border-left-width-xxl': 4,
			'icon-border-sync-width-xxl': true,
			'icon-border-unit-width-xxl': 'px',
			'icon-border-top-width-xl': 1,
			'icon-border-right-width-xl': 2,
			'icon-border-bottom-width-xl': 3,
			'icon-border-left-width-xl': 4,
			'icon-border-sync-width-xl': true,
			'icon-border-unit-width-xl': 'px',
			'icon-border-top-width-l': 1,
			'icon-border-right-width-l': 2,
			'icon-border-bottom-width-l': 3,
			'icon-border-left-width-l': 4,
			'icon-border-sync-width-l': true,
			'icon-border-unit-width-l': 'px',
			'icon-border-top-width-m': 1,
			'icon-border-right-width-m': 2,
			'icon-border-bottom-width-m': 3,
			'icon-border-left-width-m': 4,
			'icon-border-sync-width-m': true,
			'icon-border-unit-width-m': 'px',
			'icon-border-top-width-s': 1,
			'icon-border-right-width-s': 2,
			'icon-border-bottom-width-s': 3,
			'icon-border-left-width-s': 4,
			'icon-border-sync-width-s': true,
			'icon-border-unit-width-s': 'px',
			'icon-border-top-width-xs': 1,
			'icon-border-right-width-xs': 2,
			'icon-border-bottom-width-xs': 3,
			'icon-border-left-width-xs': 4,
			'icon-border-sync-width-xs': true,
			'icon-border-unit-width-xs': 'px',
			'icon-border-color-general': 'rgb(255, 99, 71)',
			'icon-border-style-general': 'none',
			'icon-border-color-xxl': 'rgb(255, 99, 71)',
			'icon-border-style-xxl': 'none',
			'icon-border-color-xl': 'rgb(255, 99, 71)',
			'icon-border-style-xl': 'none',
			'icon-border-color-l': 'rgb(255, 99, 71)',
			'icon-border-style-l': 'none',
			'icon-border-color-m': 'rgb(255, 99, 71)',
			'icon-border-style-m': 'none',
			'icon-border-color-s': 'rgb(255, 99, 71)',
			'icon-border-style-s': 'none',
			'icon-border-color-xs': 'rgb(255, 99, 71)',
			'icon-border-style-xs': 'none',
		};
		const result = getIconStyles(object);
		expect(result).toMatchSnapshot();
	});
});
