import getIconStyles from '../getIconStyles';
// import {
// iconPadding,
// iconBorder,
// iconBorderWidth,
// iconBorderRadius,
// } from './icon';
// import  from '../getIconStyles';

describe('getIconStyles', () => {
	it('Get a correct Icon Styles', () => {
		const object = {
			// iconPadding:
			'icon-name': 'icon',
			'icon-spacing': 1,
			'icon-color': 'red',
			'icon-background-color': 'black',
			'icon-background-active-media': 'none',
			'icon-background-gradient': 'none',
			'icon-background-gradient-opacity': 2,
			'icon-position': 'top',
			'icon-size-general': 3,
			'icon-size-unit-general': 'test',
			'icon-custom-padding': 'true',
			'icon-padding-top-general': 'test',
			'icon-padding-right-general': 'test',
			'icon-padding-bottom-general': 'test',
			'icon-padding-left-general': 'test',
			'icon-border-top-left-radius-general': 1,
			'icon-border-top-right-radius-general': 2,
			'icon-border-bottom-right-radius-general': 3,
			'icon-border-bottom-left-radius-general': 4,
			'icon-border-sync-radius-general': 'false',
			'icon-border-unit-radius-general': 'test',
			'icon-border-top-left-radius-xxl': 1,
			'icon-border-top-right-radius-xxl': 2,
			'icon-border-bottom-right-radius-xxl': 3,
			'icon-border-bottom-left-radius-xxl': 4,
			'icon-border-sync-radius-xxl': 'false',
			'icon-border-unit-radius-xxl': 'test',
			'icon-border-top-left-radius-xl': 1,
			'icon-border-top-right-radius-xl': 2,
			'icon-border-bottom-right-radius-xl': 2,
			'icon-border-bottom-left-radius-xl': 3,
			'icon-border-sync-radius-xl': 'false',
			'icon-border-unit-radius-xl': 'test',
			'icon-border-top-left-radius-l': 1,
			'icon-border-top-right-radius-l': 2,
			'icon-border-bottom-right-radius-l': 3,
			'icon-border-bottom-left-radius-l': 4,
			'icon-border-sync-radius-l': 'false',
			'icon-border-unit-radius-l': 'test',
			'icon-border-top-left-radius-m': 1,
			'icon-border-top-right-radius-m': 2,
			'icon-border-bottom-right-radius-m': 3,
			'icon-border-bottom-left-radius-m': 4,
			'icon-border-sync-radius-m': 'false',
			'icon-border-unit-radius-m': 'test',
			'icon-border-top-left-radius-s': 1,
			'icon-border-top-right-radius-s': 2,
			'icon-border-bottom-right-radius-s': 3,
			'icon-border-bottom-left-radius-s': 4,
			'icon-border-sync-radius-s': 'false',
			'icon-border-unit-radius-s': 'test',
			'icon-border-top-left-radius-xs': 1,
			'icon-border-top-right-radius-xs': 2,
			'icon-border-bottom-right-radius-xs': 3,
			'icon-border-bottom-left-radius-xs': 4,
			'icon-border-sync-radius-xs': 'false',
			'icon-border-unit-radius-xs': 'test',
			'icon-border-top-width-general': 1,
			'icon-border-right-width-general': 2,
			'icon-border-bottom-width-general': 3,
			'icon-border-left-width-general': 4,
			'icon-border-sync-width-general': 'true',
			'icon-border-unit-width-general': 'test',
			'icon-border-top-width-xxl': 1,
			'icon-border-right-width-xxl': 2,
			'icon-border-bottom-width-xxl': 3,
			'icon-border-left-width-xxl': 4,
			'icon-border-sync-width-xxl': 'true',
			'icon-border-unit-width-xxl': 'test',
			'icon-border-top-width-xl': 1,
			'icon-border-right-width-xl': 2,
			'icon-border-bottom-width-xl': 3,
			'icon-border-left-width-xl': 4,
			'icon-border-sync-width-xl': 'true',
			'icon-border-unit-width-xl': 'test',
			'icon-border-top-width-l': 1,
			'icon-border-right-width-l': 2,
			'icon-border-bottom-width-l': 3,
			'icon-border-left-width-l': 4,
			'icon-border-sync-width-l': 'true',
			'icon-border-unit-width-l': 'test',
			'icon-border-top-width-m': 1,
			'icon-border-right-width-m': 2,
			'icon-border-bottom-width-m': 3,
			'icon-border-left-width-m': 4,
			'icon-border-sync-width-m': 'true',
			'icon-border-unit-width-m': 'test',
			'icon-border-top-width-s': 1,
			'icon-border-right-width-s': 2,
			'icon-border-bottom-width-s': 3,
			'icon-border-left-width-s': 4,
			'icon-border-sync-width-s': 'true',
			'icon-border-unit-width-s': 'test',
			'icon-border-top-width-xs': 1,
			'icon-border-right-width-xs': 2,
			'icon-border-bottom-width-xs': 3,
			'icon-border-left-width-xs': 4,
			'icon-border-sync-width-xs': 'true',
			'icon-border-unit-width-xs': 'test',
			'icon-border-color-general': 'test',
			'icon-border-style-general': 'test',
			'icon-border-color-xxl': 'test',
			'icon-border-style-xxl': 'test',
			'icon-border-color-xl': 'test',
			'icon-border-style-xl': 'test',
			'icon-border-color-l': 'test',
			'icon-border-style-l': 'test',
			'icon-border-color-m': 'test',
			'icon-border-style-m': 'test',
			'icon-border-color-s': 'test',
			'icon-border-style-s': 'test',
			'icon-border-color-xs': 'test',
			'icon-border-style-xs': 'test',
		};
		const result = getIconStyles(object);
		expect(result).toMatchSnapshot();
	});
});
