import getPositionStyles from '../getPositionStyles';

describe('getPositionStyles', () => {
	it('Get a correct position styles', () => {
		const object = {
			'_pos-general': 'relative',
			'_pos-xxl': 'absolute',
			'_pos-xl': 'relative',
			'_pos-l': 'absolute',
			'_pos-m': 'relative',
			'_pos-s': 'absolute',
			'_pos-xs': 'relative',
			'_pos.t-general': 1,
			'_pos.r-general': 2,
			'_pos.b-general': 3,
			'_pos.l-general': 4,
			'_pos.sy-general': true,
			'_pos.t.u-general': 'px',
			'_pos.r.u-general': 'em',
			'_pos.b.u-general': 'vw',
			'_pos.l.u-general': '%',
			'_pos.t-xxl': 1,
			'_pos.r-xxl': 2,
			'_pos.b-xxl': 3,
			'_pos.l-xxl': 4,
			'_pos.sy-xxl': true,
			'_pos.u-xxl': 'px',
			'_pos.t-xl': 1,
			'_pos.r-xl': 2,
			'_pos.b-xl': 3,
			'_pos.l-xl': 4,
			'_pos.sy-xl': true,
			'_pos.t.u-xl': 'px',
			'_pos.r.u-xl': 'em',
			'_pos.b.u-xl': 'vw',
			'_pos.l.u-xl': '%',
			'_pos.t-l': 1,
			'_pos.r-l': 2,
			'_pos.b-l': 3,
			'_pos.l-l': 4,
			'_pos.sy-l': true,
			'_pos.t.u-l': 'px',
			'_pos.r.u-l': 'em',
			'_pos.b.u-l': 'vw',
			'_pos.l.u-l': '%',
			'_pos.t-m': 1,
			'_pos.r-m': 2,
			'_pos.b-m': 3,
			'_pos.l-m': 4,
			'_pos.sy-m': true,
			'_pos.u.t-m': 'px',
			'_pos.u.r-m': 'em',
			'_pos.u.b-m': 'vw',
			'_pos.u.l-m': '%',
			'_pos.t-s': 1,
			'_pos.r-s': 2,
			'_pos.b-s': 3,
			'_pos.l-s': 4,
			'_pos.sy-s': true,
			'_pos.t.u-s': 'px',
			'_pos.r.u-s': 'em',
			'_pos.b.u-s': 'vw',
			'_pos.l.u-s': '%',
			'_pos.t-xs': 1,
			'_pos.r-xs': 2,
			'_pos.b-xs': 3,
			'_pos.l-xs': 4,
			'_pos.sy-xs': true,
			'_pos.t.u-xs': 'px',
			'_pos.r.u-xs': 'em',
			'_pos.b.u-xs': 'vw',
			'_pos.l.u-xs': '%',
		};
		const result = getPositionStyles(object);
		expect(result).toMatchSnapshot();
	});

	it('Ensure unnecessary position styles are not added', () => {
		const object = {
			'_pos-general': 'inherit',
			'_pos.t.u-xl': 'px',
			'_pos.r.u-xl': 'em',
			'_pos.b.u-xl': 'vw',
			'_pos.l.u-xl': '%',
			'_pos.t-l': 1,
			'_pos.r-l': 2,
			'_pos.b-l': 3,
			'_pos.l-l': 4,
			'_pos.sy-l': true,
			'_pos-m': 'relative',
			'_pos.l.u-s': '%',
			'_pos.t-xs': 1,
			'_pos.r-xs': 2,
			'_pos.b-xs': 3,
			'_pos.l-xs': 4,
			'_pos.sy-xs': true,
		};
		const result = getPositionStyles(object);
		expect(result).toMatchSnapshot();

		const object2 = {
			'_pos-general': 'relative',
			'_pos.t-general': 1,
			'_pos.r-general': 2,
			'_pos.b-general': 3,
			'_pos.l-general': 4,
			'_pos.sy-general': true,
			'_pos.t.u-general': 'px',
			'_pos.r.u-general': 'em',
			'_pos.b.u-general': 'vw',
			'_pos.l.u-general': '%',
			'_pos.t.u-xl': 'px',
			'_pos.r.u-xl': 'em',
			'_pos.b.u-xl': 'vw',
			'_pos.l.u-xl': '%',
			'_pos.t-l': 1,
			'_pos.r-l': 2,
			'_pos.b-l': 3,
			'_pos.l-l': 4,
			'_pos.sy-l': true,
			'_pos-m': 'inherit',
			'_pos.l.u-s': '%',
			'_pos.t-xs': 1,
			'_pos.r-xs': 2,
			'_pos.b-xs': 3,
			'_pos.l-xs': 4,
			'_pos.sy-xs': true,
		};

		const result2 = getPositionStyles(object2);
		expect(result2).toMatchSnapshot();
	});
});
