import parseLongAttrObj from '../../../attributes/dictionary/parseLongAttrObj';
import getSizeStyles from '../getSizeStyles';

jest.mock('../../getDefaultAttribute', () => {
	return jest.fn(attribute => {
		return attribute.includes('general') ? 'normal' : undefined;
	});
});

describe('getSizeStyles', () => {
	it('Get a correct size styles', () => {
		const object = parseLongAttrObj({
			_sao: true,
			'_mw-unit-general': 'px',
			'_mw-general': '2',
			'_w-unit-general': 'px',
			'_w-general': '1',
			'_miw-unit-general': 'px',
			'_miw-general': '2',
			'_mh-unit-general': 'px',
			'_mh-general': '3',
			'_h-unit-general': 'px',
			'_h-general': '4',
			'_mh-unit-general': 'px',
			'_mh-general': '1',
			'_mw-xxl': '2',
			'_w-unit-xxl': 'px',
			'_w-xxl': '3',
			'_miw-xxl': '4',
			'_mh-unit-xxl': 'px',
			'_mh-xxl': '1',
			'_h-xxl': '2',
			'_mh-unit-xxl': 'px',
			'_mh-xxl': '2',
			'_mw-unit-xl': 'px',
			'_mw-xl': '3',
			'_w-unit-xl': 'px',
			'_w-xl': '4',
			'_miw-unit-xl': 'px',
			'_miw-xl': '1',
			'_mh-unit-xl': 'px',
			'_mh-xl': '2',
			'_h-unit-xl': 'px',
			'_h-xl': '3',
			'_mh-unit-xl': 'px',
			'_mh-xl': '4',
			'_mw-unit-l': 'px',
			'_mw-l': '2',
			'_w-unit-l': 'px',
			'_w-l': '1',
			'_miw-unit-l': 'px',
			'_miw-l': '3',
			'_mh-unit-l': 'px',
			'_mh-l': '2',
			'_h-unit-l': 'px',
			'_h-l': '1',
			'_mh-unit-l': 'px',
			'_mh-l': '1',
			'_mw-unit-m': 'px',
			'_mw-m': '2',
			'_w-unit-m': 'px',
			'_w-m': '3',
			'_miw-unit-m': 'px',
			'_miw-m': '4',
			'_mh-unit-m': 'px',
			'_mh-m': '1',
			'_h-unit-m': 'px',
			'_h-m': '2',
			'_mh-unit-m': 'px',
			'_mh-m': '2',
			'_mw-unit-s': 'px',
			'_mw-s': '3',
			'_w-unit-s': 'px',
			'_w-s': '4',
			'_miw-unit-s': 'px',
			'_miw-s': '1',
			'_mh-unit-s': 'px',
			'_mh-s': '1',
			'_h-unit-s': 'px',
			'_h-s': '1',
			'_mh-unit-s': 'px',
			'_mh-s': '2',
			'_mw-unit-xs': 'px',
			'_mw-xs': '3',
			'_w-unit-xs': 'px',
			'_w-xs': '4',
			'_miw-unit-xs': 'px',
			'_miw-xs': '1',
			'_mh-unit-xs': 'px',
			'_mh-xs': '2',
			'_h-unit-xs': 'px',
			'_h-xs': '3',
			'_mh-unit-xs': 'px',
			'_mh-xs': '4',
		});

		const result = getSizeStyles(object);
		expect(result).toMatchSnapshot();
	});

	it('Get a correct size styles with force aspect ratio', () => {
		const object = parseLongAttrObj({
			_sao: true,
			'_mw-unit-general': 'px',
			'_mw-general': '2',
			'_w-unit-general': 'px',
			'_w-general': '1',
			'_miw-unit-general': 'px',
			'_miw-general': '2',
			'_mh-unit-general': 'px',
			'_mh-general': '3',
			'_h-unit-general': 'px',
			'_h-general': '4',
			'_mh-unit-general': 'px',
			'_mh-general': '1',
			'_mw-unit-xxl': 'px',
			'_mw-xxl': '2',
			'_w-unit-xxl': 'px',
			'_w-xxl': '3',
			'_miw-unit-xxl': 'px',
			'_miw-xxl': '4',
			'_mh-unit-xxl': 'px',
			'_mh-xxl': '1',
			'_h-unit-xxl': 'px',
			'_h-xxl': '2',
			'_mh-unit-xxl': 'px',
			'_mh-xxl': '2',
			'_mw-unit-xl': 'px',
			'_mw-xl': '3',
			'_w-unit-xl': 'px',
			'_w-xl': '4',
			'_miw-unit-xl': 'px',
			'_miw-xl': '1',
			'_mh-unit-xl': 'px',
			'_mh-xl': '2',
			'_far-xl': true,
			'_mh-xl': '4',
			'_mw-unit-l': 'px',
			'_mw-l': '2',
			'_w-unit-l': 'px',
			'_w-l': '1',
			'_miw-unit-l': 'px',
			'_miw-l': '3',
			'_mh-unit-l': 'px',
			'_mh-l': '2',
			'_mh-unit-l': 'px',
			'_mh-l': '1',
			'_mw-unit-m': 'px',
			'_mw-m': '2',
			'_w-unit-m': 'px',
			'_w-m': '3',
			'_miw-unit-m': 'px',
			'_miw-m': '4',
			'_mh-unit-m': 'px',
			'_mh-m': '1',
			'_mh-unit-m': 'px',
			'_mh-m': '2',
			'_mw-unit-s': 'px',
			'_mw-s': '3',
			'_w-unit-s': 'px',
			'_w-s': '4',
			'_miw-unit-s': 'px',
			'_miw-s': '1',
			'_mh-unit-s': 'px',
			'_mh-s': '1',
			'_h-unit-s': 'px',
			'_h-s': '1',
			'_mh-unit-s': 'px',
			'_mh-s': '2',
			'_mw-unit-xs': 'px',
			'_mw-xs': '3',
			'_w-unit-xs': 'px',
			'_w-xs': '4',
			'_miw-unit-xs': 'px',
			'_miw-xs': '1',
			'_mh-unit-xs': 'px',
			'_mh-xs': '2',
			'_h-unit-xs': 'px',
			'_h-xs': '3',
			'_mh-unit-xs': 'px',
			'_mh-xs': '4',
		});
		const result = getSizeStyles(object);
		expect(result).toMatchSnapshot();
	});

	it('Get a correct size styles with width fit content', () => {
		const object = parseLongAttrObj({
			_sao: true,
			'_mw-unit-general': 'px',
			'_mw-general': '2',
			'_w-unit-general': 'px',
			'_w-general': 'fit-content',
			'_miw-unit-general': 'px',
			'_miw-general': '2',
			'_mh-unit-general': 'px',
			'_mh-general': '3',
			'_h-unit-general': 'px',
			'_h-general': '4',
			'_mh-unit-general': 'px',
			'_mh-general': '1',
			'_mw-unit-xxl': 'px',
			'_mw-xxl': '2',
			'_w-unit-xxl': 'px',
			'_w-xxl': '3',
			'_miw-unit-xxl': 'px',
			'_miw-xxl': '4',
			'_mh-unit-xxl': 'px',
			'_mh-xxl': '1',
			'_h-unit-xxl': 'px',
			'_h-xxl': '2',
			'_mh-unit-xxl': 'px',
			'_mh-xxl': '2',
			'_mw-unit-xl': 'px',
			'_mw-xl': '3',
			'_w-unit-xl': 'px',
			'_w-xl': '4',
			'_miw-unit-xl': 'px',
			'_miw-xl': '1',
			'_mh-unit-xl': 'px',
			'_mh-xl': '2',
			'_mh-unit-xl': 'px',
			'_mh-xl': '4',
			'_mw-unit-l': 'px',
			'_mw-l': '2',
			'_w-unit-l': 'px',
			'_w-l': '1',
			'_miw-unit-l': 'px',
			'_miw-l': '3',
			'_mh-unit-l': 'px',
			'_mh-l': '2',
			'_mh-unit-l': 'px',
			'_mh-l': '1',
			'_mw-unit-m': 'px',
			'_mw-m': '2',
			'_w-unit-m': 'px',
			'_w-m': '3',
			'_miw-unit-m': 'px',
			'_miw-m': '4',
			'_mh-unit-m': 'px',
			'_mh-m': '1',
			'_mh-unit-m': 'px',
			'_mh-m': '2',
			'_mw-unit-s': 'px',
			'_mw-s': '3',
			'_w-unit-s': 'px',
			'_w-s': '4',
			'_miw-unit-s': 'px',
			'_miw-s': '1',
			'_mh-unit-s': 'px',
			'_mh-s': '1',
			'_h-unit-s': 'px',
			'_h-s': '1',
			'_mh-unit-s': 'px',
			'_mh-s': '2',
			'_mw-unit-xs': 'px',
			'_mw-xs': '3',
			'_w-unit-xs': 'px',
			'_w-xs': '4',
			'_miw-unit-xs': 'px',
			'_miw-xs': '1',
			'_mh-unit-xs': 'px',
			'_mh-xs': '2',
			'_h-unit-xs': 'px',
			'_h-xs': '3',
			'_mh-unit-xs': 'px',
			'_mh-xs': '4',
			'_wfc-general': true,
		});

		const result = getSizeStyles(object);
		expect(result).toMatchSnapshot();
	});

	it('Get a correct size styles with full width', () => {
		const object = parseLongAttrObj({
			'full-width-general': 'full',
			'full-width-l': 'normal',
		});

		const result = getSizeStyles(object);
		expect(result).toMatchSnapshot();
	});

	it('Get a correct size styles with full width 2', () => {
		const object = parseLongAttrObj({
			_sao: true,
			'full-width-general': 'full',
			'full-width-xl': 'normal',
			'full-width-l': 'full',
			'_miw-l': '2',
			'_miw-unit-l': 'px',
			'full-width-m': 'normal',
			'_miw-m': '3',
			'_miw-s': '0',
		});

		const result = getSizeStyles(object);
		expect(result).toMatchSnapshot();
	});

	it('Get a correct size styles with full width 3', () => {
		const object = parseLongAttrObj({
			'full-width-general': 'full',
			_sao: true,
			'_mw-unit-general': 'px',
			'_mw-general': '2',
			'_w-unit-general': 'px',
			'_w-general': 'fit-content',
			'_miw-unit-general': 'px',
			'_miw-general': '2',
			'_mh-unit-general': 'px',
			'_mh-general': '3',
			'_h-unit-general': 'px',
			'_h-general': '4',
			'_mh-unit-general': 'px',
			'_mh-general': '1',
		});

		const result = getSizeStyles(object);
		expect(result).toMatchSnapshot();
	});

	it('Get a correct size styles with full width responsive', () => {
		const object = parseLongAttrObj({
			'full-width-general': 'full',
			_sao: true,
			'_mw-unit-general': 'px',
			'_mw-general': '2',
			'_w-unit-general': 'px',
			'_w-general': 'fit-content',
			'_miw-unit-general': 'px',
			'_miw-general': '2',
			'_mh-unit-general': 'px',
			'_mh-general': '3',
			'_h-unit-general': 'px',
			'_h-general': '4',
			'_mh-unit-general': 'px',
			'_mh-general': '1',
			'full-width-xxl': 'normal',
			'_mw-unit-xxl': 'px',
			'_mw-xxl': '2',
			'_w-unit-xxl': 'px',
			'_w-xxl': '3',
			'_miw-unit-xxl': 'px',
			'_miw-xxl': '4',
			'_mh-unit-xxl': 'px',
			'_mh-xxl': '1',
			'_h-unit-xxl': 'px',
			'_h-xxl': '2',
			'_mh-unit-xxl': 'px',
			'_mh-xxl': '2',
			'full-width-xl': 'full',
			'_mw-unit-xl': 'px',
			'_mw-xl': '3',
			'_w-unit-xl': 'px',
			'_w-xl': '4',
			'_miw-unit-xl': 'px',
			'_miw-xl': '1',
			'_mh-unit-xl': 'px',
			'_mh-xl': '2',
			'_mh-unit-xl': 'px',
			'_mh-xl': '4',
			'full-width-l': 'normal',
			'_mw-unit-l': 'px',
			'_mw-l': '2',
			'_w-unit-l': 'px',
			'_w-l': '1',
			'_miw-unit-l': 'px',
			'_miw-l': '3',
			'_mh-unit-l': 'px',
			'_mh-l': '2',
			'_mh-unit-l': 'px',
			'_mh-l': '1',
			'full-width-m': 'full',
			'_mw-unit-m': 'px',
			'_mw-m': '2',
			'_w-unit-m': 'px',
			'_w-m': '3',
			'_miw-unit-m': 'px',
			'_miw-m': '4',
			'_mh-unit-m': 'px',
			'_mh-m': '1',
			'_mh-unit-m': 'px',
			'_mh-m': '2',
			'full-width-s': 'normal',
			'_mw-unit-s': 'px',
			'_mw-s': '3',
			'_w-unit-s': 'px',
			'_w-s': '4',
			'_miw-unit-s': 'px',
			'_miw-s': '1',
			'_mh-unit-s': 'px',
			'_mh-s': '1',
			'_h-unit-s': 'px',
			'_h-s': '1',
			'_mh-unit-s': 'px',
			'_mh-s': '2',
			'full-width-xs': 'full',
			'_mw-unit-xs': 'px',
			'_mw-xs': '3',
			'_w-unit-xs': 'px',
			'_w-xs': '4',
			'_miw-unit-xs': 'px',
			'_miw-xs': '1',
			'_mh-unit-xs': 'px',
			'_mh-xs': '2',
			'_h-unit-xs': 'px',
			'_h-xs': '3',
			'_mh-unit-xs': 'px',
			'_mh-xs': '4',
			'_wfc-general': true,
		});

		const result = getSizeStyles(object);
		expect(result).toMatchSnapshot();
	});

	it('Get a correct size styles with full width responsive 2', () => {
		const object = parseLongAttrObj({
			'full-width-general': 'normal',
			_sao: true,
			'_mw-unit-general': 'px',
			'_mw-general': '2',
			'_w-unit-general': 'px',
			'_w-general': 'fit-content',
			'_miw-unit-general': 'px',
			'_miw-general': '2',
			'_mh-unit-general': 'px',
			'_mh-general': '3',
			'_h-unit-general': 'px',
			'_h-general': '4',
			'_mh-unit-general': 'px',
			'_mh-general': '1',
			'full-width-xxl': 'full',
			'_mw-unit-xxl': 'px',
			'_mw-xxl': '2',
			'_w-unit-xxl': 'px',
			'_w-xxl': '3',
			'_miw-unit-xxl': 'px',
			'_miw-xxl': '4',
			'_mh-unit-xxl': 'px',
			'_mh-xxl': '1',
			'_h-unit-xxl': 'px',
			'_h-xxl': '2',
			'_mh-unit-xxl': 'px',
			'_mh-xxl': '2',
			'full-width-xl': 'normal',
			'_mw-unit-xl': 'px',
			'_mw-xl': '3',
			'_w-unit-xl': 'px',
			'_w-xl': '4',
			'_miw-unit-xl': 'px',
			'_miw-xl': '1',
			'_mh-unit-xl': 'px',
			'_mh-xl': '2',
			'_mh-unit-xl': 'px',
			'_mh-xl': '4',
			'full-width-l': 'full',
			'_mw-unit-l': 'px',
			'_mw-l': '2',
			'_w-unit-l': 'px',
			'_w-l': '1',
			'_miw-unit-l': 'px',
			'_miw-l': '3',
			'_mh-unit-l': 'px',
			'_mh-l': '2',
			'_mh-unit-l': 'px',
			'_mh-l': '1',
			'full-width-m': 'normal',
			'_mw-unit-m': 'px',
			'_mw-m': '2',
			'_w-unit-m': 'px',
			'_w-m': '3',
			'_mh-unit-m': 'px',
			'_mh-m': '1',
			'_mh-unit-m': 'px',
			'_mh-m': '2',
			'full-width-s': 'full',
			'_mw-unit-s': 'px',
			'_mw-s': '3',
			'_w-unit-s': 'px',
			'_w-s': '4',
			'_mh-unit-s': 'px',
			'_mh-s': '1',
			'_h-unit-s': 'px',
			'_h-s': '1',
			'_mh-unit-s': 'px',
			'_mh-s': '2',
			'full-width-xs': 'normal',
			'_mw-unit-xs': 'px',
			'_mw-xs': '3',
			'_w-unit-xs': 'px',
			'_w-xs': '4',
			'_miw-unit-xs': 'px',
			'_miw-xs': '1',
			'_mh-unit-xs': 'px',
			'_mh-xs': '2',
			'_h-unit-xs': 'px',
			'_h-xs': '3',
			'_mh-unit-xs': 'px',
			'_mh-xs': '4',
			'_wfc-general': true,
		});

		const result = getSizeStyles(object);
		expect(result).toMatchSnapshot();
	});
});
