import getSizeStyles from '../getSizeStyles';
import '@wordpress/block-editor';

describe('getSizeStyles', () => {
	it('Get a correct alignment', () => {
		const object = {
			'size-advanced-options': 'true',
			'max-width-unit-general': 'test',
			'max-width-general': 2,
			'width-unit-general': 'test',
			'width-general': 1,
			'min-width-unit-general': 'test',
			'min-width-general': 2,
			'max-height-unit-general': 'test',
			'max-height-general': 3,
			'height-unit-general': 'test',
			'height-general': 4,
			'min-height-unit-general': 'test',
			'min-height-general': 1,
			'max-width-unit-xxl': 'test',
			'max-width-xxl': 2,
			'width-unit-xxl': 'test',
			'width-xxl': 3,
			'min-width-unit-xxl': 'test',
			'min-width-xxl': 4,
			'max-height-unit-xxl': 'test',
			'max-height-xxl': 1,
			'height-unit-xxl': 'test',
			'height-xxl': 2,
			'min-height-unit-xxl': 'test',
			'min-height-xxl': 2,
			'max-width-unit-xl': 'test',
			'max-width-xl': 3,
			'width-unit-xl': 'test',
			'width-xl': 4,
			'min-width-unit-xl': 'test',
			'min-width-xl': 1,
			'max-height-unit-xl': 'test',
			'max-height-xl': 2,
			'height-unit-xl': 'test',
			'height-xl': 3,
			'min-height-unit-xl': 'test',
			'min-height-xl': 4,
			'max-width-unit-l': 'test',
			'max-width-l': 2,
			'width-unit-l': 'test',
			'width-l': 1,
			'min-width-unit-l': 'test',
			'min-width-l': 3,
			'max-height-unit-l': 'test',
			'max-height-l': 2,
			'height-unit-l': 'test',
			'height-l': 1,
			'min-height-unit-l': 'test',
			'min-height-l': 1,
			'max-width-unit-m': 'test',
			'max-width-m': 2,
			'width-unit-m': 'test',
			'width-m': 3,
			'min-width-unit-m': 'test',
			'min-width-m': 4,
			'max-height-unit-m': 'test',
			'max-height-m': 1,
			'height-unit-m': 'test',
			'height-m': 2,
			'min-height-unit-m': 'test',
			'min-height-m': 2,
			'max-width-unit-s': 'test',
			'max-width-s': 3,
			'width-unit-s': 'test',
			'width-s': 4,
			'min-width-unit-s': 'test',
			'min-width-s': 1,
			'max-height-unit-s': 'test',
			'max-height-s': 1,
			'height-unit-s': 'test',
			'height-s': 1,
			'min-height-unit-s': 'test',
			'min-height-s': 2,
			'max-width-unit-xs': 'test',
			'max-width-xs': 3,
			'width-unit-xs': 'test',
			'width-xs': 4,
			'min-width-unit-xs': 'test',
			'min-width-xs': 1,
			'max-height-unit-xs': 'test',
			'max-height-xs': 2,
			'height-unit-xs': 'test',
			'height-xs': 3,
			'min-height-unit-xs': 'test',
			'min-height-xs': 4,
		};

		const result = getSizeStyles(object);
		expect(result).toMatchSnapshot();
	});
});
