import getTypographyStyles from '../getTypographyStyles';
import '@wordpress/block-editor';

describe('getTypographyStyles', () => {
	it('Get a correct TypographyStyles', () => {
		const object = {
			'font-family-general': 'roboto',
			'color-general': 'blue',
			'font-size-unit-general': '1',
			'font-size-general': 1,
			'line-height-unit-general': '12',
			'line-height-general': 1,
			'letter-spacing-unit-general': '2',
			'letter-spacing-general': 2,
			'font-weight-general': 3,
			'text-transform-general': 'test',
			'font-style-general': 'test',
			'text-decoration-general': 'test',
			'text-shadow-general': 'test',
			'vertical-align-general': 'test',
			'font-family-xxl': 'test',
			'color-xxl': 'test',
			'font-size-unit-xxl': 'test',
			'font-size-xxl': 1,
			'line-height-unit-xxl': 'test',
			'line-height-xxl': 2,
			'letter-spacing-unit-xxl': 'test',
			'letter-spacing-xxl': 3,
			'font-weight-xxl': 4,
			'text-transform-xxl': 'test',
			'font-style-xxl': 'test',
			'text-decoration-xxl': 'test',
			'text-shadow-xxl': 'test',
			'vertical-align-xxl': 'test',
			'font-family-xl': 'test',
			'color-xl': 'test',
			'font-size-unit-xl': 'test',
			'font-size-xl': 1,
			'line-height-unit-xl': 'test',
			'line-height-xl': 2,
			'letter-spacing-unit-xl': 'test',
			'letter-spacing-xl': 3,
			'font-weight-xl': 4,
			'text-transform-xl': 'test',
			'font-style-xl': 'test',
			'text-decoration-xl': 'test',
			'text-shadow-xl': 'test',
			'vertical-align-xl': 'test',
			'font-family-l': 'test',
			'color-l': 'test',
			'font-size-unit-l': 'test',
			'font-size-l': 1,
			'line-height-unit-l': 'test',
			'line-height-l': 2,
			'letter-spacing-unit-l': 'test',
			'letter-spacing-l': 3,
			'font-weight-l': 4,
			'text-transform-l': 'test',
			'font-style-l': 'test',
			'text-decoration-l': 'test',
			'text-shadow-l': 'test',
			'vertical-align-l': 'test',
			'font-family-m': 'test',
			'color-m': 'test',
			'font-size-unit-m': 'test',
			'font-size-m': 1,
			'line-height-unit-m': 'test',
			'line-height-m': 2,
			'letter-spacing-unit-m': 'test',
			'letter-spacing-m': 3,
			'font-weight-m': 4,
			'text-transform-m': 'test',
			'font-style-m': 'test',
			'text-decoration-m': 'test',
			'text-shadow-m': 'test',
			'vertical-align-m': 'test',
			'font-family-s': 'test',
			'color-s': 'test',
			'font-size-unit-s': 'test',
			'font-size-s': 1,
			'line-height-unit-s': 'test',
			'line-height-s': 2,
			'letter-spacing-unit-s': 'test',
			'letter-spacing-s': 3,
			'font-weight-s': 4,
			'text-transform-s': 'test',
			'font-style-s': 'test',
			'text-decoration-s': 'test',
			'text-shadow-s': 'test',
			'vertical-align-s': 'test',
			'font-family-xs': 'test',
			'color-xs': 'test',
			'font-size-unit-xs': 'test',
			'font-size-xs': 1,
			'line-height-unit-xs': 'test',
			'line-height-xs': 2,
			'letter-spacing-unit-xs': 'test',
			'letter-spacing-xs': 3,
			'font-weight-xs': 4,
			'text-transform-xs': 'test',
			'font-style-xs': 'test',
			'text-decoration-xs': 'test',
			'text-shadow-xs': 'test',
			'vertical-align-xs': 'test',
			'custom-formats': 'object',
		};

		const result = getTypographyStyles(object);
		expect(result).toMatchSnapshot();
	});
});
