import getTransformStyles from '../getTransformStyles';
import '@wordpress/block-editor';

describe('getTransformStyles', () => {
	it('Get a correct alignment', () => {
		const object = {
			'transform-scale-x-general': 1,
			'transform-scale-y-general': 2,
			'transform-translate-x-unit-general': 'px',
			'transform-translate-x-general': 3,
			'transform-translate-y-unit-general': 'px',
			'transform-translate-y-general': 4,
			'transform-rotate-x-general': 1,
			'transform-rotate-y-general': 2,
			'transform-rotate-z-general': 3,
			'transform-origin-x-general': 'test',
			'transform-origin-y-general': 'test',
			'transform-scale-x-xxl': 4,
			'transform-scale-y-xxl': 1,
			'transform-translate-x-unit-xxl': 'px',
			'transform-translate-x-xxl': 2,
			'transform-translate-y-unit-xxl': 'px',
			'transform-translate-y-xxl': 3,
			'transform-rotate-x-xxl': 4,
			'transform-rotate-y-xxl': 1,
			'transform-rotate-z-xxl': 2,
			'transform-origin-x-xxl': 'test',
			'transform-origin-y-xxl': 'test',
			'transform-scale-x-xl': 3,
			'transform-scale-y-xl': 4,
			'transform-translate-x-unit-xl': 'px',
			'transform-translate-x-xl': 1,
			'transform-translate-y-unit-xl': 'px',
			'transform-translate-y-xl': 2,
			'transform-rotate-x-xl': 3,
			'transform-rotate-y-xl': 4,
			'transform-rotate-z-xl': 1,
			'transform-origin-x-xl': 'test',
			'transform-origin-y-xl': 'test',
			'transform-scale-x-l': 2,
			'transform-scale-y-l': 3,
			'transform-translate-x-unit-l': 'px',
			'transform-translate-x-l': 4,
			'transform-translate-y-unit-l': 'px',
			'transform-translate-y-l': 1,
			'transform-rotate-x-l': 2,
			'transform-rotate-y-l': 3,
			'transform-rotate-z-l': 4,
			'transform-origin-x-l': 'test',
			'transform-origin-y-l': 'test',
			'transform-scale-x-m': 1,
			'transform-scale-y-m': 2,
			'transform-translate-x-unit-m': 'px',
			'transform-translate-x-m': 3,
			'transform-translate-y-unit-m': 'px',
			'transform-translate-y-m': 4,
			'transform-rotate-x-m': 1,
			'transform-rotate-y-m': 2,
			'transform-rotate-z-m': 3,
			'transform-origin-x-m': 'test',
			'transform-origin-y-m': 'test',
			'transform-scale-x-s': 4,
			'transform-scale-y-s': 1,
			'transform-translate-x-unit-s': 'px',
			'transform-translate-x-s': 2,
			'transform-translate-y-unit-s': 'px',
			'transform-translate-y-s': 3,
			'transform-rotate-x-s': 4,
			'transform-rotate-y-s': 1,
			'transform-rotate-z-s': 2,
			'transform-origin-x-s': 'test',
			'transform-origin-y-s': 'test',
			'transform-scale-x-xs': 4,
			'transform-scale-y-xs': 2,
			'transform-translate-x-unit-xs': 'px',
			'transform-translate-x-xs': 1,
			'transform-translate-y-unit-xs': 'px',
			'transform-translate-y-xs': 2,
			'transform-rotate-x-xs': 3,
			'transform-rotate-y-xs': 4,
			'transform-rotate-z-xs': 1,
			'transform-origin-x-xs': 'test',
			'transform-origin-y-xs': 'test',
		};

		const result = getTransformStyles(object);
		expect(result).toMatchSnapshot();
	});
});
