import getTypographyStyles from '../getTypographyStyles';

jest.mock('@wordpress/data', () => {
	return {
		select: jest.fn(),
	};
});
import { select } from '@wordpress/data';

jest.mock('src/extensions/style-cards/getActiveStyleCard.js', () => {
	return jest.fn(() => {
		return {
			value: {
				name: 'Maxi (Default)',
				status: 'active',
				light: {
					styleCard: {},
					defaultStyleCard: {
						color: {
							1: '255,255,255',
							2: '242,249,253',
							3: '155,155,155',
							4: '255,74,23',
							5: '0,0,0',
							6: '201,52,10',
							7: '8,18,25',
							8: '150,176,203',
						},
					},
				},
			},
		};
	});
});

describe('getTypographyStyles', () => {
	it('Get a correct typography styles', () => {
		const obj = {
			'_ff-general': 'roboto',
			'_cc-general': 'rgb(255, 99, 71)',
			'_fs.u-general': 'px',
			'_fs-general': 1,
			'_lhe.u-general': '-',
			'_lhe-general': 1,
			'_ls.u-general': 'px',
			'_ls-general': 2,
			'_fwe-general': '3',
			'_ttr-general': 'none',
			'_fst-general': 'bold',
			'_td-general': 'underline',
			'_ti-general': 10,
			'_ti.u-general': 'px',
			'_tsh-general': 'none',
			'_va-general': 'none',
			'_ff-xxl': 'roboto',
			'_cc-xxl': 'rgb(255, 99, 71)',
			'_fs.u-xxl': 'px',
			'_fs-xxl': 1,
			'_lhe.u-xxl': 'px',
			'_lhe-xxl': 2,
			'_ls.u-xxl': 'px',
			'_ls-xxl': '3',
			'_fwe-xxl': '4',
			'_ttr-xxl': 'none',
			'_fst-xxl': 'bold',
			'_td-xxl': 'underline',
			'_ti-xxl': 10,
			'_ti.u-xxl': 'px',
			'_tsh-xxl': 'none',
			'_va-xxl': 'none',
			'_ff-xl': 'roboto',
			'_cc-xl': 'rgb(255, 99, 71)',
			'_fs.u-xl': 'px',
			'_fs-xl': 1,
			'_lhe.u-xl': '-',
			'_lhe-xl': 2,
			'_ls.u-xl': 'px',
			'_ls-xl': '3',
			'_fwe-xl': '4',
			'_ttr-xl': 'none',
			'_fst-xl': 'bold',
			'_td-xl': 'underline',
			'_ti-xl': 10,
			'_ti.u-xl': 'px',
			'_tsh-xl': 'none',
			'_va-xl': 'none',
			'_ff-l': 'roboto',
			'_cc-l': 'rgb(255, 99, 71)',
			'_fs.u-l': 'px',
			'_fs-l': 1,
			'_lhe.u-l': 'px',
			'_lhe-l': 2,
			'_ls.u-l': 'px',
			'_ls-l': '3',
			'_fwe-l': '4',
			'_ttr-l': 'none',
			'_fst-l': 'bold',
			'_td-l': 'underline',
			'_ti-l': -20,
			'_ti.u-l': 'px',
			'_tsh-l': 'none',
			'_va-l': 'none',
			'_ff-m': 'roboto',
			'_cc-m': 'rgb(255, 99, 71)',
			'_fs.u-m': 'px',
			'_fs-m': 1,
			'_lhe.u-m': 'px',
			'_lhe-m': 2,
			'_ls.u-m': 'px',
			'_ls-m': '3',
			'_fwe-m': '4',
			'_ttr-m': 'none',
			'_fst-m': 'bold',
			'_td-m': 'underline',
			'_ti-m': 30,
			'_ti.u-m': 'px',
			'_tsh-m': 'none',
			'_va-m': 'none',
			'_ff-s': 'roboto',
			'_cc-s': 'rgb(255, 99, 71)',
			'_fs.u-s': 'px',
			'_fs-s': 1,
			'_lhe.u-s': 'px',
			'_lhe-s': 2,
			'_ls.u-s': 'px',
			'_ls-s': '3',
			'_fwe-s': '4',
			'_ttr-s': 'none',
			'_fst-s': 'bold',
			'_td-s': 'underline',
			'_ti-s': 10,
			'_ti.u-s': 'px',
			'_tsh-s': 'none',
			'_va-s': 'none',
			'_ff-xs': 'roboto',
			'_cc-xs': 'rgb(255, 99, 71)',
			'_fs.u-xs': 'px',
			'_fs-xs': 1,
			'_lhe.u-xs': 'px',
			'_lhe-xs': 2,
			'_ls.u-xs': 'px',
			'_ls-xs': '3',
			'_fwe-xs': '4',
			'_ttr-xs': 'none',
			'_fst-xs': 'bold',
			'_td-xs': 'underline',
			'_ti-xs': 10,
			'_ti.u-xs': 'px',
			'_tsh-xs': 'none',
			'_va-xs': 'none',
			_cf: 'object',
		};

		const result = getTypographyStyles({
			obj,
			blockStyle: 'light',
		});
		expect(result).toMatchSnapshot();
	});

	it('Get a correct typography styles with hover', () => {
		const obj = {
			content: 'Testing',
			textLevel: 'p',
			isList: false,
			typeOfList: 'ul',
			listReversed: 0,
			'_l_ps-general': true,
			'_l_pc-general': '4',
			'_lia_ps-general': true,
			'_lia_pc-general': 6,
			'_liv_ps-general': true,
			'_liv_pc-general': 6,
			'_ps-general': true,
			'_pc-general': '4',
			'_fs.u-general': 'px',
			'_lhe.u-general': 'px',
			'_ls.u-general': 'px',
			'_ff-general': 'roboto',
			'_cc-general': 'rgb(255, 99, 71)',
			'_fs-general': 1,
			'_lhe-general': 1,
			'_ls-general': 2,
			'_fwe-general': '3',
			'_ttr-general': 'none',
			'_fst-general': 'bold',
			'_td-general': 'underline',
			'_ti-general': 10,
			'_ti.u-general': 'px',
			'_tsh-general': 'none',
			'_va-general': 'none',
			'_ff-xxl': 'roboto',
			'_cc-xxl': 'rgb(255, 99, 71)',
			'_fs.u-xxl': 'px',
			'_fs-xxl': 1,
			'_lhe.u-xxl': 'px',
			'_lhe-xxl': 2,
			'_ls.u-xxl': 'px',
			'_ls-xxl': '3',
			'_fwe-xxl': '4',
			'_ttr-xxl': 'none',
			'_fst-xxl': 'bold',
			'_td-xxl': 'underline',
			'_ti-xxl': 10,
			'_ti.u-xxl': 'px',
			'_tsh-xxl': 'none',
			'_va-xxl': 'none',
			'_ff-xl': 'roboto',
			'_cc-xl': 'rgb(255, 99, 71)',
			'_fs.u-xl': 'px',
			'_fs-xl': 29,
			'_lhe.u-xl': 'px',
			'_lhe-xl': 10,
			'_ls.u-xl': 'px',
			'_ls-xl': '3',
			'_fwe-xl': '4',
			'_ttr-xl': 'none',
			'_fst-xl': 'bold',
			'_td-xl': 'underline',
			'_ti-xl': 10,
			'_ti.u-xl': 'px',
			'_tsh-xl': 'none',
			'_va-xl': 'none',
			'_ff-l': 'roboto',
			'_cc-l': 'rgb(255, 99, 71)',
			'_fs.u-l': 'px',
			'_fs-l': 1,
			'_lhe.u-l': 'px',
			'_lhe-l': 2,
			'_ls.u-l': 'px',
			'_ls-l': '3',
			'_fwe-l': '4',
			'_ttr-l': 'none',
			'_fst-l': 'bold',
			'_td-l': 'underline',
			'_ti-l': 10,
			'_ti.u-l': 'px',
			'_tsh-l': 'none',
			'_va-l': 'none',
			'_ff-m': 'roboto',
			'_cc-m': 'rgb(255, 99, 71)',
			'_fs.u-m': 'px',
			'_fs-m': 1,
			'_lhe.u-m': 'px',
			'_lhe-m': 2,
			'_ls.u-m': 'px',
			'_ls-m': '3',
			'_fwe-m': '4',
			'_ttr-m': 'none',
			'_fst-m': 'bold',
			'_td-m': 'underline',
			'_ti-m': 10,
			'_ti.u-m': 'px',
			'_tsh-m': 'none',
			'_va-m': 'none',
			'_ff-s': 'roboto',
			'_cc-s': 'rgb(255, 99, 71)',
			'_fs.u-s': 'px',
			'_fs-s': 1,
			'_lhe.u-s': 'px',
			'_lhe-s': 2,
			'_ls.u-s': 'px',
			'_ls-s': '3',
			'_fwe-s': '4',
			'_ttr-s': 'none',
			'_fst-s': 'bold',
			'_td-s': 'underline',
			'_ti-s': 10,
			'_ti.u-s': 'px',
			'_tsh-s': 'none',
			'_va-s': 'none',
			'_ff-xs': 'roboto',
			'_cc-xs': 'rgb(255, 99, 71)',
			'_fs.u-xs': 'px',
			'_fs-xs': 1,
			'_lhe.u-xs': 'px',
			'_lhe-xs': 2,
			'_ls.u-xs': 'px',
			'_ls-xs': '3',
			'_fwe-xs': '4',
			'_ttr-xs': 'none',
			'_fst-xs': 'bold',
			'_td-xs': 'underline',
			'_ti-xs': 10,
			'_ti.u-xs': 'px',
			'_tsh-xs': 'none',
			'_va-xs': 'none',
			_cf: 'object',
			'_po-general': 1,
			'_lih_ps-general': true,
			'_lih_pc-general': 6,
			'_lih_pc-l': '3',
		};
		const hoverObj = {
			't.sh': true,
			'_ps-general.h': true,
			'_pc-general.h': '3',
			'_pc-l.h': 6,
			'_po-general.h': 1,
			'_po-l.h': 10,
			'_cc-general.h': 'rgb(255, 99, 71)',
			'_fs-xl.h': 22,
			'_fs-l.h': 10,
			'_lhe-xl.h': '4',
			'_lhe-l.h': 40,
			'_ls-xl.h': 24.2,
			'_ls-l.h': 2,
			'_fwe-general.h': '500',
			'_fwe-l.h': '200',
			'_ttr-general.h': 'uppercase',
			'_ttr-l.h': 'lowercase',
			'_fst-general.h': 'italic',
			'_fst-l.h': 'oblique',
			'_td-general.h': 'overline',
			'_ti-general': 10,
			'_ti.u-general': 'px',
			'_td-l.h': 'underline',
			'_ti-l': 10,
			'_ti.u-l': 'px',
		};

		const result = getTypographyStyles({
			obj: hoverObj,
			blockStyle: 'light',
			isHover: true,
			normalTypography: obj,
		});
		expect(result).toMatchSnapshot();
	});

	it('Get a correct typography styles when there is a unit value set for XXL and general has no value (it has unit)', () => {
		select.mockImplementation(
			jest.fn(() => {
				return {
					receiveMaxiDeviceType: jest.fn(() => 'xl'),
					receiveBaseBreakpoint: jest.fn(() => 'xxl'),
					getSelectedBlockCount: jest.fn(() => 1),
				};
			})
		);
		const obj = {
			'_ps-general': true,
			'_pc-general': 5,
			'_l_ps-general': true,
			'_l_pc-general': 4,
			'_fs.u-general': 'px',
			'_fs.u-xxl': 'em',
			'_fs.u-m': 'px',
			'_fs-general': 90,
			'_fs-xxl': 6.12,
			'_fs-m': 60,
			'_fs-s': 36,
			'_lhe.u-general': 'px',
			'_lhe.u-xxl': 'em',
			'_lhe.u-m': 'px',
			'_lhe-general': 99,
			'_lhe-xxl': 1.19,
			'_lhe-m': 70,
			'_lhe-s': 48,
		};

		const result = getTypographyStyles({
			obj,
			blockStyle: 'light',
		});
		expect(result).toMatchSnapshot();
	});
});
