const path = '../wp-content/plugins/maxi-blocks/src/icons/shape-icons/';

const SVGDefaults = [
    `${path}shape1.svg`,
    `${path}shape2.svg`,
    `${path}shape3.svg`,
    `${path}shape4.svg`,
    `${path}shape5.svg`,
    `${path}shape6.svg`,
    `${path}shape7.svg`,
    `${path}shape8.svg`,
    `${path}shape9.svg`,
    `${path}shape10.svg`,
    `${path}shape11.svg`,
    `${path}shape12.svg`,
    `${path}shape13.svg`,
    `${path}shape14.svg`,
    `${path}shape15.svg`,
    `${path}shape16.svg`,
    `${path}shape17.svg`,
    `${path}shape18.svg`,
    `${path}shape19.svg`,
    `${path}shape20.svg`,
    `${path}shape21.svg`,
    `${path}shape22.svg`,
    `${path}shape23.svg`,
    `${path}shape24.svg`,
    // `${path}shape25.svg`,
    `${path}shape26.svg`,
    `${path}shape27.svg`,
    `${path}shape28.svg`,
    `${path}shape29.svg`,
    `${path}shape30.svg`,
    `${path}shape31.svg`,
    `${path}shape32.svg`,
    `${path}shape33.svg`,
];

export default SVGDefaults;