const size = {
	label: 'Size',
	general: {
		'max-widthUnit': 'px',
		'max-width': '',
		widthUnit: '%',
		width: 100,
		'min-widthUnit': 'px',
		'min-width': '',
		'max-heightUnit': 'px',
		'max-height': '',
		heightUnit: 'px',
		height: '',
		'min-heightUnit': 'px',
		'min-height': '',
		advancedOptions: 0,
	},
	xxl: {
		'max-widthUnit': 'px',
		'max-width': '',
		widthUnit: 'px',
		width: '',
		'min-widthUnit': 'px',
		'min-width': '',
		'max-heightUnit': 'px',
		'max-height': '',
		heightUnit: 'px',
		height: '',
		'min-heightUnit': 'px',
		'min-height': '',
		advancedOptions: 0,
	},
	xl: {
		'max-widthUnit': 'px',
		'max-width': '',
		widthUnit: 'px',
		width: '',
		'min-widthUnit': 'px',
		'min-width': '',
		'max-heightUnit': 'px',
		'max-height': '',
		heightUnit: 'px',
		height: '',
		'min-heightUnit': 'px',
		'min-height': '',
		advancedOptions: 0,
	},
	l: {
		'max-widthUnit': 'px',
		'max-width': '',
		widthUnit: 'px',
		width: '',
		'min-widthUnit': 'px',
		'min-width': '',
		'max-heightUnit': 'px',
		'max-height': '',
		heightUnit: 'px',
		height: '',
		'min-heightUnit': 'px',
		'min-height': '',
		advancedOptions: 0,
	},
	m: {
		'max-widthUnit': 'px',
		'max-width': '',
		widthUnit: 'px',
		width: '',
		'min-widthUnit': 'px',
		'min-width': '',
		'max-heightUnit': 'px',
		'max-height': '',
		heightUnit: 'px',
		height: '',
		'min-heightUnit': 'px',
		'min-height': '',
		advancedOptions: 0,
	},
	s: {
		'max-widthUnit': 'px',
		'max-width': '',
		widthUnit: 'px',
		width: '',
		'min-widthUnit': 'px',
		'min-width': '',
		'max-heightUnit': 'px',
		'max-height': '',
		heightUnit: 'px',
		height: '',
		'min-heightUnit': 'px',
		'min-height': '',
		advancedOptions: 0,
	},
	xs: {
		'max-widthUnit': 'px',
		'max-width': '',
		widthUnit: 'px',
		width: '',
		'min-widthUnit': 'px',
		'min-width': '',
		'max-heightUnit': 'px',
		'max-height': '',
		heightUnit: 'px',
		height: '',
		'min-heightUnit': 'px',
		'min-height': '',
		advancedOptions: 0,
	},
};

export default size;
