/**
 * WordPress dependencies
 */
import {
	createNewPost,
	insertBlock,
	// pressKeyTimes,
} from '@wordpress/e2e-test-utils';
// import openSidebar from '../../utils/openSidebar';
import { getBlockAttributes } from '../../utils';

describe('default styles control', () => {
	beforeEach(async () => {
		await createNewPost();
	});
	it('checking the default styles control', async () => {
		await insertBlock('Text Maxi');
		await page.keyboard.type('check default styles');

		const expectAttributes = {
			'background-gradient-opacity': 1,
			'background-highlight': false,
			'background-image-attachment': 'scroll',
			'background-image-clip': 'border-box',
			'background-image-height': 100,
			'background-image-height-unit': '%',
			'background-image-opacity': 1,
			'background-image-origin': 'padding-box',
			'background-image-position': 'center center',
			'background-image-position-height': 0,
			'background-image-position-height-unit': '%',
			'background-image-position-width': 0,
			'background-image-position-width-unit': '%',
			'background-image-repeat': 'no-repeat',
			'background-image-size': 'auto',
			'background-image-width': 100,
			'background-image-width-unit': '%',
			'background-layers-status': false,
			'background-layers-status-hover': false,
			'background-status-hover': false,
			'background-svg-left': 0,
			'background-svg-left--unit': '%',
			'background-svg-size': 100,
			'background-svg-size--unit': '%',
			'background-svg-top': 0,
			'background-svg-top--unit': '%',
			'background-video-loop': false,
			'background-video-opacity': 100,
			'background-video-playOnMobile': false,
			blockStyle: 'maxi-light',
			blockStyleBackground: 1,
			'border-highlight': false,
			'border-status-hover': false,
			'border-sync-radius-general': true,
			'border-sync-width-general': true,
			'border-unit-radius-general': 'px',
			'border-unit-radius-general-hover': 'px',
			'border-unit-width-general': 'px',
			'box-shadow-color-general': 'rgb(236, 241, 246)',
			'box-shadow-color-general-hover': '',
			'box-shadow-status-hover': false,
			'color1-highlight': false,
			'color2-highlight': false,
			'container-height-unit-general': 'px',
			'container-height-unit-l': 'px',
			'container-height-unit-m': 'px',
			'container-height-unit-s': 'px',
			'container-height-unit-xl': 'px',
			'container-height-unit-xs': 'px',
			'container-height-unit-xxl': 'px',
			'container-max-height-unit-general': 'px',
			'container-max-height-unit-l': 'px',
			'container-max-height-unit-m': 'px',
			'container-max-height-unit-s': 'px',
			'container-max-height-unit-xl': 'px',
			'container-max-height-unit-xs': 'px',
			'container-max-height-unit-xxl': 'px',
			'container-max-width-general': 1170,
			'container-max-width-l': 90,
			'container-max-width-m': 90,
			'container-max-width-s': 90,
			'container-max-width-unit-general': 'px',
			'container-max-width-unit-l': '%',
			'container-max-width-unit-m': '%',
			'container-max-width-unit-s': '%',
			'container-max-width-unit-xl': 'px',
			'container-max-width-unit-xs': '%',
			'container-max-width-unit-xxl': 'px',
			'container-max-width-xl': 1170,
			'container-max-width-xs': 90,
			'container-max-width-xxl': 1790,
			'container-min-height-unit-general': 'px',
			'container-min-height-unit-l': 'px',
			'container-min-height-unit-m': 'px',
			'container-min-height-unit-s': 'px',
			'container-min-height-unit-xl': 'px',
			'container-min-height-unit-xs': 'px',
			'container-min-height-unit-xxl': 'px',
			'container-min-width-unit-general': 'px',
			'container-min-width-unit-l': 'px',
			'container-min-width-unit-m': 'px',
			'container-min-width-unit-s': 'px',
			'container-min-width-unit-xl': 'px',
			'container-min-width-unit-xs': 'px',
			'container-min-width-unit-xxl': 'px',
			'container-size-advanced-options': false,
			'container-width-l': 1170,
			'container-width-m': 1000,
			'container-width-s': 700,
			'container-width-unit-l': 'px',
			'container-width-unit-m': 'px',
			'container-width-unit-s': 'px',
			'container-width-unit-xs': 'px',
			'container-width-xs': 460,
			content: 'check default styles',
			customLabel: 'Text',
			defaultBlockStyle: 'maxi-def-light',
			'entrance-delay': 1,
			'entrance-duration': 1,
			'entrance-type': 'none',
			extraClassName: '',
			'font-family-general': 'Roboto',
			'font-size-general': 16,
			'font-size-unit-general': 'px',
			'font-size-unit-l': 'px',
			'font-size-unit-m': 'px',
			'font-size-unit-s': 'px',
			'font-size-unit-xl': 'px',
			'font-size-unit-xs': 'px',
			'font-size-unit-xxl': 'px',
			fullWidth: 'normal',
			'height-unit-general': 'px',
			isFirstOnHierarchy: true,
			isList: false,
			'letter-spacing-general': 0,
			'letter-spacing-unit-general': 'px',
			'letter-spacing-unit-l': 'px',
			'letter-spacing-unit-m': 'px',
			'letter-spacing-unit-s': 'px',
			'letter-spacing-unit-xl': 'px',
			'letter-spacing-unit-xs': 'px',
			'letter-spacing-unit-xxl': 'px',
			'line-height-general': 1.625,
			listReversed: 0,
			listStart: 1,
			'margin-sync-general': false,
			'margin-unit-general': 'px',
			'max-height-unit-general': 'px',
			'max-width-unit-general': 'px',
			'min-height-unit-general': 'px',
			'min-width-unit-general': 'px',
			'motion-active-time-line-index': 0,
			'motion-active-time-line-time': 0,
			'motion-mobile-status': true,
			'motion-preset-status': false,
			'motion-preview-status': false,
			'motion-status': false,
			'motion-tablet-status': true,
			'motion-transform-origin-x': 'center',
			'motion-transform-origin-y': 'center',
			'padding-sync-general': false,
			'padding-unit-general': 'px',
			'parallax-direction': 'up',
			'parallax-speed': 4,
			'parallax-status': false,
			'position-sync-general': false,
			'position-unit-general': 'px',
			'size-advanced-options': false,
			'text-highlight': false,
			textLevel: 'p',
			'transform-translate-x-unit-general': '%',
			'transform-translate-x-unit-l': '%',
			'transform-translate-x-unit-m': '%',
			'transform-translate-x-unit-s': '%',
			'transform-translate-x-unit-xl': '%',
			'transform-translate-x-unit-xs': '%',
			'transform-translate-x-unit-xxl': '%',
			'transform-translate-y-unit-general': '%',
			'transform-translate-y-unit-l': '%',
			'transform-translate-y-unit-m': '%',
			'transform-translate-y-unit-s': '%',
			'transform-translate-y-unit-xl': '%',
			'transform-translate-y-unit-xs': '%',
			'transform-translate-y-unit-xxl': '%',
			uniqueID: 'text-maxi-12',
			typeOfList: 'ul',
			'typography-status-hover': false,
			'width-unit-general': 'px',
		};
		const attributes = await getBlockAttributes();

		expect(attributes).toStrictEqual(expectAttributes);
	});
});
