/**
 * Internal dependencies
 */
import '@wordpress/block-editor';
import { onSplit } from '../utils';
import '../text-maxi';

describe('onSplit', () => {
	it('onSplit: simple simple with no formats', () => {
		const attributes = {
			uniqueID: 'text-maxi-255',
			content: 'Quiero juntar esta frase......con esta!',
		};
		const value = 'Quiero juntar esta frase...';

		const result = onSplit(attributes, value);
		delete result.clientId;

		const expectedResult = {
			name: 'maxi-blocks/text-maxi',
			isValid: true,
			attributes: {
				customLabel: 'Text',
				textLevel: 'p',
				isList: false,
				typeOfList: 'ul',
				listStart: 1,
				listReversed: 0,
				fullWidth: 'normal',
				content: 'Quiero juntar esta frase...',
				'background-highlight': false,
				'text-highlight': false,
				'border-highlight': false,
				'color1-highlight': false,
				'color2-highlight': false,
				'background-layers-status': false,
				'background-gradient-opacity': 1,
				'background-layers-status-hover': false,
				'background-status-hover': false,
				'background-image-size': 'auto',
				'background-image-width': 100,
				'background-image-width-unit': '%',
				'background-image-height': 100,
				'background-image-height-unit': '%',
				'background-image-repeat': 'no-repeat',
				'background-image-position': 'center center',
				'background-image-position-width-unit': '%',
				'background-image-position-width': 0,
				'background-image-position-height-unit': '%',
				'background-image-position-height': 0,
				'background-image-origin': 'padding-box',
				'background-image-clip': 'border-box',
				'background-image-attachment': 'scroll',
				'background-image-opacity': 1,
				'background-svg-top--unit': '%',
				'background-svg-top': 0,
				'background-svg-left--unit': '%',
				'background-svg-left': 0,
				'background-svg-size': 100,
				'background-svg-size--unit': '%',
				'background-video-loop': false,
				'background-video-playOnMobile': false,
				'background-video-opacity': 100,
				'border-status-hover': false,
				'border-sync-radius-general': true,
				'border-unit-radius-general': 'px',
				'border-unit-radius-general-hover': 'px',
				'border-sync-width-general': true,
				'border-unit-width-general': 'px',
				'box-shadow-color-general': 'rgb(236, 241, 246)',
				'box-shadow-status-hover': false,
				'box-shadow-color-general-hover': '',
				'container-min-width-unit-general': 'px',
				'container-max-height-unit-general': 'px',
				'container-height-unit-general': 'px',
				'container-min-height-unit-general': 'px',
				'container-min-width-unit-xxl': 'px',
				'container-max-height-unit-xxl': 'px',
				'container-height-unit-xxl': 'px',
				'container-min-height-unit-xxl': 'px',
				'container-min-width-unit-xl': 'px',
				'container-max-height-unit-xl': 'px',
				'container-height-unit-xl': 'px',
				'container-min-height-unit-xl': 'px',
				'container-min-width-unit-l': 'px',
				'container-max-height-unit-l': 'px',
				'container-height-unit-l': 'px',
				'container-min-height-unit-l': 'px',
				'container-min-width-unit-m': 'px',
				'container-max-height-unit-m': 'px',
				'container-height-unit-m': 'px',
				'container-min-height-unit-m': 'px',
				'container-min-width-unit-s': 'px',
				'container-max-height-unit-s': 'px',
				'container-height-unit-s': 'px',
				'container-min-height-unit-s': 'px',
				'container-min-width-unit-xs': 'px',
				'container-max-height-unit-xs': 'px',
				'container-height-unit-xs': 'px',
				'container-min-height-unit-xs': 'px',
				'container-size-advanced-options': false,
				'container-max-width-general': 1170,
				'container-max-width-xxl': 1790,
				'container-max-width-xl': 1170,
				'container-max-width-l': 90,
				'container-max-width-m': 90,
				'container-max-width-s': 90,
				'container-max-width-xs': 90,
				'container-max-width-unit-general': 'px',
				'container-max-width-unit-xxl': 'px',
				'container-max-width-unit-xl': 'px',
				'container-max-width-unit-l': '%',
				'container-max-width-unit-m': '%',
				'container-max-width-unit-s': '%',
				'container-max-width-unit-xs': '%',
				'container-width-l': 1170,
				'container-width-unit-l': 'px',
				'container-width-m': 1000,
				'container-width-unit-m': 'px',
				'container-width-s': 700,
				'container-width-unit-s': 'px',
				'container-width-xs': 460,
				'container-width-unit-xs': 'px',
				'entrance-type': 'none',
				'entrance-duration': 1,
				'entrance-delay': 1,
				'margin-sync-general': false,
				'margin-unit-general': 'px',
				'motion-status': false,
				'motion-active-time-line-time': 0,
				'motion-active-time-line-index': 0,
				'motion-transform-origin-x': 'center',
				'motion-transform-origin-y': 'center',
				'motion-preset-status': false,
				'motion-preview-status': false,
				'motion-tablet-status': true,
				'motion-mobile-status': true,
				'padding-sync-general': false,
				'padding-unit-general': 'px',
				'parallax-status': false,
				'parallax-speed': 2,
				'parallax-direction': 'up',
				'position-sync-general': false,
				'position-unit-general': 'px',
				'size-advanced-options': false,
				'max-width-unit-general': 'px',
				'width-unit-general': 'px',
				'min-width-unit-general': 'px',
				'max-height-unit-general': 'px',
				'height-unit-general': 'px',
				'min-height-unit-general': 'px',
				'transform-translate-x-unit-general': '%',
				'transform-translate-y-unit-general': '%',
				'transform-translate-x-unit-xxl': '%',
				'transform-translate-y-unit-xxl': '%',
				'transform-translate-x-unit-xl': '%',
				'transform-translate-y-unit-xl': '%',
				'transform-translate-x-unit-l': '%',
				'transform-translate-y-unit-l': '%',
				'transform-translate-x-unit-m': '%',
				'transform-translate-y-unit-m': '%',
				'transform-translate-x-unit-s': '%',
				'transform-translate-y-unit-s': '%',
				'transform-translate-x-unit-xs': '%',
				'transform-translate-y-unit-xs': '%',
				'font-family-general': 'Roboto',
				'font-size-unit-general': 'px',
				'font-size-general': 16,
				'line-height-general': 1.625,
				'letter-spacing-unit-general': 'px',
				'letter-spacing-general': 0,
				'font-size-unit-xxl': 'px',
				'letter-spacing-unit-xxl': 'px',
				'font-size-unit-xl': 'px',
				'letter-spacing-unit-xl': 'px',
				'font-size-unit-l': 'px',
				'letter-spacing-unit-l': 'px',
				'font-size-unit-m': 'px',
				'letter-spacing-unit-m': 'px',
				'font-size-unit-s': 'px',
				'letter-spacing-unit-s': 'px',
				'font-size-unit-xs': 'px',
				'letter-spacing-unit-xs': 'px',
				'typography-status-hover': false,
			},
			innerBlocks: [],
		};

		expect(result).toStrictEqual(expectedResult);
	});
	/**
	 * Missing tests:
	 * - onReplace
	 * - onMerge
	 */
});
