const DefaultTypography = {
    p: {
        color: '#9b9b9b',
        font: 'Roboto',
        sizeUnit: 'px',
        size: 16,
        fontWeight: 400,
        lineHeightUnit: 'px',
        lineHeight: 26,
        letterSpacingUnit: 'px',
        letterSpacing: 0,
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        decorationLine: 'none'
    },
    link: {
        color: '#00ccff',
        font: 'Roboto',
        sizeUnit: 'px',
        size: 16,
        fontWeight: 400,
        lineHeightUnit: 'px',
        lineHeight: 26,
        letterSpacingUnit: 'px',
        letterSpacing: 0,
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        decorationLine: 'none'
    },
    h1: {
        color: '#000000',
        font: 'Roboto',
        sizeUnit: 'px',
        size: 45,
        fontWeight: 400,
        lineHeightUnit: 'px',
        lineHeight: 55,
        letterSpacingUnit: 'px',
        letterSpacing: 0,
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        decorationLine: 'none'
    },
    h2: {
        color: '#000000',
        font: 'Roboto',
        sizeUnit: 'px',
        size: 38,
        fontWeight: 400,
        lineHeightUnit: 'px',
        lineHeight: 48,
        letterSpacingUnit: 'px',
        letterSpacing: 0,
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        decorationLine: 'none'
    },
    h3: {
        color: '#000000',
        font: 'Roboto',
        sizeUnit: 'px',
        size: 30,
        fontWeight: 400,
        lineHeightUnit: 'px',
        lineHeight: 40,
        letterSpacingUnit: 'px',
        letterSpacing: 0,
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        decorationLine: 'none'
    },
    h4: {
        color: '#000000',
        font: 'Roboto',
        sizeUnit: 'px',
        size: 26,
        fontWeight: 400,
        lineHeightUnit: 'px',
        lineHeight: 36,
        letterSpacingUnit: 'px',
        letterSpacing: 0,
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        decorationLine: 'none'
    },
    h5: {
        color: '#000000',
        font: 'Roboto',
        sizeUnit: 'px',
        size: 22,
        fontWeight: 400,
        lineHeightUnit: 'px',
        lineHeight: 32,
        letterSpacingUnit: 'px',
        letterSpacing: 0,
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        decorationLine: 'none'
    },
    h6: {
        color: '#000000',
        font: 'Roboto',
        sizeUnit: 'px',
        size: 20,
        fontWeight: 400,
        lineHeightUnit: 'px',
        lineHeight: 30,
        letterSpacingUnit: 'px',
        letterSpacing: 0,
        textTransform: 'none',
        fontStyle: 'normal',
        textDecoration: 'none',
        decorationLine: 'none'
    }
}

export default DefaultTypography;