const DefaultTypography = {
	p: {
		label: 'Typography',
		general: {
			'font-family': 'Roboto',
			'font-options': {
				100: 'http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1MmgWxPKTM1K9nz.ttf',
				'100italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOiCnqEu92Fr1Mu51QrIzcXLsnzjYk.ttf',
				300: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmSU5vAx05IsDqlA.ttf',
				'300italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TjARc9AMX6lJBP.ttf',
				400: 'http://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf',
				italic:
					'http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1Mu52xPKTM1K9nz.ttf',
				500: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmEU9vAx05IsDqlA.ttf',
				'500italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51S7ABc9AMX6lJBP.ttf',
				700: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlvAx05IsDqlA.ttf',
				'700italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TzBhc9AMX6lJBP.ttf',
				900: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmYUtvAx05IsDqlA.ttf',
				'900italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TLBBc9AMX6lJBP.ttf',
			},
			color: '#9b9b9b',
			'text-align': 'left',
			'font-sizeUnit': 'px',
			'font-size': 16,
			'line-heightUnit': '%',
			'line-height': 156,
			'letter-spacingUnit': 'px',
			'letter-spacing': 0,
			'font-weight': 400,
			'text-transform': 'none',
			'font-style': 'normal',
			'text-decoration': 'none',
			'text-shadow': '',
		},
		xxl: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': 24,
			'line-heightUnit': '%',
			'line-height': 142,
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		xl: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': '',
			'line-heightUnit': '%',
			'line-height': '',
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		l: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': '',
			'line-heightUnit': '%',
			'line-height': '',
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		m: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': '',
			'line-heightUnit': '%',
			'line-height': '',
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		s: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': '',
			'line-heightUnit': '%',
			'line-height': '',
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		xs: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': '',
			'line-heightUnit': '%',
			'line-height': '',
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
	},
	link: {
		label: 'Typography',
		general: {
			'font-family': 'Roboto',
			'font-options': {
				100: 'http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1MmgWxPKTM1K9nz.ttf',
				'100italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOiCnqEu92Fr1Mu51QrIzcXLsnzjYk.ttf',
				300: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmSU5vAx05IsDqlA.ttf',
				'300italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TjARc9AMX6lJBP.ttf',
				400: 'http://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf',
				italic:
					'http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1Mu52xPKTM1K9nz.ttf',
				500: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmEU9vAx05IsDqlA.ttf',
				'500italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51S7ABc9AMX6lJBP.ttf',
				700: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlvAx05IsDqlA.ttf',
				'700italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TzBhc9AMX6lJBP.ttf',
				900: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmYUtvAx05IsDqlA.ttf',
				'900italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TLBBc9AMX6lJBP.ttf',
			},
			color: '#9b9b9b',
			'text-align': 'left',
			'font-sizeUnit': 'px',
			'font-size': 16,
			'line-heightUnit': '%',
			'line-height': 156,
			'letter-spacingUnit': 'px',
			'letter-spacing': 0,
			'font-weight': 400,
			'text-transform': 'none',
			'font-style': 'normal',
			'text-decoration': 'underline',
			'text-shadow': '',
		},
		xxl: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': 24,
			'line-heightUnit': '%',
			'line-height': 142,
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		xl: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': 16,
			'line-heightUnit': '%',
			'line-height': 156,
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		l: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': '',
			'line-heightUnit': '%',
			'line-height': '',
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		m: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': '',
			'line-heightUnit': '%',
			'line-height': '',
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		s: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': '',
			'line-heightUnit': '%',
			'line-height': '',
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		xs: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': '',
			'line-heightUnit': '%',
			'line-height': '',
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
	},
	h1: {
		label: 'Typography',
		general: {
			'font-family': 'Roboto',
			'font-options': {
				100: 'http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1MmgWxPKTM1K9nz.ttf',
				'100italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOiCnqEu92Fr1Mu51QrIzcXLsnzjYk.ttf',
				300: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmSU5vAx05IsDqlA.ttf',
				'300italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TjARc9AMX6lJBP.ttf',
				400: 'http://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf',
				italic:
					'http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1Mu52xPKTM1K9nz.ttf',
				500: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmEU9vAx05IsDqlA.ttf',
				'500italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51S7ABc9AMX6lJBP.ttf',
				700: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlvAx05IsDqlA.ttf',
				'700italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TzBhc9AMX6lJBP.ttf',
				900: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmYUtvAx05IsDqlA.ttf',
				'900italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TLBBc9AMX6lJBP.ttf',
			},
			color: '#9b9b9b',
			'text-align': 'left',
			'font-sizeUnit': 'px',
			'font-size': 35,
			'line-heightUnit': '%',
			'line-height': 129,
			'letter-spacingUnit': 'px',
			'letter-spacing': 0,
			'font-weight': 400,
			'text-transform': 'none',
			'font-style': 'normal',
			'text-decoration': 'none',
			'text-shadow': '',
		},
		xl: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': 55,
			'line-heightUnit': '%',
			'line-height': 118,
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		xxl: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': 55,
			'line-heightUnit': '%',
			'line-height': 118,
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		l: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': 45,
			'line-heightUnit': '%',
			'line-height': 122,
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		m: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': 35,
			'line-heightUnit': '%',
			'line-height': 129,
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		s: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': 35,
			'line-heightUnit': '%',
			'line-height': 129,
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		xs: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': 35,
			'line-heightUnit': '%',
			'line-height': 129,
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
	},
	h2: {
		label: 'Typography',
		general: {
			'font-family': 'Roboto',
			'font-options': {
				100: 'http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1MmgWxPKTM1K9nz.ttf',
				'100italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOiCnqEu92Fr1Mu51QrIzcXLsnzjYk.ttf',
				300: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmSU5vAx05IsDqlA.ttf',
				'300italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TjARc9AMX6lJBP.ttf',
				400: 'http://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf',
				italic:
					'http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1Mu52xPKTM1K9nz.ttf',
				500: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmEU9vAx05IsDqlA.ttf',
				'500italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51S7ABc9AMX6lJBP.ttf',
				700: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlvAx05IsDqlA.ttf',
				'700italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TzBhc9AMX6lJBP.ttf',
				900: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmYUtvAx05IsDqlA.ttf',
				'900italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TLBBc9AMX6lJBP.ttf',
			},
			color: '#9b9b9b',
			'text-align': 'left',
			'font-sizeUnit': 'px',
			'font-size': 38,
			'line-heightUnit': '%',
			'line-height': 126,
			'letter-spacingUnit': 'px',
			'letter-spacing': 0,
			'font-weight': 400,
			'text-transform': 'none',
			'font-style': 'normal',
			'text-decoration': 'none',
			'text-shadow': '',
		},
		xxl: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': 48,
			'line-heightUnit': '%',
			'line-height': 121,
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		xl: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': 48,
			'line-heightUnit': '%',
			'line-height': 121,
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		l: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': 38,
			'line-heightUnit': '%',
			'line-height': 126,
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		m: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': 30,
			'line-heightUnit': '%',
			'line-height': 133,
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		s: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': '',
			'line-heightUnit': '%',
			'line-height': '',
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		xs: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': '',
			'line-heightUnit': '%',
			'line-height': '',
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
	},
	h3: {
		label: 'Typography',
		general: {
			'font-family': 'Roboto',
			'font-options': {
				100: 'http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1MmgWxPKTM1K9nz.ttf',
				'100italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOiCnqEu92Fr1Mu51QrIzcXLsnzjYk.ttf',
				300: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmSU5vAx05IsDqlA.ttf',
				'300italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TjARc9AMX6lJBP.ttf',
				400: 'http://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf',
				italic:
					'http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1Mu52xPKTM1K9nz.ttf',
				500: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmEU9vAx05IsDqlA.ttf',
				'500italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51S7ABc9AMX6lJBP.ttf',
				700: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlvAx05IsDqlA.ttf',
				'700italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TzBhc9AMX6lJBP.ttf',
				900: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmYUtvAx05IsDqlA.ttf',
				'900italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TLBBc9AMX6lJBP.ttf',
			},
			color: '#9b9b9b',
			'text-align': 'left',
			'font-sizeUnit': 'px',
			'font-size': 30,
			'line-heightUnit': '%',
			'line-height': 133,
			'letter-spacingUnit': 'px',
			'letter-spacing': 0,
			'font-weight': 400,
			'text-transform': 'none',
			'font-style': 'normal',
			'text-decoration': 'none',
			'text-shadow': '',
		},
		xxl: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': 40,
			'line-heightUnit': '%',
			'line-height': 125,
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		xl: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': 40,
			'line-heightUnit': '%',
			'line-height': 125,
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		l: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': 30,
			'line-heightUnit': '%',
			'line-height': 133,
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		m: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': 28,
			'line-heightUnit': '%',
			'line-height': 136,
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		s: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': '',
			'line-heightUnit': '%',
			'line-height': '',
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		xs: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': 22,
			'line-heightUnit': '%',
			'line-height': 32,
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
	},
	h4: {
		label: 'Typography',
		general: {
			'font-family': 'Roboto',
			'font-options': {
				100: 'http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1MmgWxPKTM1K9nz.ttf',
				'100italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOiCnqEu92Fr1Mu51QrIzcXLsnzjYk.ttf',
				300: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmSU5vAx05IsDqlA.ttf',
				'300italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TjARc9AMX6lJBP.ttf',
				400: 'http://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf',
				italic:
					'http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1Mu52xPKTM1K9nz.ttf',
				500: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmEU9vAx05IsDqlA.ttf',
				'500italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51S7ABc9AMX6lJBP.ttf',
				700: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlvAx05IsDqlA.ttf',
				'700italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TzBhc9AMX6lJBP.ttf',
				900: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmYUtvAx05IsDqlA.ttf',
				'900italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TLBBc9AMX6lJBP.ttf',
			},
			color: '#9b9b9b',
			'text-align': 'left',
			'font-sizeUnit': 'px',
			'font-size': 26,
			'line-heightUnit': '%',
			'line-height': 139,
			'letter-spacingUnit': 'px',
			'letter-spacing': 0,
			'font-weight': 400,
			'text-transform': 'none',
			'font-style': 'normal',
			'text-decoration': 'none',
			'text-shadow': '',
		},
		xxl: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': 30,
			'line-heightUnit': '%',
			'line-height': 133,
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		xl: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': 30,
			'line-heightUnit': '%',
			'line-height': 133,
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		l: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': 26,
			'line-heightUnit': '%',
			'line-height': 139,
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		m: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': 24,
			'line-heightUnit': '%',
			'line-height': 142,
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		s: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': '',
			'line-heightUnit': '%',
			'line-height': '',
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		xs: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': 20,
			'line-heightUnit': '%',
			'line-height': 30,
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
	},
	h5: {
		label: 'Typography',
		general: {
			'font-family': 'Roboto',
			'font-options': {
				100: 'http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1MmgWxPKTM1K9nz.ttf',
				'100italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOiCnqEu92Fr1Mu51QrIzcXLsnzjYk.ttf',
				300: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmSU5vAx05IsDqlA.ttf',
				'300italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TjARc9AMX6lJBP.ttf',
				400: 'http://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf',
				italic:
					'http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1Mu52xPKTM1K9nz.ttf',
				500: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmEU9vAx05IsDqlA.ttf',
				'500italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51S7ABc9AMX6lJBP.ttf',
				700: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlvAx05IsDqlA.ttf',
				'700italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TzBhc9AMX6lJBP.ttf',
				900: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmYUtvAx05IsDqlA.ttf',
				'900italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TLBBc9AMX6lJBP.ttf',
			},
			color: '#9b9b9b',
			'text-align': 'left',
			'font-sizeUnit': 'px',
			'font-size': 22,
			'line-heightUnit': '%',
			'line-height': 145,
			'letter-spacingUnit': 'px',
			'letter-spacing': 0,
			'font-weight': 400,
			'text-transform': 'none',
			'font-style': 'normal',
			'text-decoration': 'none',
			'text-shadow': '',
		},
		xxl: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': 28,
			'line-heightUnit': '%',
			'line-height': 136,
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		xl: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': 28,
			'line-heightUnit': '%',
			'line-height': 136,
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		l: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': 22,
			'line-heightUnit': '%',
			'line-height': 145,
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		m: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': 20,
			'line-heightUnit': '%',
			'line-height': 150,
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		s: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': '',
			'line-heightUnit': '%',
			'line-height': '',
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		xs: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': 19,
			'font-sizeUnit': 'px',
			'font-size': 29,
			'line-heightUnit': '%',
			'line-height': '',
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
	},
	h6: {
		label: 'Typography',
		general: {
			'font-family': 'Roboto',
			'font-options': {
				100: 'http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1MmgWxPKTM1K9nz.ttf',
				'100italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOiCnqEu92Fr1Mu51QrIzcXLsnzjYk.ttf',
				300: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmSU5vAx05IsDqlA.ttf',
				'300italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TjARc9AMX6lJBP.ttf',
				400: 'http://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf',
				italic:
					'http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1Mu52xPKTM1K9nz.ttf',
				500: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmEU9vAx05IsDqlA.ttf',
				'500italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51S7ABc9AMX6lJBP.ttf',
				700: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlvAx05IsDqlA.ttf',
				'700italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TzBhc9AMX6lJBP.ttf',
				900: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmYUtvAx05IsDqlA.ttf',
				'900italic':
					'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TLBBc9AMX6lJBP.ttf',
			},
			color: '#9b9b9b',
			'text-align': 'left',
			'font-sizeUnit': 'px',
			'font-size': 20,
			'line-heightUnit': '%',
			'line-height': 150,
			'letter-spacingUnit': 'px',
			'letter-spacing': 0,
			'font-weight': 400,
			'text-transform': 'none',
			'font-style': 'normal',
			'text-decoration': 'none',
			'text-shadow': '',
		},
		xxl: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': 26,
			'line-heightUnit': '%',
			'line-height': 139,
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		xl: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': 26,
			'line-heightUnit': '%',
			'line-height': 139,
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		l: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': 20,
			'line-heightUnit': '%',
			'line-height': 150,
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		m: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': 18,
			'line-heightUnit': '%',
			'line-height': 156,
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		s: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': '',
			'line-heightUnit': '%',
			'line-height': '',
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
		xs: {
			'font-family': '',
			'font-options': {},
			color: '',
			'text-align': '',
			'font-sizeUnit': 'px',
			'font-size': 18,
			'line-heightUnit': '%',
			'line-height': 28,
			'letter-spacingUnit': 'px',
			'letter-spacing': '',
			'font-weight': '',
			'text-transform': '',
			'font-style': '',
			'text-decoration': '',
			'text-shadow': '',
		},
	},
};

export default DefaultTypography;
