name: Bug report
title: 'PART AFFECTED :: summary'
description: Report a bug in MaxiBlocks plugin
labels: ['bug']
body:
    - type: textarea
      attributes:
          label: Description
          description: Please write a description of the bug, including what was expect to happen and what is currently happening.
          value: |
              1. Brief description
              <!-- Clear description of what the bug is. -->
              
              2. What was expected to happen
              <!-- Clear description of what was expected to happen. -->
              
              3. What actually happened
              <!-- Clear description of what actually happened. -->
              

      validations:
          required: true

    - type: textarea
      attributes:
          label: Step-by-step reproduction instructions
          description: Please write the steps needed to reproduce the bug.
          placeholder: |
              1. Go to '...'
              2. Click on '...'
              3. Scroll down to '...'
      validations:
          required: true

    - type: textarea
      attributes:
          label: Screenshots, screen recording, code snippet
          description: |
              If possible, please upload a screenshot or screen recording which demonstrates the bug.
      validations:
          required: false

    - type: textarea
      attributes:
          label: URL and/or Code editor
          description: |
              In case the bug is related to a specific URL /andor code editor, please provide the URL and/or code editor.
      validations:
          required: false

    - type: textarea
      attributes:
          label: Other information
          description: |
              Please, use this space to share additional information related with the bug.
      validations:
          required: false
