name: Bug report
description: Report a bug on MaxiBlocks
labels: ['bug']
body:
    - type: textarea
      attributes:
          label: Description
          description: Please write a brief description of the bug, including what you expect to happen and what is currently happening.
          placeholder: |
              Feature '...' is not working properly. I expect '...' to happen, but '...' happens instead
      validations:
          required: true

    - type: textarea
      attributes:
          label: Step-by-step reproduction instructions
          description: Please write the steps needed to reproduce the bug.
          placeholder: |
              1. Go to '...'
              2. Click on '...'
              3. Scroll down to '...'
      validations:
          required: true

    - type: textarea
      attributes:
          label: Screenshots, screen recording, code snippet
          description: |
              If possible, please upload a screenshot or screen recording which demonstrates the bug.
      validations:
          required: false

    - type: textarea
      attributes:
          label: URL and/or Code editor
          description: |
              In case the bug is related to a specific URL /andor code editor, please provide the URL and/or code editor.
      validations:
          required: false

    - type: textarea
      attributes:
          label: How to fix it
          description: |
              Please, if you have an idea or suggestion about how to fix the bug, write it here.
      validations:
          required: false

    - type: textarea
      attributes:
          label: Other information
          description: |
              Please, use this space to share additional information related with the bug.
      validations:
          required: false
