import getSCFromTypography from '../getSCFromTypography';

describe('getSCFromTypography', () => {
	it('returns a SC object', () => {
		const typographyObj = {
			'p-font-family-xxl': 'Roboto',
			'p-font-family-xl': 'Roboto',
			'p-font-family-l': 'Roboto',
			'p-font-family-m': 'Roboto',
			'p-font-family-s': 'Roboto',
			'p-font-family-xs': 'Roboto',
			'p-font-family-general': 'Roboto',
			'p-font-size-xxl': 20,
			'p-font-size-unit-xxl': 'px',
			'p-font-size-xl': 16,
			'p-font-size-unit-xl': 'px',
			'p-font-size-l': 16,
			'p-font-size-unit-l': 'px',
			'p-font-size-m': 16,
			'p-font-size-unit-m': 'px',
			'p-font-size-s': 16,
			'p-font-size-unit-s': 'px',
			'p-font-size-xs': 16,
			'p-font-size-unit-xs': 'px',
			'p-font-size-general': 16,
			'p-font-size-unit-general': 'px',
			'p-line-height-xxl': 1.5,
			'p-line-height-xl': 418.27,
			'p-line-height-l': 1.625,
			'p-line-height-m': 1.625,
			'p-line-height-s': 1.625,
			'p-line-height-xs': 1.625,
			'p-font-weight-xxl': '400',
			'p-font-weight-xl': '400',
			'p-font-weight-l': '400',
			'p-font-weight-m': '400',
			'p-font-weight-s': '400',
			'p-font-weight-xs': '400',
			'p-font-weight-general': '400',
			'p-letter-spacing-xxl': '0',
			'p-letter-spacing-unit-xxl': 'px',
			'p-letter-spacing-xl': '0',
			'p-letter-spacing-unit-xl': 'px',
			'p-letter-spacing-l': '0',
			'p-letter-spacing-unit-l': 'px',
			'p-letter-spacing-m': '0',
			'p-letter-spacing-unit-m': 'px',
			'p-letter-spacing-s': '0',
			'p-letter-spacing-unit-s': 'px',
			'p-letter-spacing-xs': '0',
			'p-letter-spacing-unit-xs': 'px',
			'p-letter-spacing-general': 0,
			'p-letter-spacing-unit-general': 'px',
			'p-text-transform-xxl': 'none',
			'p-text-transform-xl': 'none',
			'p-text-transform-l': 'none',
			'p-text-transform-m': 'none',
			'p-text-transform-s': 'none',
			'p-text-transform-xs': 'none',
			'p-text-transform-general': 'none',
			'p-font-style-xxl': 'normal',
			'p-font-style-xl': 'normal',
			'p-font-style-l': 'normal',
			'p-font-style-m': 'normal',
			'p-font-style-s': 'normal',
			'p-font-style-xs': 'normal',
			'p-font-style-general': 'normal',
			'p-text-decoration-xxl': 'unset',
			'p-text-decoration-xl': 'unset',
			'p-text-decoration-l': 'unset',
			'p-text-decoration-m': 'unset',
			'p-text-decoration-s': 'unset',
			'p-text-decoration-xs': 'unset',
			'p-text-decoration-general': 'unset',
		};
		const styleCards = {
			name: 'Maxi (Default)',
			status: 'active',
			styleCard: {
				dark: {},
				light: {},
			},
			styleCardDefaults: {
				dark: {},
				light: {
					'color-1': '#ffffff',
					'color-2': '#f2f9fd',
					'color-3': '#9b9b9b',
					'color-4': '#ff4a17',
					'color-5': '#000000',
					'color-6': '#c9340a',
					'color-7': '#081219',
					'p-font-family-general': 'Roboto',
					'p-font-size-general': '16px',
					'p-font-size-xxl': '20px',
					'p-font-size-xl': '16px',
					'p-font-size-l': '16px',
					'p-font-size-m': '16px',
					'p-font-size-s': '16px',
					'p-font-size-xs': '16px',
					'p-line-height-xxl': 1.5,
					'p-line-height-xl': 1.625,
					'p-line-height-l': 1.625,
					'p-line-height-m': 1.625,
					'p-line-height-s': 1.625,
					'p-line-height-xs': 1.625,
					'p-font-weight-general': '400',
					'p-letter-spacing-general': '0px',
					'p-text-transform-general': 'none',
					'p-font-style-general': 'normal',
					'p-text-decoration-general': 'unset',
				},
			},
		};
		const SCStyle = 'light';

		const result = getSCFromTypography(styleCards, SCStyle, typographyObj);
		const expectedResult = {
			'p-font-family-xxl': 'Roboto',
			'p-font-family-xl': 'Roboto',
			'p-font-family-l': 'Roboto',
			'p-font-family-m': 'Roboto',
			'p-font-family-s': 'Roboto',
			'p-font-family-xs': 'Roboto',
			'p-font-family-general': 'Roboto',
			'p-font-size-xxl': '20px',
			'p-font-size-xl': '16px',
			'p-font-size-l': '16px',
			'p-font-size-m': '16px',
			'p-font-size-s': '16px',
			'p-font-size-xs': '16px',
			'p-font-size-general': '16px',
			'p-line-height-xxl': 1.5,
			'p-line-height-xl': 418.27,
			'p-line-height-l': 1.625,
			'p-line-height-m': 1.625,
			'p-line-height-s': 1.625,
			'p-line-height-xs': 1.625,
			'p-font-weight-xxl': '400',
			'p-font-weight-xl': '400',
			'p-font-weight-l': '400',
			'p-font-weight-m': '400',
			'p-font-weight-s': '400',
			'p-font-weight-xs': '400',
			'p-font-weight-general': '400',
			'p-letter-spacing-xxl': '0px',
			'p-letter-spacing-xl': '0px',
			'p-letter-spacing-l': '0px',
			'p-letter-spacing-m': '0px',
			'p-letter-spacing-s': '0px',
			'p-letter-spacing-xs': '0px',
			'p-letter-spacing-general': '0px',
			'p-text-transform-xxl': 'none',
			'p-text-transform-xl': 'none',
			'p-text-transform-l': 'none',
			'p-text-transform-m': 'none',
			'p-text-transform-s': 'none',
			'p-text-transform-xs': 'none',
			'p-text-transform-general': 'none',
			'p-font-style-xxl': 'normal',
			'p-font-style-xl': 'normal',
			'p-font-style-l': 'normal',
			'p-font-style-m': 'normal',
			'p-font-style-s': 'normal',
			'p-font-style-xs': 'normal',
			'p-font-style-general': 'normal',
			'p-text-decoration-xxl': 'unset',
			'p-text-decoration-xl': 'unset',
			'p-text-decoration-l': 'unset',
			'p-text-decoration-m': 'unset',
			'p-text-decoration-s': 'unset',
			'p-text-decoration-xs': 'unset',
			'p-text-decoration-general': 'unset',
		};

		expect(result).toStrictEqual(expectedResult);
	});
});
