export const preset1 = {
	'icon-name': 'fas fa-arrow-right',
	'icon-position': 'right',
	'icon-spacing': 10,
	'icon-color': '#fff',
	'icon-border-color-general': '',
	'icon-border-style-general': 'none',
	'icon-border-top-width-general': '',
	'icon-border-right-width-general': '',
	'icon-border-bottom-width-general': '',
	'icon-border-left-width-general': '',
	'icon-background-color': '',
	'icon-background-gradient': '',
	'icon-background-gradient-opacity': 1,
	'icon-custom-padding': true,
	'icon-padding-top-general': 6,
	'icon-padding-right-general': 6,
	'icon-padding-bottom-general': 6,
	'icon-padding-left-general': 6,
	'border-top-left-radius-general': 0,
	'border-top-right-radius-general': 0,
	'border-bottom-right-radius-general': 0,
	'border-bottom-left-radius-general': 0,
	'icon-border-top-left-radius-general': 0,
	'icon-border-top-right-radius-general': 0,
	'icon-border-bottom-right-radius-general': 0,
	'icon-border-bottom-left-radius-general': 0,
};

export const preset2 = {
	'icon-name': 'fas fa-arrow-right',
	'icon-position': 'right',
	'icon-spacing': 10,
	'icon-color': '#fff',
	'icon-border-color-general': '',
	'icon-border-style-general': 'none',
	'icon-border-top-width-general': '',
	'icon-border-right-width-general': '',
	'icon-border-bottom-width-general': '',
	'icon-border-left-width-general': '',
	'icon-background-color': 'rgba(255,255,255, 0.5)',
	'icon-background-gradient': '',
	'icon-background-gradient-opacity': 1,
	'icon-custom-padding': true,
	'icon-padding-top-general': 6,
	'icon-padding-right-general': 6,
	'icon-padding-bottom-general': 6,
	'icon-padding-left-general': 6,
	'border-top-left-radius-general': 5,
	'border-top-right-radius-general': 5,
	'border-bottom-right-radius-general': 5,
	'border-bottom-left-radius-general': 5,
	'icon-border-top-left-radius-general': 5,
	'icon-border-top-right-radius-general': 5,
	'icon-border-bottom-right-radius-general': 5,
	'icon-border-bottom-left-radius-general': 5,
};

export const preset3 = {
	'icon-name': 'fas fa-arrow-right',
	'icon-position': 'right',
	'icon-spacing': 10,
	'icon-color': '#fff',
	'icon-border-color-general': '#fff',
	'icon-border-style-general': 'solid',
	'icon-border-top-width-general': 1,
	'icon-border-right-width-general': 1,
	'icon-border-bottom-width-general': 1,
	'icon-border-left-width-general': 1,
	'icon-background-color': '',
	'icon-background-gradient': '',
	'icon-background-gradient-opacity': 1,
	'icon-custom-padding': true,
	'icon-padding-top-general': 5,
	'icon-padding-right-general': 5,
	'icon-padding-bottom-general': 5,
	'icon-padding-left-general': 5,
	'border-top-left-radius-general': 0,
	'border-top-right-radius-general': 0,
	'border-bottom-right-radius-general': 0,
	'border-bottom-left-radius-general': 0,
	'icon-border-top-left-radius-general': 0,
	'icon-border-top-right-radius-general': 0,
	'icon-border-bottom-right-radius-general': 0,
	'icon-border-bottom-left-radius-general': 0,
};
