const aliasMap = {
	'--maxi-primary-color': '--mpc',
	'--maxi-secondary-color': '--msc',
	'--maxi-tertiary-color': '--mtc',
	'--maxi-white': '--mw',
	'--maxi-off-white': '--mow',
	'--maxi-grey': '--mg',
	'--maxi-grey-light': '--mgl',
	'--maxi-grey-dark': '--mgd',
	'--maxi-black': '--mb',
	'--maxi-light-blue': '--mlb',
	'--maxi-light-blue-alt': '--mlba',
	'--maxi-highlight-color': '--mhc',
	'--maxi-light-yellow': '--mly',
	'--maxi-pastel-green': '--mpg',
	'--maxi-mid-green': '--mmg',
	'--maxi-whisper-green': '--mwg',
	'--maxi-cloud-primary': '--mcp',
	'--maxi-cloud-primary-light': '--mcpl',
	'--maxi-cloud-primary-bright': '--mcpb',
	'--maxi-cloud-primary-whisper': '--mcpw',
	'--maxi-cloud-primary-contrast': '--mcpc',
	'--maxi-cloud-hover': '--mch',
	'--maxi-cloud-hover-deep': '--mchd',
	'--maxi-accessibility-grey': '--mag',
	'--maxi-trans-std': '--mt',
	'--maxi-font-sans': '--mf',
};

module.exports = { aliasMap };
