const defaultTypography = {
	p: {
		'font-family-general': 'Roboto',
		'font-options-general': {
			100: 'http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1MmgWxPKTM1K9nz.ttf',
			'100italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOiCnqEu92Fr1Mu51QrIzcXLsnzjYk.ttf',
			300: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmSU5vAx05IsDqlA.ttf',
			'300italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TjARc9AMX6lJBP.ttf',
			400: 'http://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf',
			italic:
				'http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1Mu52xPKTM1K9nz.ttf',
			500: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmEU9vAx05IsDqlA.ttf',
			'500italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51S7ABc9AMX6lJBP.ttf',
			700: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlvAx05IsDqlA.ttf',
			'700italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TzBhc9AMX6lJBP.ttf',
			900: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmYUtvAx05IsDqlA.ttf',
			'900italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TLBBc9AMX6lJBP.ttf',
		},
		'color-general': '#9b9b9b',
		'text-align-general': '',
		'font-size.unit-general': 'px',
		'font-size-general': 16,
		'line-height-unit-general': '',
		'line-height-general': 1.625,
		'letter-spacing-unit-general': 'px',
		'letter-spacing-general': 0,
		'font-weight-general': 400,
		'text-transform-general': 'none',
		'font-style-general': 'normal',
		'text-decoration-general': 'none',
		'text-shadow-general': '',
		'vertical-align-general': '',
		'font-family-xxl': '',
		'font-options-xxl': {},
		'color-xxl': '',
		'text-align-xxl': '',
		'font-size-unit-xxl': 'px',
		'font-size-xxl': 20,
		'line-height-unit-xxl': '',
		'line-height-xxl': 1.5,
		'letter-spacing-unit-xxl': 'px',
		'letter-spacing-xxl': '',
		'font-weight-xxl': '',
		'text-transform-xxl': '',
		'font-style-xxl': '',
		'text-decoration-xxl': '',
		'text-shadow-xxl': '',
		'vertical-align-xxl': '',
		'font-family-xl': '',
		'font-options-xl': {},
		'color-xl': '',
		'text-align-xl': '',
		'font-size-unit-xl': 'px',
		'font-size-xl': 18,
		'line-height-unit-xl': '',
		'line-height-xl': 1.35,
		'letter-spacing-unit-xl': 'px',
		'letter-spacing-xl': '',
		'font-weight-xl': '',
		'text-transform-xl': '',
		'font-style-xl': '',
		'text-decoration-xl': '',
		'text-shadow-xl': '',
		'vertical-align-xl': '',
		'font-family-l': '',
		'font-options-l': {},
		'color-l': '',
		'text-align-l': '',
		'font-size-unit-l': 'px',
		'font-size-l': 16,
		'line-height-unit-l': '',
		'line-height-l': 1.625,
		'letter-spacing-unit-l': 'px',
		'letter-spacing-l': '',
		'font-weight-l': '',
		'text-transform-l': '',
		'font-style-l': '',
		'text-decoration-l': '',
		'text-shadow-l': '',
		'vertical-align-l': '',
		'font-family-m': '',
		'font-options-m': {},
		'color-m': '',
		'text-align-m': '',
		'font-size-unit-m': 'px',
		'font-size-m': '',
		'line-height-unit-m': '',
		'line-height-m': '',
		'letter-spacing-unit-m': 'px',
		'letter-spacing-m': '',
		'font-weight-m': '',
		'text-transform-m': '',
		'font-style-m': '',
		'text-decoration-m': '',
		'text-shadow-m': '',
		'vertical-align-m': '',
		'font-family-s': '',
		'font-options-s': {},
		'color-s': '',
		'text-align-s': '',
		'font-size-unit-s': 'px',
		'font-size-s': '',
		'line-height-unit-s': '',
		'line-height-s': '',
		'letter-spacing-unit-s': 'px',
		'letter-spacing-s': '',
		'font-weight-s': '',
		'text-transform-s': '',
		'font-style-s': '',
		'text-decoration-s': '',
		'text-shadow-s': '',
		'vertical-align-s': '',
		'font-family-xs': '',
		'font-options-xs': {},
		'color-xs': '',
		'text-align-xs': '',
		'font-size-unit-xs': 'px',
		'font-size-xs': '',
		'line-height-unit-xs': '',
		'line-height-xs': '',
		'letter-spacing-unit-xs': 'px',
		'letter-spacing-xs': '',
		'font-weight-xs': '',
		'text-transform-xs': '',
		'font-style-xs': '',
		'text-decoration-xs': '',
		'text-shadow-xs': '',
		'vertical-align-xs': '',
	},
	link: {
		'font-family-general': 'Roboto',
		'font-options-general': {
			100: 'http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1MmgWxPKTM1K9nz.ttf',
			'100italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOiCnqEu92Fr1Mu51QrIzcXLsnzjYk.ttf',
			300: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmSU5vAx05IsDqlA.ttf',
			'300italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TjARc9AMX6lJBP.ttf',
			400: 'http://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf',
			italic:
				'http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1Mu52xPKTM1K9nz.ttf',
			500: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmEU9vAx05IsDqlA.ttf',
			'500italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51S7ABc9AMX6lJBP.ttf',
			700: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlvAx05IsDqlA.ttf',
			'700italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TzBhc9AMX6lJBP.ttf',
			900: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmYUtvAx05IsDqlA.ttf',
			'900italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TLBBc9AMX6lJBP.ttf',
		},
		'color-general': '#9b9b9b',
		'text-align-general': '',
		'font-size.unit-general': 'px',
		'font-size-general': 16,
		'line-height-unit-general': '',
		'line-height-general': 1.625,
		'letter-spacing-unit-general': 'px',
		'letter-spacing-general': 0,
		'font-weight-general': 400,
		'text-transform-general': 'none',
		'font-style-general': 'normal',
		'text-decoration-general': 'underline',
		'text-shadow-general': '',
		'vertical-align-general': '',
		'font-family-xxl': '',
		'font-options-xxl': {},
		'color-xxl': '',
		'text-align-xxl': '',
		'font-size-unit-xxl': 'px',
		'font-size-xxl': 20,
		'line-height-unit-xxl': '',
		'line-height-xxl': 1.5,
		'letter-spacing-unit-xxl': 'px',
		'letter-spacing-xxl': '',
		'font-weight-xxl': '',
		'text-transform-xxl': '',
		'font-style-xxl': '',
		'text-decoration-xxl': '',
		'text-shadow-xxl': '',
		'vertical-align-xxl': '',
		'font-family-xl': '',
		'font-options-xl': {},
		'color-xl': '',
		'text-align-xl': '',
		'font-size-unit-xl': 'px',
		'font-size-xl': 18,
		'line-height-unit-xl': '',
		'line-height-xl': 1.35,
		'letter-spacing-unit-xl': 'px',
		'letter-spacing-xl': '',
		'font-weight-xl': '',
		'text-transform-xl': '',
		'font-style-xl': '',
		'text-decoration-xl': '',
		'text-shadow-xl': '',
		'vertical-align-xl': '',
		'font-family-l': '',
		'font-options-l': {},
		'color-l': '',
		'text-align-l': '',
		'font-size-unit-l': 'px',
		'font-size-l': 16,
		'line-height-unit-l': '',
		'line-height-l': 1.625,
		'letter-spacing-unit-l': 'px',
		'letter-spacing-l': '',
		'font-weight-l': '',
		'text-transform-l': '',
		'font-style-l': '',
		'text-decoration-l': '',
		'text-shadow-l': '',
		'vertical-align-l': '',
		'font-family-m': '',
		'font-options-m': {},
		'color-m': '',
		'text-align-m': '',
		'font-size-unit-m': 'px',
		'font-size-m': '',
		'line-height-unit-m': '',
		'line-height-m': '',
		'letter-spacing-unit-m': 'px',
		'letter-spacing-m': '',
		'font-weight-m': '',
		'text-transform-m': '',
		'font-style-m': '',
		'text-decoration-m': '',
		'text-shadow-m': '',
		'vertical-align-m': '',
		'font-family-s': '',
		'font-options-s': {},
		'color-s': '',
		'text-align-s': '',
		'font-size-unit-s': 'px',
		'font-size-s': '',
		'line-height-unit-s': '',
		'line-height-s': '',
		'letter-spacing-unit-s': 'px',
		'letter-spacing-s': '',
		'font-weight-s': '',
		'text-transform-s': '',
		'font-style-s': '',
		'text-decoration-s': '',
		'text-shadow-s': '',
		'vertical-align-s': '',
		'font-family-xs': '',
		'font-options-xs': {},
		'color-xs': '',
		'text-align-xs': '',
		'font-size-unit-xs': 'px',
		'font-size-xs': '',
		'line-height-unit-xs': '',
		'line-height-xs': '',
		'letter-spacing-unit-xs': 'px',
		'letter-spacing-xs': '',
		'font-weight-xs': '',
		'text-transform-xs': '',
		'font-style-xs': '',
		'text-decoration-xs': '',
		'text-shadow-xs': '',
		'vertical-align-xs': '',
	},
	h1: {
		'font-family-general': 'Roboto',
		'font-options-general': {
			100: 'http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1MmgWxPKTM1K9nz.ttf',
			'100italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOiCnqEu92Fr1Mu51QrIzcXLsnzjYk.ttf',
			300: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmSU5vAx05IsDqlA.ttf',
			'300italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TjARc9AMX6lJBP.ttf',
			400: 'http://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf',
			italic:
				'http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1Mu52xPKTM1K9nz.ttf',
			500: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmEU9vAx05IsDqlA.ttf',
			'500italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51S7ABc9AMX6lJBP.ttf',
			700: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlvAx05IsDqlA.ttf',
			'700italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TzBhc9AMX6lJBP.ttf',
			900: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmYUtvAx05IsDqlA.ttf',
			'900italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TLBBc9AMX6lJBP.ttf',
		},
		'color-general': '#081219',
		'text-align-general': '',
		'font-size.unit-general': 'px',
		'font-size-general': 45,
		'line-height-unit-general': '',
		'line-height-general': 1.22,
		'letter-spacing-unit-general': 'px',
		'letter-spacing-general': 0,
		'font-weight-general': 500,
		'text-transform-general': 'none',
		'font-style-general': 'normal',
		'text-decoration-general': 'none',
		'text-shadow-general': '',
		'vertical-align-general': '',
		'font-family-xxl': '',
		'font-options-xxl': {},
		'color-xxl': '',
		'text-align-xxl': '',
		'font-size-unit-xxl': 'px',
		'font-size-xxl': 55,
		'line-height-unit-xxl': '',
		'line-height-xxl': 1.18,
		'letter-spacing-unit-xxl': 'px',
		'letter-spacing-xxl': '',
		'font-weight-xxl': '',
		'text-transform-xxl': '',
		'font-style-xxl': '',
		'text-decoration-xxl': '',
		'text-shadow-xxl': '',
		'vertical-align-xxl': '',
		'font-family-xl': '',
		'font-options-xl': {},
		'color-xl': '',
		'text-align-xl': '',
		'font-size-unit-xl': 'px',
		'font-size-xl': 50,
		'line-height-unit-xl': '',
		'line-height-xl': 1.1,
		'letter-spacing-unit-xl': 'px',
		'letter-spacing-xl': '',
		'font-weight-xl': '',
		'text-transform-xl': '',
		'font-style-xl': '',
		'text-decoration-xl': '',
		'text-shadow-xl': '',
		'vertical-align-xl': '',
		'font-family-l': '',
		'font-options-l': {},
		'color-l': '',
		'text-align-l': '',
		'font-size-unit-l': 'px',
		'font-size-l': 45,
		'line-height-unit-l': '',
		'line-height-l': 1.22,
		'letter-spacing-unit-l': 'px',
		'letter-spacing-l': '',
		'font-weight-l': '',
		'text-transform-l': '',
		'font-style-l': '',
		'text-decoration-l': '',
		'text-shadow-l': '',
		'vertical-align-l': '',
		'font-family-m': '',
		'font-options-m': {},
		'color-m': '',
		'text-align-m': '',
		'font-size-unit-m': 'px',
		'font-size-m': 36,
		'line-height-unit-m': '',
		'line-height-m': 1.27,
		'letter-spacing-unit-m': 'px',
		'letter-spacing-m': '',
		'font-weight-m': '',
		'text-transform-m': '',
		'font-style-m': '',
		'text-decoration-m': '',
		'text-shadow-m': '',
		'vertical-align-m': '',
		'font-family-s': '',
		'font-options-s': {},
		'color-s': '',
		'text-align-s': '',
		'font-size-unit-s': 'px',
		'font-size-s': '',
		'line-height-unit-s': '',
		'line-height-s': '',
		'letter-spacing-unit-s': 'px',
		'letter-spacing-s': '',
		'font-weight-s': '',
		'text-transform-s': '',
		'font-style-s': '',
		'text-decoration-s': '',
		'text-shadow-s': '',
		'vertical-align-s': '',
		'font-family-xs': '',
		'font-options-xs': {},
		'color-xs': '',
		'text-align-xs': '',
		'font-size-unit-xs': 'px',
		'font-size-xs': '',
		'line-height-unit-xs': '',
		'line-height-xs': '',
		'letter-spacing-unit-xs': 'px',
		'letter-spacing-xs': '',
		'font-weight-xs': '',
		'text-transform-xs': '',
		'font-style-xs': '',
		'text-decoration-xs': '',
		'text-shadow-xs': '',
		'vertical-align-xs': '',
	},
	h2: {
		'font-family-general': 'Roboto',
		'font-options-general': {
			100: 'http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1MmgWxPKTM1K9nz.ttf',
			'100italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOiCnqEu92Fr1Mu51QrIzcXLsnzjYk.ttf',
			300: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmSU5vAx05IsDqlA.ttf',
			'300italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TjARc9AMX6lJBP.ttf',
			400: 'http://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf',
			italic:
				'http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1Mu52xPKTM1K9nz.ttf',
			500: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmEU9vAx05IsDqlA.ttf',
			'500italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51S7ABc9AMX6lJBP.ttf',
			700: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlvAx05IsDqlA.ttf',
			'700italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TzBhc9AMX6lJBP.ttf',
			900: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmYUtvAx05IsDqlA.ttf',
			'900italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TLBBc9AMX6lJBP.ttf',
		},
		'color-general': '#081219',
		'text-align-general': '',
		'font-size.unit-general': 'px',
		'font-size-general': 38,
		'line-height-unit-general': '',
		'line-height-general': 1.33,
		'letter-spacing-unit-general': 'px',
		'letter-spacing-general': 0,
		'font-weight-general': 500,
		'text-transform-general': 'none',
		'font-style-general': 'normal',
		'text-decoration-general': 'none',
		'text-shadow-general': '',
		'vertical-align-general': '',
		'font-family-xxl': '',
		'font-options-xxl': {},
		'color-xxl': '',
		'text-align-xxl': '',
		'font-size-unit-xxl': 'px',
		'font-size-xxl': 48,
		'line-height-unit-xxl': '',
		'line-height-xxl': 1.21,
		'letter-spacing-unit-xxl': 'px',
		'letter-spacing-xxl': '',
		'font-weight-xxl': '',
		'text-transform-xxl': '',
		'font-style-xxl': '',
		'text-decoration-xxl': '',
		'text-shadow-xxl': '',
		'vertical-align-xxl': '',
		'font-family-xl': '',
		'font-options-xl': {},
		'color-xl': '',
		'text-align-xl': '',
		'font-size-unit-xl': 'px',
		'font-size-xl': 42,
		'line-height-unit-xl': '',
		'line-height-xl': 1.05,
		'letter-spacing-unit-xl': 'px',
		'letter-spacing-xl': '',
		'font-weight-xl': '',
		'text-transform-xl': '',
		'font-style-xl': '',
		'text-decoration-xl': '',
		'text-shadow-xl': '',
		'vertical-align-xl': '',
		'font-family-l': '',
		'font-options-l': {},
		'color-l': '',
		'text-align-l': '',
		'font-size-unit-l': 'px',
		'font-size-l': 38,
		'line-height-unit-l': '',
		'line-height-l': 1.26,
		'letter-spacing-unit-l': 'px',
		'letter-spacing-l': '',
		'font-weight-l': '',
		'text-transform-l': '',
		'font-style-l': '',
		'text-decoration-l': '',
		'text-shadow-l': '',
		'vertical-align-l': '',
		'font-family-m': '',
		'font-options-m': {},
		'color-m': '',
		'text-align-m': '',
		'font-size-unit-m': 'px',
		'font-size-m': 30,
		'line-height-unit-m': '',
		'line-height-m': 1.33,
		'letter-spacing-unit-m': 'px',
		'letter-spacing-m': '',
		'font-weight-m': '',
		'text-transform-m': '',
		'font-style-m': '',
		'text-decoration-m': '',
		'text-shadow-m': '',
		'vertical-align-m': '',
		'font-family-s': '',
		'font-options-s': {},
		'color-s': '',
		'text-align-s': '',
		'font-size-unit-s': 'px',
		'font-size-s': '',
		'line-height-unit-s': '',
		'line-height-s': '',
		'letter-spacing-unit-s': 'px',
		'letter-spacing-s': '',
		'font-weight-s': '',
		'text-transform-s': '',
		'font-style-s': '',
		'text-decoration-s': '',
		'text-shadow-s': '',
		'vertical-align-s': '',
		'font-family-xs': '',
		'font-options-xs': {},
		'color-xs': '',
		'text-align-xs': '',
		'font-size-unit-xs': 'px',
		'font-size-xs': '',
		'line-height-unit-xs': '',
		'line-height-xs': '',
		'letter-spacing-unit-xs': 'px',
		'letter-spacing-xs': '',
		'font-weight-xs': '',
		'text-transform-xs': '',
		'font-style-xs': '',
		'text-decoration-xs': '',
		'text-shadow-xs': '',
		'vertical-align-xs': '',
	},
	h3: {
		'font-family-general': 'Roboto',
		'font-options-general': {
			100: 'http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1MmgWxPKTM1K9nz.ttf',
			'100italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOiCnqEu92Fr1Mu51QrIzcXLsnzjYk.ttf',
			300: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmSU5vAx05IsDqlA.ttf',
			'300italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TjARc9AMX6lJBP.ttf',
			400: 'http://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf',
			italic:
				'http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1Mu52xPKTM1K9nz.ttf',
			500: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmEU9vAx05IsDqlA.ttf',
			'500italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51S7ABc9AMX6lJBP.ttf',
			700: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlvAx05IsDqlA.ttf',
			'700italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TzBhc9AMX6lJBP.ttf',
			900: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmYUtvAx05IsDqlA.ttf',
			'900italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TLBBc9AMX6lJBP.ttf',
		},
		'color-general': '#081219',
		'text-align-general': '',
		'font-size.unit-general': 'px',
		'font-size-general': 30,
		'line-height-unit-general': '',
		'line-height-general': 1.33,
		'letter-spacing-unit-general': 'px',
		'letter-spacing-general': 0,
		'font-weight-general': 500,
		'text-transform-general': 'none',
		'font-style-general': 'normal',
		'text-decoration-general': 'none',
		'text-shadow-general': '',
		'vertical-align-general': '',
		'font-family-xxl': '',
		'font-options-xxl': {},
		'color-xxl': '',
		'text-align-xxl': '',
		'font-size-unit-xxl': 'px',
		'font-size-xxl': 40,
		'line-height-unit-xxl': '',
		'line-height-xxl': 1.25,
		'letter-spacing-unit-xxl': 'px',
		'letter-spacing-xxl': '',
		'font-weight-xxl': '',
		'text-transform-xxl': '',
		'font-style-xxl': '',
		'text-decoration-xxl': '',
		'text-shadow-xxl': '',
		'vertical-align-xxl': '',
		'font-family-xl': '',
		'font-options-xl': {},
		'color-xl': '',
		'text-align-xl': '',
		'font-size-unit-xl': 'px',
		'font-size-xl': 35,
		'line-height-unit-xl': '',
		'line-height-xl': 1.09,
		'letter-spacing-unit-xl': 'px',
		'letter-spacing-xl': '',
		'font-weight-xl': '',
		'text-transform-xl': '',
		'font-style-xl': '',
		'text-decoration-xl': '',
		'text-shadow-xl': '',
		'vertical-align-xl': '',
		'font-family-l': '',
		'font-options-l': {},
		'color-l': '',
		'text-align-l': '',
		'font-size-unit-l': 'px',
		'font-size-l': 30,
		'line-height-unit-l': '',
		'line-height-l': 1.33,
		'letter-spacing-unit-l': 'px',
		'letter-spacing-l': '',
		'font-weight-l': '',
		'text-transform-l': '',
		'font-style-l': '',
		'text-decoration-l': '',
		'text-shadow-l': '',
		'vertical-align-l': '',
		'font-family-m': '',
		'font-options-m': {},
		'color-m': '',
		'text-align-m': '',
		'font-size-unit-m': 'px',
		'font-size-m': 28,
		'line-height-unit-m': '',
		'line-height-m': 1.36,
		'letter-spacing-unit-m': 'px',
		'letter-spacing-m': '',
		'font-weight-m': '',
		'text-transform-m': '',
		'font-style-m': '',
		'text-decoration-m': '',
		'text-shadow-m': '',
		'vertical-align-m': '',
		'font-family-s': '',
		'font-options-s': {},
		'color-s': '',
		'text-align-s': '',
		'font-size-unit-s': 'px',
		'font-size-s': '',
		'line-height-unit-s': '',
		'line-height-s': '',
		'letter-spacing-unit-s': 'px',
		'letter-spacing-s': '',
		'font-weight-s': '',
		'text-transform-s': '',
		'font-style-s': '',
		'text-decoration-s': '',
		'text-shadow-s': '',
		'vertical-align-s': '',
		'font-family-xs': '',
		'font-options-xs': {},
		'color-xs': '',
		'text-align-xs': '',
		'font-size-unit-xs': 'px',
		'font-size-xs': '',
		'line-height-unit-xs': '',
		'line-height-xs': '',
		'letter-spacing-unit-xs': 'px',
		'letter-spacing-xs': '',
		'font-weight-xs': '',
		'text-transform-xs': '',
		'font-style-xs': '',
		'text-decoration-xs': '',
		'text-shadow-xs': '',
		'vertical-align-xs': '',
	},
	h4: {
		'font-family-general': 'Roboto',
		'font-options-general': {
			100: 'http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1MmgWxPKTM1K9nz.ttf',
			'100italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOiCnqEu92Fr1Mu51QrIzcXLsnzjYk.ttf',
			300: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmSU5vAx05IsDqlA.ttf',
			'300italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TjARc9AMX6lJBP.ttf',
			400: 'http://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf',
			italic:
				'http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1Mu52xPKTM1K9nz.ttf',
			500: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmEU9vAx05IsDqlA.ttf',
			'500italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51S7ABc9AMX6lJBP.ttf',
			700: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlvAx05IsDqlA.ttf',
			'700italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TzBhc9AMX6lJBP.ttf',
			900: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmYUtvAx05IsDqlA.ttf',
			'900italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TLBBc9AMX6lJBP.ttf',
		},
		'color-general': '#081219',
		'text-align-general': '',
		'font-size.unit-general': 'px',
		'font-size-general': 26,
		'line-height-unit-general': '',
		'line-height-general': 1.39,
		'letter-spacing-unit-general': 'px',
		'letter-spacing-general': 0,
		'font-weight-general': 500,
		'text-transform-general': 'none',
		'font-style-general': 'normal',
		'text-decoration-general': 'none',
		'text-shadow-general': '',
		'vertical-align-general': '',
		'font-family-xxl': '',
		'font-options-xxl': {},
		'color-xxl': '',
		'text-align-xxl': '',
		'font-size-unit-xxl': 'px',
		'font-size-xxl': 30,
		'line-height-unit-xxl': '',
		'line-height-xxl': 1.33,
		'letter-spacing-unit-xxl': 'px',
		'letter-spacing-xxl': '',
		'font-weight-xxl': '',
		'text-transform-xxl': '',
		'font-style-xxl': '',
		'text-decoration-xxl': '',
		'text-shadow-xxl': '',
		'vertical-align-xxl': '',
		'font-family-xl': '',
		'font-options-xl': {},
		'color-xl': '',
		'text-align-xl': '',
		'font-size-unit-xl': 'px',
		'font-size-xl': 28,
		'line-height-unit-xl': '',
		'line-height-xl': 1.24,
		'letter-spacing-unit-xl': 'px',
		'letter-spacing-xl': '',
		'font-weight-xl': '',
		'text-transform-xl': '',
		'font-style-xl': '',
		'text-decoration-xl': '',
		'text-shadow-xl': '',
		'vertical-align-xl': '',
		'font-family-l': '',
		'font-options-l': {},
		'color-l': '',
		'text-align-l': '',
		'font-size-unit-l': 'px',
		'font-size-l': 26,
		'line-height-unit-l': '',
		'line-height-l': 1.39,
		'letter-spacing-unit-l': 'px',
		'letter-spacing-l': '',
		'font-weight-l': '',
		'text-transform-l': '',
		'font-style-l': '',
		'text-decoration-l': '',
		'text-shadow-l': '',
		'vertical-align-l': '',
		'font-family-m': '',
		'font-options-m': {},
		'color-m': '',
		'text-align-m': '',
		'font-size-unit-m': 'px',
		'font-size-m': 24,
		'line-height-unit-m': '',
		'line-height-m': 1.42,
		'letter-spacing-unit-m': 'px',
		'letter-spacing-m': '',
		'font-weight-m': '',
		'text-transform-m': '',
		'font-style-m': '',
		'text-decoration-m': '',
		'text-shadow-m': '',
		'vertical-align-m': '',
		'font-family-s': '',
		'font-options-s': {},
		'color-s': '',
		'text-align-s': '',
		'font-size-unit-s': 'px',
		'font-size-s': '',
		'line-height-unit-s': '',
		'line-height-s': '',
		'letter-spacing-unit-s': 'px',
		'letter-spacing-s': '',
		'font-weight-s': '',
		'text-transform-s': '',
		'font-style-s': '',
		'text-decoration-s': '',
		'text-shadow-s': '',
		'vertical-align-s': '',
		'font-family-xs': '',
		'font-options-xs': {},
		'color-xs': '',
		'text-align-xs': '',
		'font-size-unit-xs': 'px',
		'font-size-xs': '',
		'line-height-unit-xs': '',
		'line-height-xs': '',
		'letter-spacing-unit-xs': 'px',
		'letter-spacing-xs': '',
		'font-weight-xs': '',
		'text-transform-xs': '',
		'font-style-xs': '',
		'text-decoration-xs': '',
		'text-shadow-xs': '',
		'vertical-align-xs': '',
	},
	h5: {
		'font-family-general': 'Roboto',
		'font-options-general': {
			100: 'http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1MmgWxPKTM1K9nz.ttf',
			'100italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOiCnqEu92Fr1Mu51QrIzcXLsnzjYk.ttf',
			300: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmSU5vAx05IsDqlA.ttf',
			'300italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TjARc9AMX6lJBP.ttf',
			400: 'http://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf',
			italic:
				'http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1Mu52xPKTM1K9nz.ttf',
			500: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmEU9vAx05IsDqlA.ttf',
			'500italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51S7ABc9AMX6lJBP.ttf',
			700: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlvAx05IsDqlA.ttf',
			'700italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TzBhc9AMX6lJBP.ttf',
			900: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmYUtvAx05IsDqlA.ttf',
			'900italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TLBBc9AMX6lJBP.ttf',
		},
		'color-general': '#081219',
		'text-align-general': '',
		'font-size.unit-general': 'px',
		'font-size-general': 22,
		'line-height-unit-general': '',
		'line-height-general': 1.45,
		'letter-spacing-unit-general': 'px',
		'letter-spacing-general': 0,
		'font-weight-general': 500,
		'text-transform-general': 'none',
		'font-style-general': 'normal',
		'text-decoration-general': 'none',
		'text-shadow-general': '',
		'vertical-align-general': '',
		'font-family-xxl': '',
		'font-options-xxl': {},
		'color-xxl': '',
		'text-align-xxl': '',
		'font-size-unit-xxl': 'px',
		'font-size-xxl': 28,
		'line-height-unit-xxl': '',
		'line-height-xxl': 1.36,
		'letter-spacing-unit-xxl': 'px',
		'letter-spacing-xxl': '',
		'font-weight-xxl': '',
		'text-transform-xxl': '',
		'font-style-xxl': '',
		'text-decoration-xxl': '',
		'text-shadow-xxl': '',
		'vertical-align-xxl': '',
		'font-family-xl': '',
		'font-options-xl': {},
		'color-xl': '',
		'text-align-xl': '',
		'font-size-unit-xl': 'px',
		'font-size-xl': 26,
		'line-height-unit-xl': '',
		'line-height-xl': 1.26,
		'letter-spacing-unit-xl': 'px',
		'letter-spacing-xl': '',
		'font-weight-xl': '',
		'text-transform-xl': '',
		'font-style-xl': '',
		'text-decoration-xl': '',
		'text-shadow-xl': '',
		'vertical-align-xl': '',
		'font-family-l': '',
		'font-options-l': {},
		'color-l': '',
		'text-align-l': '',
		'font-size-unit-l': 'px',
		'font-size-l': 22,
		'line-height-unit-l': '',
		'line-height-l': 1.45,
		'letter-spacing-unit-l': 'px',
		'letter-spacing-l': '',
		'font-weight-l': '',
		'text-transform-l': '',
		'font-style-l': '',
		'text-decoration-l': '',
		'text-shadow-l': '',
		'vertical-align-l': '',
		'font-family-m': '',
		'font-options-m': {},
		'color-m': '',
		'text-align-m': '',
		'font-size-unit-m': 'px',
		'font-size-m': 20,
		'line-height-unit-m': '',
		'line-height-m': 1.5,
		'letter-spacing-unit-m': 'px',
		'letter-spacing-m': '',
		'font-weight-m': '',
		'text-transform-m': '',
		'font-style-m': '',
		'text-decoration-m': '',
		'text-shadow-m': '',
		'vertical-align-m': '',
		'font-family-s': '',
		'font-options-s': {},
		'color-s': '',
		'text-align-s': '',
		'font-size-unit-s': 'px',
		'font-size-s': '',
		'line-height-unit-s': '',
		'line-height-s': '',
		'letter-spacing-unit-s': 'px',
		'letter-spacing-s': '',
		'font-weight-s': '',
		'text-transform-s': '',
		'font-style-s': '',
		'text-decoration-s': '',
		'text-shadow-s': '',
		'vertical-align-s': '',
		'font-family-xs': '',
		'font-options-xs': {},
		'color-xs': '',
		'text-align-xs': '',
		'font-size-unit-xs': 'px',
		'font-size-xs': '',
		'line-height-unit-xs': '',
		'line-height-xs': '',
		'letter-spacing-unit-xs': 'px',
		'letter-spacing-xs': '',
		'font-weight-xs': '',
		'text-transform-xs': '',
		'font-style-xs': '',
		'text-decoration-xs': '',
		'text-shadow-xs': '',
		'vertical-align-xs': '',
	},
	h6: {
		'font-family-general': 'Roboto',
		'font-options-general': {
			100: 'http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1MmgWxPKTM1K9nz.ttf',
			'100italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOiCnqEu92Fr1Mu51QrIzcXLsnzjYk.ttf',
			300: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmSU5vAx05IsDqlA.ttf',
			'300italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TjARc9AMX6lJBP.ttf',
			400: 'http://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf',
			italic:
				'http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1Mu52xPKTM1K9nz.ttf',
			500: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmEU9vAx05IsDqlA.ttf',
			'500italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51S7ABc9AMX6lJBP.ttf',
			700: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlvAx05IsDqlA.ttf',
			'700italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TzBhc9AMX6lJBP.ttf',
			900: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmYUtvAx05IsDqlA.ttf',
			'900italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TLBBc9AMX6lJBP.ttf',
		},
		'color-general': '#081219',
		'text-align-general': '',
		'font-size.unit-general': 'px',
		'font-size-general': 20,
		'line-height-unit-general': '',
		'line-height-general': 1.5,
		'letter-spacing-unit-general': 'px',
		'letter-spacing-general': 0,
		'font-weight-general': 500,
		'text-transform-general': 'none',
		'font-style-general': 'normal',
		'text-decoration-general': 'none',
		'text-shadow-general': '',
		'vertical-align-general': '',
		'font-family-xxl': '',
		'font-options-xxl': {},
		'color-xxl': '',
		'text-align-xxl': '',
		'font-size-unit-xxl': 'px',
		'font-size-xxl': 26,
		'line-height-unit-xxl': '',
		'line-height-xxl': 1.39,
		'letter-spacing-unit-xxl': 'px',
		'letter-spacing-xxl': '',
		'font-weight-xxl': '',
		'text-transform-xxl': '',
		'font-style-xxl': '',
		'text-decoration-xxl': '',
		'text-shadow-xxl': '',
		'vertical-align-xxl': '',
		'font-family-xl': '',
		'font-options-xl': {},
		'color-xl': '',
		'text-align-xl': '',
		'font-size-unit-xl': 'px',
		'font-size-xl': 24,
		'line-height-unit-xl': '',
		'line-height-xl': 1.29,
		'letter-spacing-unit-xl': 'px',
		'letter-spacing-xl': '',
		'font-weight-xl': '',
		'text-transform-xl': '',
		'font-style-xl': '',
		'text-decoration-xl': '',
		'text-shadow-xl': '',
		'vertical-align-xl': '',
		'font-family-l': '',
		'font-options-l': {},
		'color-l': '',
		'text-align-l': '',
		'font-size-unit-l': 'px',
		'font-size-l': 20,
		'line-height-unit-l': '',
		'line-height-l': 1.5,
		'letter-spacing-unit-l': 'px',
		'letter-spacing-l': '',
		'font-weight-l': '',
		'text-transform-l': '',
		'font-style-l': '',
		'text-decoration-l': '',
		'text-shadow-l': '',
		'vertical-align-l': '',
		'font-family-m': '',
		'font-options-m': {},
		'color-m': '',
		'text-align-m': '',
		'font-size-unit-m': 'px',
		'font-size-m': 18,
		'line-height-unit-m': '',
		'line-height-m': 1.56,
		'letter-spacing-unit-m': 'px',
		'letter-spacing-m': '',
		'font-weight-m': '',
		'text-transform-m': '',
		'font-style-m': '',
		'text-decoration-m': '',
		'text-shadow-m': '',
		'vertical-align-m': '',
		'font-family-s': '',
		'font-options-s': {},
		'color-s': '',
		'text-align-s': '',
		'font-size-unit-s': 'px',
		'font-size-s': '',
		'line-height-unit-s': '',
		'line-height-s': '',
		'letter-spacing-unit-s': 'px',
		'letter-spacing-s': '',
		'font-weight-s': '',
		'text-transform-s': '',
		'font-style-s': '',
		'text-decoration-s': '',
		'text-shadow-s': '',
		'vertical-align-s': '',
		'font-family-xs': '',
		'font-options-xs': {},
		'color-xs': '',
		'text-align-xs': '',
		'font-size-unit-xs': 'px',
		'font-size-xs': '',
		'line-height-unit-xs': '',
		'line-height-xs': '',
		'letter-spacing-unit-xs': 'px',
		'letter-spacing-xs': '',
		'font-weight-xs': '',
		'text-transform-xs': '',
		'font-style-xs': '',
		'text-decoration-xs': '',
		'text-shadow-xs': '',
		'vertical-align-xs': '',
	},
};

export default defaultTypography;
