const defaultCustomFormat = {
	label: 'Typography',
	general: {
		'font-family': '',
		'font-options': {},
		color: '',
		'font-sizeUnit': 'px',
		'font-size': '',
		'line-heightUnit': '%',
		'line-height': '',
		'letter-spacingUnit': 'px',
		'letter-spacing': '',
		'font-weight': '',
		'text-transform': '',
		'font-style': '',
		'text-decoration': '',
		'text-shadow': '',
	},
	xxl: {
		'font-family': '',
		'font-options': {},
		color: '',
		'font-sizeUnit': 'px',
		'font-size': '',
		'line-heightUnit': '%',
		'line-height': '',
		'letter-spacingUnit': 'px',
		'letter-spacing': '',
		'font-weight': '',
		'text-transform': '',
		'font-style': '',
		'text-decoration': '',
		'text-shadow': '',
	},
	xl: {
		'font-family': '',
		'font-options': {},
		color: '',
		'font-sizeUnit': 'px',
		'font-size': '',
		'line-heightUnit': '%',
		'line-height': '',
		'letter-spacingUnit': 'px',
		'letter-spacing': '',
		'font-weight': '',
		'text-transform': '',
		'font-style': '',
		'text-decoration': '',
		'text-shadow': '',
	},
	l: {
		'font-family': '',
		'font-options': {},
		color: '',
		'font-sizeUnit': 'px',
		'font-size': '',
		'line-heightUnit': '%',
		'line-height': '',
		'letter-spacingUnit': 'px',
		'letter-spacing': '',
		'font-weight': '',
		'text-transform': '',
		'font-style': '',
		'text-decoration': '',
		'text-shadow': '',
	},
	m: {
		'font-family': '',
		'font-options': {},
		color: '',
		'font-sizeUnit': 'px',
		'font-size': '',
		'line-heightUnit': '%',
		'line-height': '',
		'letter-spacingUnit': 'px',
		'letter-spacing': '',
		'font-weight': '',
		'text-transform': '',
		'font-style': '',
		'text-decoration': '',
		'text-shadow': '',
	},
	s: {
		'font-family': '',
		'font-options': {},
		color: '',
		'font-sizeUnit': 'px',
		'font-size': '',
		'line-heightUnit': '%',
		'line-height': '',
		'letter-spacingUnit': 'px',
		'letter-spacing': '',
		'font-weight': '',
		'text-transform': '',
		'font-style': '',
		'text-decoration': '',
		'text-shadow': '',
	},
	xs: {
		'font-family': '',
		'font-options': {},
		color: '',
		'font-sizeUnit': 'px',
		'font-size': '',
		'line-heightUnit': '%',
		'line-height': '',
		'letter-spacingUnit': 'px',
		'letter-spacing': '',
		'font-weight': '',
		'text-transform': '',
		'font-style': '',
		'text-decoration': '',
		'text-shadow': '',
	},
	textAlign: {
		label: 'Alignment',
		general: {
			alignment: 'left',
		},
		xxl: {
			alignment: '',
		},
		xl: {
			alignment: '',
		},
		l: {
			alignment: '',
		},
		m: {
			alignment: '',
		},
		s: {
			alignment: '',
		},
		xs: {
			alignment: '',
		},
	},
};

export default defaultCustomFormat;
