export const alignment = {
	label: 'Alignment',
	general: {
		alignment: 'center',
	},
	xxl: {
		alignment: '',
	},
	xl: {
		alignment: '',
	},
	l: {
		alignment: '',
	},
	m: {
		alignment: '',
	},
	s: {
		alignment: '',
	},
	xs: {
		alignment: '',
	},
};

export const opacity = {
	label: 'Opacity',
	general: {
		opacity: 1,
	},
	xxl: {
		opacity: '',
	},
	xl: {
		opacity: '',
	},
	l: {
		opacity: '',
	},
	m: {
		opacity: '',
	},
	s: {
		opacity: '',
	},
	xs: {
		opacity: '',
	},
};

export const opacityHover = {
	label: 'Opacity',
	general: {
		opacity: 1,
	},
	xxl: {
		opacity: '',
	},
	xl: {
		opacity: '',
	},
	l: {
		opacity: '',
	},
	m: {
		opacity: '',
	},
	s: {
		opacity: '',
	},
	xs: {
		opacity: '',
	},
};

export const border = {
	label: 'Border',
	general: {
		'border-color': '#ffffff',
		'border-style': 'none',
	},
	xxl: {
		'border-color': '',
		'border-style': '',
	},
	xl: {
		'border-color': '',
		'border-style': '',
	},
	l: {
		'border-color': '',
		'border-style': '',
	},
	m: {
		'border-color': '',
		'border-style': '',
	},
	s: {
		'border-color': '',
		'border-style': '',
	},
	xs: {
		'border-color': '',
		'border-style': '',
	},
	borderWidth: {
		label: 'Border width',
		general: {
			'border-top-width': '',
			'border-right-width': '',
			'border-bottom-width': '',
			'border-left-width': '',
			sync: true,
			unit: 'px',
		},
		xxl: {
			'border-top-width': '',
			'border-right-width': '',
			'border-bottom-width': '',
			'border-left-width': '',
			sync: true,
			unit: '',
		},
		xl: {
			'border-top-width': '',
			'border-right-width': '',
			'border-bottom-width': '',
			'border-left-width': '',
			sync: true,
			unit: '',
		},
		l: {
			'border-top-width': '',
			'border-right-width': '',
			'border-bottom-width': '',
			'border-left-width': '',
			sync: true,
			unit: '',
		},
		m: {
			'border-top-width': '',
			'border-right-width': '',
			'border-bottom-width': '',
			'border-left-width': '',
			sync: true,
			unit: '',
		},
		s: {
			'border-top-width': '',
			'border-right-width': '',
			'border-bottom-width': '',
			'border-left-width': '',
			sync: true,
			unit: '',
		},
		xs: {
			'border-top-width': '',
			'border-right-width': '',
			'border-bottom-width': '',
			'border-left-width': '',
			sync: true,
			unit: '',
		},
	},
	borderRadius: {
		label: 'Border radius',
		general: {
			'border-top-left-radius': 0,
			'border-top-right-radius': 0,
			'border-bottom-right-radius': 0,
			'border-bottom-left-radius': 0,
			sync: true,
			unit: 'px',
		},
		xxl: {
			'border-top-left-radius': '',
			'border-top-right-radius': '',
			'border-bottom-right-radius': '',
			'border-bottom-left-radius': '',
			sync: true,
			unit: '',
		},
		xl: {
			'border-top-left-radius': '',
			'border-top-right-radius': '',
			'border-bottom-right-radius': '',
			'border-bottom-left-radius': '',
			sync: true,
			unit: '',
		},
		l: {
			'border-top-left-radius': '',
			'border-top-right-radius': '',
			'border-bottom-right-radius': '',
			'border-bottom-left-radius': '',
			sync: true,
			unit: '',
		},
		m: {
			'border-top-left-radius': '',
			'border-top-right-radius': '',
			'border-bottom-right-radius': '',
			'border-bottom-left-radius': '',
			sync: true,
			unit: '',
		},
		s: {
			'border-top-left-radius': '',
			'border-top-right-radius': '',
			'border-bottom-right-radius': '',
			'border-bottom-left-radius': '',
			sync: true,
			unit: '',
		},
		xs: {
			'border-top-left-radius': '',
			'border-top-right-radius': '',
			'border-bottom-right-radius': '',
			'border-bottom-left-radius': '',
			sync: true,
			unit: '',
		},
	},
};

export const borderHover = {
	label: 'Border',
	general: {
		'border-color': '',
		'border-style': '',
	},
	xxl: {
		'border-color': '',
		'border-style': '',
	},
	xl: {
		'border-color': '',
		'border-style': '',
	},
	l: {
		'border-color': '',
		'border-style': '',
	},
	m: {
		'border-color': '',
		'border-style': '',
	},
	s: {
		'border-color': '',
		'border-style': '',
	},
	xs: {
		'border-color': '',
		'border-style': '',
	},
	borderWidth: {
		label: 'Border width',
		general: {
			'border-top-width': '',
			'border-right-width': '',
			'border-bottom-width': '',
			'border-left-width': '',
			sync: true,
			unit: 'px',
		},
		xxl: {
			'border-top-width': '',
			'border-right-width': '',
			'border-bottom-width': '',
			'border-left-width': '',
			sync: true,
			unit: '',
		},
		xl: {
			'border-top-width': '',
			'border-right-width': '',
			'border-bottom-width': '',
			'border-left-width': '',
			sync: true,
			unit: '',
		},
		l: {
			'border-top-width': '',
			'border-right-width': '',
			'border-bottom-width': '',
			'border-left-width': '',
			sync: true,
			unit: '',
		},
		m: {
			'border-top-width': '',
			'border-right-width': '',
			'border-bottom-width': '',
			'border-left-width': '',
			sync: true,
			unit: '',
		},
		s: {
			'border-top-width': '',
			'border-right-width': '',
			'border-bottom-width': '',
			'border-left-width': '',
			sync: true,
			unit: '',
		},
		xs: {
			'border-top-width': '',
			'border-right-width': '',
			'border-bottom-width': '',
			'border-left-width': '',
			sync: true,
			unit: '',
		},
	},
	borderRadius: {
		label: 'Border radius',
		general: {
			'border-top-left-radius': '',
			'border-top-right-radius': '',
			'border-bottom-right-radius': '',
			'border-bottom-left-radius': '',
			sync: true,
			unit: 'px',
		},
		xxl: {
			'border-top-left-radius': '',
			'border-top-right-radius': '',
			'border-bottom-right-radius': '',
			'border-bottom-left-radius': '',
			sync: true,
			unit: '',
		},
		xl: {
			'border-top-left-radius': '',
			'border-top-right-radius': '',
			'border-bottom-right-radius': '',
			'border-bottom-left-radius': '',
			sync: true,
			unit: '',
		},
		l: {
			'border-top-left-radius': '',
			'border-top-right-radius': '',
			'border-bottom-right-radius': '',
			'border-bottom-left-radius': '',
			sync: true,
			unit: '',
		},
		m: {
			'border-top-left-radius': '',
			'border-top-right-radius': '',
			'border-bottom-right-radius': '',
			'border-bottom-left-radius': '',
			sync: true,
			unit: '',
		},
		s: {
			'border-top-left-radius': '',
			'border-top-right-radius': '',
			'border-bottom-right-radius': '',
			'border-bottom-left-radius': '',
			sync: true,
			unit: '',
		},
		xs: {
			'border-top-left-radius': '',
			'border-top-right-radius': '',
			'border-bottom-right-radius': '',
			'border-bottom-left-radius': '',
			sync: true,
			unit: '',
		},
	},
};

export const size = {
	label: 'Size',
	general: {
		'max-widthUnit': 'px',
		'max-width': '',
		widthUnit: 'px',
		width: '',
		'min-widthUnit': 'px',
		'min-width': '',
		'max-heightUnit': 'px',
		'max-height': '',
		heightUnit: 'px',
		height: '',
		'min-heightUnit': 'px',
		'min-height': '',
	},
	xxl: {
		'max-widthUnit': 'px',
		'max-width': '',
		widthUnit: 'px',
		width: '',
		'min-widthUnit': 'px',
		'min-width': '',
		'max-heightUnit': 'px',
		'max-height': '',
		heightUnit: 'px',
		height: '',
		'min-heightUnit': 'px',
		'min-height': '',
	},
	xl: {
		'max-widthUnit': 'px',
		'max-width': '',
		widthUnit: 'px',
		width: '',
		'min-widthUnit': 'px',
		'min-width': '',
		'max-heightUnit': 'px',
		'max-height': '',
		heightUnit: 'px',
		height: '',
		'min-heightUnit': 'px',
		'min-height': '',
	},
	l: {
		'max-widthUnit': 'px',
		'max-width': '',
		widthUnit: 'px',
		width: '',
		'min-widthUnit': 'px',
		'min-width': '',
		'max-heightUnit': 'px',
		'max-height': '',
		heightUnit: 'px',
		height: '',
		'min-heightUnit': 'px',
		'min-height': '',
	},
	m: {
		'max-widthUnit': 'px',
		'max-width': '',
		widthUnit: 'px',
		width: '',
		'min-widthUnit': 'px',
		'min-width': '',
		'max-heightUnit': 'px',
		'max-height': '',
		heightUnit: 'px',
		height: '',
		'min-heightUnit': 'px',
		'min-height': '',
	},
	s: {
		'max-widthUnit': 'px',
		'max-width': '',
		widthUnit: 'px',
		width: '',
		'min-widthUnit': 'px',
		'min-width': '',
		'max-heightUnit': 'px',
		'max-height': '',
		heightUnit: 'px',
		height: '',
		'min-heightUnit': 'px',
		'min-height': '',
	},
	xs: {
		'max-widthUnit': 'px',
		'max-width': '',
		widthUnit: 'px',
		width: '',
		'min-widthUnit': 'px',
		'min-width': '',
		'max-heightUnit': 'px',
		'max-height': '',
		heightUnit: 'px',
		height: '',
		'min-heightUnit': 'px',
		'min-height': '',
	},
};

export const background = {
	label: 'Background',
	activeMedia: '',
	imageOptions: [
		{
			imageData: {
				mediaID: '',
				mediaURL: '',
			},
			sizeSettings: {
				size: 'cover',
				widthUnit: '%',
				width: 100,
				heightUnit: '%',
				height: 100,
			},
			repeat: 'no-repeat',
			positionOptions: {
				position: 'center center',
				widthUnit: '%',
				width: 0,
				heightUnit: '%',
				height: 0,
			},
			origin: 'padding-box',
			clip: 'border-box',
			attachment: 'scroll',
		},
	],
	clipPathImage: '',
	videoOptions: {
		mediaID: '',
		mediaURL: '',
		width: 100,
		widthUnit: '%',
		height: 100,
		heightUnit: '%',
		fill: 'cover',
		position: 'unset',
		autoplay: 0,
		loop: 0,
		muted: 0,
		controls: 0,
		preload: 'metadata',
		clipPath: '',
	},
	colorOptions: {
		activeColor: '',
		color: '',
		gradient: '',
		gradientAboveBackground: false,
		clipPath: '',
	},
	overlayOptions: {
		overlay: '',
		activeColor: '',
		color: '',
		gradient: '',
		gradientAboveBackground: false,
		opacity: {
			label: 'Opacity',
			general: {
				opacity: 0.8,
			},
		},
	},
};

export const backgroundHover = {
	label: 'Background',
	activeMedia: '',
	imageOptions: [
		{
			imageData: {
				mediaID: '',
				mediaURL: '',
			},
			sizeSettings: {
				size: '',
				widthUnit: '',
				width: '',
				heightUnit: '',
				height: '',
			},
			repeat: '',
			positionOptions: {
				position: '',
				widthUnit: '',
				width: '',
				heightUnit: '',
				height: '',
			},
			origin: '',
			clip: '',
			attachment: '',
		},
	],
	clipPathImage: '',
	videoOptions: {
		mediaID: '',
		mediaURL: '',
		width: '',
		widthUnit: '',
		height: '',
		heightUnit: '',
		fill: '',
		position: '',
		autoplay: '',
		loop: '',
		muted: '',
		controls: '',
		preload: '',
		clipPath: '',
	},
	colorOptions: {
		activeColor: '',
		color: '',
		gradient: '',
		gradientAboveBackground: '',
		clipPath: '',
	},
	overlayOptions: {
		overlay: '',
		activeColor: '',
		color: '',
		gradient: '',
		gradientAboveBackground: false,
		opacity: {
			label: 'Opacity',
			general: {
				opacity: '',
			},
		},
	},
};

export const boxShadow = {
	label: 'Box Shadow',
	general: {
		shadowColor: '#ffffff',
		shadowHorizontal: 0,
		shadowVertical: 0,
		shadowBlur: 0,
		shadowSpread: 0,
	},
	xxl: {
		shadowColor: '',
		shadowHorizontal: '',
		shadowVertical: '',
		shadowBlur: '',
		shadowSpread: '',
	},
	xl: {
		shadowColor: '',
		shadowHorizontal: '',
		shadowVertical: '',
		shadowBlur: '',
		shadowSpread: '',
	},
	l: {
		shadowColor: '',
		shadowHorizontal: '',
		shadowVertical: '',
		shadowBlur: '',
		shadowSpread: '',
	},
	m: {
		shadowColor: '',
		shadowHorizontal: '',
		shadowVertical: '',
		shadowBlur: '',
		shadowSpread: '',
	},
	s: {
		shadowColor: '',
		shadowHorizontal: '',
		shadowVertical: '',
		shadowBlur: '',
		shadowSpread: '',
	},
	xs: {
		shadowColor: '',
		shadowHorizontal: '',
		shadowVertical: '',
		shadowBlur: '',
		shadowSpread: '',
	},
};

export const boxShadowHover = {
	label: 'Box Shadow',
	general: {
		shadowColor: '#',
		shadowHorizontal: '',
		shadowVertical: '',
		shadowBlur: '',
		shadowSpread: '',
	},
	xxl: {
		shadowColor: '',
		shadowHorizontal: '',
		shadowVertical: '',
		shadowBlur: '',
		shadowSpread: '',
	},
	xl: {
		shadowColor: '',
		shadowHorizontal: '',
		shadowVertical: '',
		shadowBlur: '',
		shadowSpread: '',
	},
	l: {
		shadowColor: '',
		shadowHorizontal: '',
		shadowVertical: '',
		shadowBlur: '',
		shadowSpread: '',
	},
	m: {
		shadowColor: '',
		shadowHorizontal: '',
		shadowVertical: '',
		shadowBlur: '',
		shadowSpread: '',
	},
	s: {
		shadowColor: '',
		shadowHorizontal: '',
		shadowVertical: '',
		shadowBlur: '',
		shadowSpread: '',
	},
	xs: {
		shadowColor: '',
		shadowHorizontal: '',
		shadowVertical: '',
		shadowBlur: '',
		shadowSpread: '',
	},
};

export const typography = {
	label: 'Typography',
	general: {
		'font-family': 'Roboto',
		'font-options': {
			100: 'http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1MmgWxPKTM1K9nz.ttf',
			'100italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOiCnqEu92Fr1Mu51QrIzcXLsnzjYk.ttf',
			300: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmSU5vAx05IsDqlA.ttf',
			'300italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TjARc9AMX6lJBP.ttf',
			400: 'http://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf',
			italic:
				'http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1Mu52xPKTM1K9nz.ttf',
			500: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmEU9vAx05IsDqlA.ttf',
			'500italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51S7ABc9AMX6lJBP.ttf',
			700: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlvAx05IsDqlA.ttf',
			'700italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TzBhc9AMX6lJBP.ttf',
			900: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmYUtvAx05IsDqlA.ttf',
			'900italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TLBBc9AMX6lJBP.ttf',
		},
		color: '#9b9b9b',
		'font-sizeUnit': 'px',
		'font-size': 16,
		'line-heightUnit': '%',
		'line-height': 150,
		'letter-spacingUnit': 'px',
		'letter-spacing': 0,
		'font-weight': 400,
		'text-transform': 'none',
		'font-style': 'normal',
		'text-decoration': 'none',
		'text-shadow': '',
	},
	xxl: {
		'font-family': '',
		'font-options': {},
		color: '',
		'text-align': '',
		'font-sizeUnit': 'px',
		'font-size': '',
		'line-heightUnit': '%',
		'line-height': '',
		'letter-spacingUnit': 'px',
		'letter-spacing': '',
		'font-weight': '',
		'text-transform': '',
		'font-style': '',
		'text-decoration': '',
		'text-shadow': '',
	},
	xl: {
		'font-family': '',
		'font-options': {},
		color: '',
		'font-sizeUnit': 'px',
		'font-size': '',
		'line-heightUnit': '%',
		'line-height': '',
		'letter-spacingUnit': 'px',
		'letter-spacing': '',
		'font-weight': '',
		'text-transform': '',
		'font-style': '',
		'text-decoration': '',
		'text-shadow': '',
	},
	l: {
		'font-family': '',
		'font-options': {},
		color: '',
		'font-sizeUnit': 'px',
		'font-size': '',
		'line-heightUnit': '%',
		'line-height': '',
		'letter-spacingUnit': 'px',
		'letter-spacing': '',
		'font-weight': '',
		'text-transform': '',
		'font-style': '',
		'text-decoration': '',
		'text-shadow': '',
	},
	m: {
		'font-family': '',
		'font-options': {},
		color: '',
		'font-sizeUnit': 'px',
		'font-size': '',
		'line-heightUnit': '%',
		'line-height': '',
		'letter-spacingUnit': 'px',
		'letter-spacing': '',
		'font-weight': '',
		'text-transform': '',
		'font-style': '',
		'text-decoration': '',
		'text-shadow': '',
	},
	s: {
		'font-family': '',
		'font-options': {},
		color: '',
		'font-sizeUnit': 'px',
		'font-size': '',
		'line-heightUnit': '%',
		'line-height': '',
		'letter-spacingUnit': 'px',
		'letter-spacing': '',
		'font-weight': '',
		'text-transform': '',
		'font-style': '',
		'text-decoration': '',
		'text-shadow': '',
	},
	xs: {
		'font-family': '',
		'font-options': {},
		color: '',
		'font-sizeUnit': 'px',
		'font-size': '',
		'line-heightUnit': '%',
		'line-height': '',
		'letter-spacingUnit': 'px',
		'letter-spacing': '',
		'font-weight': '',
		'text-transform': '',
		'font-style': '',
		'text-decoration': '',
		'text-shadow': '',
	},
	textAlign: {
		label: 'Alignment',
		general: {
			alignment: 'left',
		},
		xxl: {
			alignment: '',
		},
		xl: {
			alignment: '',
		},
		l: {
			alignment: '',
		},
		m: {
			alignment: '',
		},
		s: {
			alignment: '',
		},
		xs: {
			alignment: '',
		},
	},
};

export const typographyHover = {
	label: 'Typography',
	general: {
		'font-family': '',
		'font-options': '',
		color: '#',
		'font-sizeUnit': 'px',
		'font-size': '',
		'line-heightUnit': '%',
		'line-height': '',
		'letter-spacingUnit': 'px',
		'letter-spacing': '',
		'font-weight': '',
		'text-transform': '',
		'font-style': '',
		'text-decoration': '',
		'text-shadow': '',
	},
	xxl: {
		'font-family': '',
		'font-options': {},
		color: '',
		'text-align': '',
		'font-sizeUnit': 'px',
		'font-size': '',
		'line-heightUnit': '%',
		'line-height': '',
		'letter-spacingUnit': 'px',
		'letter-spacing': '',
		'font-weight': '',
		'text-transform': '',
		'font-style': '',
		'text-decoration': '',
		'text-shadow': '',
	},
	xl: {
		'font-family': '',
		'font-options': {},
		color: '',
		'font-sizeUnit': 'px',
		'font-size': '',
		'line-heightUnit': '%',
		'line-height': '',
		'letter-spacingUnit': 'px',
		'letter-spacing': '',
		'font-weight': '',
		'text-transform': '',
		'font-style': '',
		'text-decoration': '',
		'text-shadow': '',
	},
	l: {
		'font-family': '',
		'font-options': {},
		color: '',
		'font-sizeUnit': 'px',
		'font-size': '',
		'line-heightUnit': '%',
		'line-height': '',
		'letter-spacingUnit': 'px',
		'letter-spacing': '',
		'font-weight': '',
		'text-transform': '',
		'font-style': '',
		'text-decoration': '',
		'text-shadow': '',
	},
	m: {
		'font-family': '',
		'font-options': {},
		color: '',
		'font-sizeUnit': 'px',
		'font-size': '',
		'line-heightUnit': '%',
		'line-height': '',
		'letter-spacingUnit': 'px',
		'letter-spacing': '',
		'font-weight': '',
		'text-transform': '',
		'font-style': '',
		'text-decoration': '',
		'text-shadow': '',
	},
	s: {
		'font-family': '',
		'font-options': {},
		color: '',
		'font-sizeUnit': 'px',
		'font-size': '',
		'line-heightUnit': '%',
		'line-height': '',
		'letter-spacingUnit': 'px',
		'letter-spacing': '',
		'font-weight': '',
		'text-transform': '',
		'font-style': '',
		'text-decoration': '',
		'text-shadow': '',
	},
	xs: {
		'font-family': '',
		'font-options': {},
		color: '',
		'font-sizeUnit': 'px',
		'font-size': '',
		'line-heightUnit': '%',
		'line-height': '',
		'letter-spacingUnit': 'px',
		'letter-spacing': '',
		'font-weight': '',
		'text-transform': '',
		'font-style': '',
		'text-decoration': '',
		'text-shadow': '',
	},
	textAlign: {
		label: 'Alignment',
		general: {
			alignment: 'left',
		},
		xxl: {
			alignment: '',
		},
		xl: {
			alignment: '',
		},
		l: {
			alignment: '',
		},
		m: {
			alignment: '',
		},
		s: {
			alignment: '',
		},
		xs: {
			alignment: '',
		},
	},
};

export const margin = {
	label: 'Margin',
	general: {
		'margin-top': '',
		'margin-right': '',
		'margin-bottom': '',
		'margin-left': '',
		sync: true,
		unit: 'px',
	},
	xxl: {
		'margin-top': '',
		'margin-right': '',
		'margin-bottom': '',
		'margin-left': '',
		sync: true,
		unit: '',
	},
	xl: {
		'margin-top': '',
		'margin-right': '',
		'margin-bottom': '',
		'margin-left': '',
		sync: true,
		unit: '',
	},
	l: {
		'margin-top': '',
		'margin-right': '',
		'margin-bottom': '',
		'margin-left': '',
		sync: true,
		unit: '',
	},
	m: {
		'margin-top': '',
		'margin-right': '',
		'margin-bottom': '',
		'margin-left': '',
		sync: true,
		unit: '',
	},
	s: {
		'margin-top': '',
		'margin-right': '',
		'margin-bottom': '',
		'margin-left': '',
		sync: true,
		unit: '',
	},
	xs: {
		'margin-top': '',
		'margin-right': '',
		'margin-bottom': '',
		'margin-left': '',
		sync: true,
		unit: '',
	},
};

export const padding = {
	label: 'Padding',
	general: {
		'padding-top': '',
		'padding-right': '',
		'padding-bottom': '',
		'padding-left': '',
		sync: true,
		unit: 'px',
	},
	xxl: {
		'padding-top': '',
		'padding-right': '',
		'padding-bottom': '',
		'padding-left': '',
		sync: true,
		unit: '',
	},
	xl: {
		'padding-top': '',
		'padding-right': '',
		'padding-bottom': '',
		'padding-left': '',
		sync: true,
		unit: '',
	},
	l: {
		'padding-top': '',
		'padding-right': '',
		'padding-bottom': '',
		'padding-left': '',
		sync: true,
		unit: '',
	},
	m: {
		'padding-top': '',
		'padding-right': '',
		'padding-bottom': '',
		'padding-left': '',
		sync: true,
		unit: '',
	},
	s: {
		'padding-top': '',
		'padding-right': '',
		'padding-bottom': '',
		'padding-left': '',
		sync: true,
		unit: '',
	},
	xs: {
		'padding-top': '',
		'padding-right': '',
		'padding-bottom': '',
		'padding-left': '',
		sync: true,
		unit: '',
	},
};

export const cropOptions = {
	image: {
		source_url: '',
		width: '',
		height: '',
	},
	crop: {
		unit: '',
		x: 0,
		y: 0,
		width: 0,
		height: 0,
		scale: 100,
	},
};

export const __experimentalDivider = {
	label: 'Divider',
	general: {
		'border-color': '#ff4a17',
		'border-style': 'solid',
		widthUnit: '%',
		width: 100,
		heightUnit: '%',
		height: '',
		'border-top-widthUnit': 'px',
		'border-top-width': 2,
		'border-right-widthUnit': 'px',
		'border-right-width': '',
		'border-radius': '',
	},
	opacity: {
		label: 'Opacity',
		general: {
			opacity: 1,
		},
	},
};

export const __experimentalContainer = {
	label: 'Container size',
	general: {
		'max-widthUnit': 'px',
		'max-width': 1784,
		widthUnit: '%',
		width: 92.9,
	},
	xxl: {
		'max-widthUnit': 'px',
		'max-width': 1784,
		widthUnit: '%',
		width: 92.9,
	},
	xl: {
		'max-widthUnit': 'px',
		'max-width': 1784,
		widthUnit: '%',
		width: 92.9,
	},
	l: {
		'max-widthUnit': 'px',
		'max-width': 1170,
		widthUnit: '%',
		width: 85.65,
	},
	m: {
		'max-widthUnit': 'px',
		'max-width': 940,
		widthUnit: '%',
		width: 91.8,
	},
	s: {
		'max-widthUnit': 'px',
		'max-width': 720,
		widthUnit: '%',
		width: 93.75,
	},
	xs: {
		'max-widthUnit': 'px',
		'max-width': 426,
		widthUnit: '%',
		width: 88.75,
	},
};

export const __experimentalColumn = {
	label: 'Column size',
	general: {
		size: 90,
	},
	xxl: {
		size: '',
	},
	xl: {
		size: '',
	},
	l: {
		size: '',
	},
	m: {
		size: '',
	},
	s: {
		size: '',
	},
	xs: {
		size: '',
	},
};

export const __experimentalShapeDivider = {
	label: 'Shape Divider',
	top: {
		height: 100,
		heightUnit: 'px',
		opacity: {
			label: 'Opacity',
			general: {
				opacity: 1,
			},
		},
		shapeStyle: '',
		colorOptions: {
			color: '#000000',
			gradient: '',
			gradientAboveBackground: false,
		},
		effects: {
			status: 0,
		},
	},
	bottom: {
		height: 100,
		heightUnit: 'px',
		opacity: {
			label: 'Opacity',
			general: {
				opacity: 1,
			},
		},
		shapeStyle: '',
		colorOptions: {
			color: '#000000',
			gradient: '',
			gradientAboveBackground: false,
		},
		effects: {
			status: 0,
		},
	},
};

export const __experimentalPosition = {
	label: 'Position',
	general: {
		position: '',
	},
	xxl: {
		position: '',
	},
	xl: {
		position: '',
	},
	l: {
		position: '',
	},
	m: {
		position: '',
	},
	s: {
		position: '',
	},
	xs: {
		position: '',
	},
	options: {
		label: 'Position options',
		general: {
			top: '',
			right: '',
			bottom: '',
			left: '',
			sync: false,
			unit: 'px',
		},
		xxl: {
			top: '',
			right: '',
			bottom: '',
			left: '',
			sync: false,
			unit: '',
		},
		xl: {
			top: '',
			right: '',
			bottom: '',
			left: '',
			sync: false,
			unit: '',
		},
		l: {
			top: '',
			right: '',
			bottom: '',
			left: '',
			sync: false,
			unit: '',
		},
		m: {
			top: '',
			right: '',
			bottom: '',
			left: '',
			sync: false,
			unit: '',
		},
		s: {
			top: '',
			right: '',
			bottom: '',
			left: '',
			sync: false,
			unit: '',
		},
		xs: {
			top: '',
			right: '',
			bottom: '',
			left: '',
			sync: false,
			unit: '',
		},
	},
};

export const __experimentalDisplay = {
	label: 'Display block',
	general: {
		display: '',
	},
	xxl: {
		display: '',
	},
	xl: {
		display: '',
	},
	l: {
		display: '',
	},
	m: {
		display: '',
	},
	s: {
		display: '',
	},
	xs: {
		display: '',
	},
};

export const __experimentalHover = {
	label: 'Hover Effects',
	settings: {
		type: 'none',
		effectType: 'fade',
		duration: 1,
	},
	textPreset: 'center-center',
	borderStatus: 0,
	paddingStatus: 0,
	marginStatus: 0,
	border: { ...border },
	background: { ...background },
	margin: { ...margin },
	padding: { ...padding },
	titleTypography: {
		...typography,
		general: {
			...typography.general,
			'font-size': 33,
		},
	},
	contentTypography: {
		...typography,
		general: {
			...typography.general,
			'font-size': 18,
		},
	},
	titleStatus: 0,
	titleText: '',
	contentStatus: 0,
	contentText: '',
};

export const __experimentalMotion = {
	label: 'Motion Effects',
	vertical: {
		status: 0,
		direction: 'up',
		viewport: [0, 50, 100],
		amounts: [0, 100, 0],
		preset: '',
		presets: {
			preset_1: {
				viewport: [45, 50, 55],
				amounts: [0, 100, 0],
			},
			preset_2: {
				viewport: [35, 50, 65],
				amounts: [0, 150, 0],
			},
			preset_3: {
				viewport: [25, 50, 85],
				amounts: [0, 200, 0],
			},
			preset_4: {
				viewport: [15, 50, 95],
				amounts: [250, 0, 0],
			},
			preset_5: {
				viewport: [0, 50, 100],
				amounts: [300, 0, 0],
			},
			preset_6: {
				viewport: [45, 50, 55],
				amounts: [0, 100, 0],
			},
			preset_7: {
				viewport: [35, 50, 65],
				amounts: [0, 150, 0],
			},
			preset_8: {
				viewport: [25, 50, 85],
				amounts: [0, 200, 0],
			},
			preset_9: {
				viewport: [15, 50, 95],
				amounts: [250, 0, 0],
			},
			preset_10: {
				viewport: [0, 50, 100],
				amounts: [300, 0, 0],
			},
		},
	},
	horizontal: {
		status: 0,
		direction: 'left',
		viewport: [0, 50, 100],
		amounts: [0, 100, 0],
		preset: '',
		presets: {
			preset_1: {
				viewport: [45, 50, 55],
				amounts: [0, 100, 0],
			},
			preset_2: {
				viewport: [35, 50, 65],
				amounts: [0, 150, 0],
			},
			preset_3: {
				viewport: [25, 50, 85],
				amounts: [0, 200, 0],
			},
			preset_4: {
				viewport: [15, 50, 95],
				amounts: [300, 0, 0],
			},
			preset_5: {
				viewport: [0, 50, 100],
				amounts: [400, 0, 0],
			},
			preset_6: {
				viewport: [45, 50, 55],
				amounts: [0, 100, 0],
			},
			preset_7: {
				viewport: [35, 50, 65],
				amounts: [0, 150, 0],
			},
			preset_8: {
				viewport: [25, 50, 85],
				amounts: [0, 200, 0],
			},
			preset_9: {
				viewport: [15, 50, 95],
				amounts: [300, 0, 0],
			},
			preset_10: {
				viewport: [0, 50, 100],
				amounts: [400, 0, 0],
			},
		},
	},
	rotate: {
		status: 0,
		direction: 'left',
		viewport: [0, 50, 100],
		amounts: [0, 30, 0],
		preset: '',
		presets: {
			preset_1: {
				viewport: [30, 50, 55],
				amounts: [0, 30, 0],
			},
			preset_2: {
				viewport: [35, 50, 65],
				amounts: [0, 45, 0],
			},
			preset_3: {
				viewport: [25, 50, 85],
				amounts: [0, 60, 0],
			},
			preset_4: {
				viewport: [15, 50, 95],
				amounts: [90, 0, 0],
			},
			preset_5: {
				viewport: [0, 50, 100],
				amounts: [180, 0, 0],
			},
			preset_6: {
				viewport: [45, 50, 55],
				amounts: [0, 30, 0],
			},
			preset_7: {
				viewport: [35, 50, 65],
				amounts: [0, 45, 0],
			},
			preset_8: {
				viewport: [25, 50, 85],
				amounts: [0, 60, 0],
			},
			preset_9: {
				viewport: [15, 50, 95],
				amounts: [90, 0, 0],
			},
			preset_10: {
				viewport: [0, 50, 100],
				amounts: [180, 0, 0],
			},
		},
	},
	scale: {
		status: 0,
		direction: 'up',
		viewport: [0, 50, 100],
		amounts: ['', 0, ''],
		preset: '',
		presets: {
			preset_1: {
				viewport: [45, 50, 55],
				amounts: ['', 0, ''],
			},
			preset_2: {
				viewport: [35, 50, 65],
				amounts: ['', 2, ''],
			},
			preset_3: {
				viewport: [25, 50, 85],
				amounts: ['', 4, ''],
			},
			preset_4: {
				viewport: [15, 50, 95],
				amounts: [6, '', ''],
			},
			preset_5: {
				viewport: [0, 50, 100],
				amounts: [8, '', ''],
			},
			preset_6: {
				viewport: [45, 50, 55],
				amounts: ['', 0, ''],
			},
			preset_7: {
				viewport: [35, 50, 65],
				amounts: ['', 2, ''],
			},
			preset_8: {
				viewport: [25, 50, 85],
				amounts: ['', 4, ''],
			},
			preset_9: {
				viewport: [15, 50, 95],
				amounts: [6, '', ''],
			},
			preset_10: {
				viewport: [0, 50, 100],
				amounts: [8, '', ''],
			},
		},
	},
	fade: {
		status: 0,
		direction: 'in',
		viewport: [0, 50, 100],
		amounts: ['', 0, ''],
		preset: '',
		presets: {
			preset_1: {
				viewport: [45, 50, 55],
				amounts: ['', 0, ''],
			},
			preset_2: {
				viewport: [35, 50, 65],
				amounts: ['', 2, ''],
			},
			preset_3: {
				viewport: [25, 50, 85],
				amounts: ['', 4, ''],
			},
			preset_4: {
				viewport: [15, 50, 95],
				amounts: [5, '', ''],
			},
			preset_5: {
				viewport: [0, 50, 100],
				amounts: [6, '', ''],
			},
			preset_6: {
				viewport: [45, 50, 55],
				amounts: ['', 0, ''],
			},
			preset_7: {
				viewport: [35, 50, 65],
				amounts: ['', 2, ''],
			},
			preset_8: {
				viewport: [25, 50, 85],
				amounts: ['', 4, ''],
			},
			preset_9: {
				viewport: [15, 50, 95],
				amounts: [5, '', ''],
			},
			preset_10: {
				viewport: [0, 50, 100],
				amounts: [6, '', ''],
			},
		},
	},
	blur: {
		status: 0,
		direction: 'in',
		viewport: [0, 50, 100],
		amounts: ['', 2, ''],
		preset: '',
		presets: {
			preset_1: {
				viewport: [45, 50, 55],
				amounts: ['', 1, ''],
			},
			preset_2: {
				viewport: [35, 50, 65],
				amounts: ['', 2, ''],
			},
			preset_3: {
				viewport: [25, 50, 85],
				amounts: ['', 3, ''],
			},
			preset_4: {
				viewport: [15, 50, 95],
				amounts: [4, '', ''],
			},
			preset_5: {
				viewport: [0, 50, 100],
				amounts: [8, '', ''],
			},
			preset_6: {
				viewport: [45, 50, 55],
				amounts: ['', 1, ''],
			},
			preset_7: {
				viewport: [35, 50, 65],
				amounts: ['', 2, ''],
			},
			preset_8: {
				viewport: [25, 50, 85],
				amounts: ['', 3, ''],
			},
			preset_9: {
				viewport: [15, 50, 95],
				amounts: [4, '', ''],
			},
			preset_10: {
				viewport: [0, 50, 100],
				amounts: [8, '', ''],
			},
		},
	},
	entrance: {
		type: '',
		duration: 1,
		delay: 1,
	},
	parallax: {
		status: 0,
		speed: 2,
		direction: 'up',
	},
};

export const __experimentalArrow = {
	label: 'Arrow',
	active: 0,
	general: {
		active: 0,
		side: 'bottom',
		position: 50,
		color: '#ffffff',
		widthUnit: 'px',
		width: 80,
		border: '',
	},
	xxl: {
		side: '',
		position: '',
		color: '',
		widthUnit: '',
		width: '',
		border: '',
	},
	xl: {
		side: '',
		position: '',
		color: '',
		widthUnit: '',
		height: '',
		border: '',
	},
	l: {
		side: '',
		position: '',
		color: '',
		widthUnit: '',
		height: '',
		border: '',
	},
	m: {
		side: '',
		position: '',
		color: '',
		widthUnit: '',
		height: '',
		border: '',
	},
	s: {
		side: '',
		position: '',
		color: '',
		widthUnit: '',
		height: '',
		border: '',
	},
	xs: {
		side: '',
		position: '',
		color: '',
		widthUnit: '',
		height: '',
		border: '',
	},
};

export const __experimentalTransform = {
	label: 'Transform',
	general: {
		scaleX: '',
		scaleY: '',
		translateXUnit: '%',
		translateX: '',
		translateYUnit: '%',
		translateY: '',
		rotateX: '',
		rotateY: '',
		rotateZ: '',
		originX: 'center',
		originY: 'center',
	},
	xxl: {
		scaleX: '',
		scaleY: '',
		translateXUnit: '%',
		translateX: '',
		translateYUnit: '%',
		translateY: '',
		rotateX: '',
		rotateY: '',
		rotateZ: '',
		originX: '',
		originY: '',
	},
	xl: {
		scaleX: '',
		scaleY: '',
		translateXUnit: '%',
		translateX: '',
		translateYUnit: '%',
		translateY: '',
		rotateX: '',
		rotateY: '',
		rotateZ: '',
		originX: '',
		originY: '',
	},
	l: {
		scaleX: '',
		scaleY: '',
		translateXUnit: '%',
		translateX: '',
		translateYUnit: '%',
		translateY: '',
		rotateX: '',
		rotateY: '',
		rotateZ: '',
		originX: '',
		originY: '',
	},
	m: {
		scaleX: '',
		scaleY: '',
		translateXUnit: '%',
		translateX: '',
		translateYUnit: '%',
		translateY: '',
		rotateX: '',
		rotateY: '',
		rotateZ: '',
		originX: '',
		originY: '',
	},
	s: {
		scaleX: '',
		scaleY: '',
		translateXUnit: '%',
		translateX: '',
		translateYUnit: '%',
		translateY: '',
		rotateX: '',
		rotateY: '',
		rotateZ: '',
		originX: '',
		originY: '',
	},
	xs: {
		scaleX: '',
		scaleY: '',
		translateXUnit: '%',
		translateX: '',
		translateYUnit: '%',
		translateY: '',
		rotateX: '',
		rotateY: '',
		rotateZ: '',
		originX: '',
		originY: '',
	},
};
