export const alignment = {
	label: 'Alignment',
	general: {
		alignment: 'center',
	},
	xxl: {
		alignment: '',
	},
	xl: {
		alignment: '',
	},
	l: {
		alignment: '',
	},
	m: {
		alignment: '',
	},
	s: {
		alignment: '',
	},
	xs: {
		alignment: '',
	},
};

export const opacity = {
	label: 'Opacity',
	general: {
		opacity: 1,
	},
	xxl: {
		opacity: '',
	},
	xl: {
		opacity: '',
	},
	l: {
		opacity: '',
	},
	m: {
		opacity: '',
	},
	s: {
		opacity: '',
	},
	xs: {
		opacity: '',
	},
};

export const border = {
	label: 'Border',
	general: {
		'border-color': '#ffffff',
		'border-style': 'none',
	},
	xxl: {
		'border-color': '',
		'border-style': '',
	},
	xl: {
		'border-color': '',
		'border-style': '',
	},
	l: {
		'border-color': '',
		'border-style': '',
	},
	m: {
		'border-color': '',
		'border-style': '',
	},
	s: {
		'border-color': '',
		'border-style': '',
	},
	xs: {
		'border-color': '',
		'border-style': '',
	},
	borderWidth: {
		label: 'Border width',
		general: {
			'border-top-width': '',
			'border-right-width': '',
			'border-bottom-width': '',
			'border-left-width': '',
			sync: true,
			unit: 'px',
		},
		xxl: {
			'border-top-width': '',
			'border-right-width': '',
			'border-bottom-width': '',
			'border-left-width': '',
			sync: true,
			unit: '',
		},
		xl: {
			'border-top-width': '',
			'border-right-width': '',
			'border-bottom-width': '',
			'border-left-width': '',
			sync: true,
			unit: '',
		},
		l: {
			'border-top-width': '',
			'border-right-width': '',
			'border-bottom-width': '',
			'border-left-width': '',
			sync: true,
			unit: '',
		},
		m: {
			'border-top-width': '',
			'border-right-width': '',
			'border-bottom-width': '',
			'border-left-width': '',
			sync: true,
			unit: '',
		},
		s: {
			'border-top-width': '',
			'border-right-width': '',
			'border-bottom-width': '',
			'border-left-width': '',
			sync: true,
			unit: '',
		},
		xs: {
			'border-top-width': '',
			'border-right-width': '',
			'border-bottom-width': '',
			'border-left-width': '',
			sync: true,
			unit: '',
		},
	},
	borderRadius: {
		label: 'Border radius',
		general: {
			'border-top-left-radius': 0,
			'border-top-right-radius': 0,
			'border-bottom-right-radius': 0,
			'border-bottom-left-radius': 0,
			sync: true,
			unit: 'px',
		},
		xxl: {
			'border-top-left-radius': '',
			'border-top-right-radius': '',
			'border-bottom-right-radius': '',
			'border-bottom-left-radius': '',
			sync: true,
			unit: '',
		},
		xl: {
			'border-top-left-radius': '',
			'border-top-right-radius': '',
			'border-bottom-right-radius': '',
			'border-bottom-left-radius': '',
			sync: true,
			unit: '',
		},
		l: {
			'border-top-left-radius': '',
			'border-top-right-radius': '',
			'border-bottom-right-radius': '',
			'border-bottom-left-radius': '',
			sync: true,
			unit: '',
		},
		m: {
			'border-top-left-radius': '',
			'border-top-right-radius': '',
			'border-bottom-right-radius': '',
			'border-bottom-left-radius': '',
			sync: true,
			unit: '',
		},
		s: {
			'border-top-left-radius': '',
			'border-top-right-radius': '',
			'border-bottom-right-radius': '',
			'border-bottom-left-radius': '',
			sync: true,
			unit: '',
		},
		xs: {
			'border-top-left-radius': '',
			'border-top-right-radius': '',
			'border-bottom-right-radius': '',
			'border-bottom-left-radius': '',
			sync: true,
			unit: '',
		},
	},
};

export const borderHover = {
	label: 'Border',
	status: 0,
	general: {
		'border-color': '',
		'border-style': '',
	},
	xxl: {
		'border-color': '',
		'border-style': '',
	},
	xl: {
		'border-color': '',
		'border-style': '',
	},
	l: {
		'border-color': '',
		'border-style': '',
	},
	m: {
		'border-color': '',
		'border-style': '',
	},
	s: {
		'border-color': '',
		'border-style': '',
	},
	xs: {
		'border-color': '',
		'border-style': '',
	},
	borderWidth: {
		label: 'Border width',
		general: {
			'border-top-width': '',
			'border-right-width': '',
			'border-bottom-width': '',
			'border-left-width': '',
			sync: true,
			unit: 'px',
		},
		xxl: {
			'border-top-width': '',
			'border-right-width': '',
			'border-bottom-width': '',
			'border-left-width': '',
			sync: true,
			unit: '',
		},
		xl: {
			'border-top-width': '',
			'border-right-width': '',
			'border-bottom-width': '',
			'border-left-width': '',
			sync: true,
			unit: '',
		},
		l: {
			'border-top-width': '',
			'border-right-width': '',
			'border-bottom-width': '',
			'border-left-width': '',
			sync: true,
			unit: '',
		},
		m: {
			'border-top-width': '',
			'border-right-width': '',
			'border-bottom-width': '',
			'border-left-width': '',
			sync: true,
			unit: '',
		},
		s: {
			'border-top-width': '',
			'border-right-width': '',
			'border-bottom-width': '',
			'border-left-width': '',
			sync: true,
			unit: '',
		},
		xs: {
			'border-top-width': '',
			'border-right-width': '',
			'border-bottom-width': '',
			'border-left-width': '',
			sync: true,
			unit: '',
		},
	},
	borderRadius: {
		label: 'Border radius',
		general: {
			'border-top-left-radius': '',
			'border-top-right-radius': '',
			'border-bottom-right-radius': '',
			'border-bottom-left-radius': '',
			sync: true,
			unit: 'px',
		},
		xxl: {
			'border-top-left-radius': '',
			'border-top-right-radius': '',
			'border-bottom-right-radius': '',
			'border-bottom-left-radius': '',
			sync: true,
			unit: '',
		},
		xl: {
			'border-top-left-radius': '',
			'border-top-right-radius': '',
			'border-bottom-right-radius': '',
			'border-bottom-left-radius': '',
			sync: true,
			unit: '',
		},
		l: {
			'border-top-left-radius': '',
			'border-top-right-radius': '',
			'border-bottom-right-radius': '',
			'border-bottom-left-radius': '',
			sync: true,
			unit: '',
		},
		m: {
			'border-top-left-radius': '',
			'border-top-right-radius': '',
			'border-bottom-right-radius': '',
			'border-bottom-left-radius': '',
			sync: true,
			unit: '',
		},
		s: {
			'border-top-left-radius': '',
			'border-top-right-radius': '',
			'border-bottom-right-radius': '',
			'border-bottom-left-radius': '',
			sync: true,
			unit: '',
		},
		xs: {
			'border-top-left-radius': '',
			'border-top-right-radius': '',
			'border-bottom-right-radius': '',
			'border-bottom-left-radius': '',
			sync: true,
			unit: '',
		},
	},
};

export const size = {
	label: 'Size',
	advancedOptions: 0,
	general: {
		'max-widthUnit': 'px',
		'max-width': '',
		widthUnit: 'px',
		width: '',
		'min-widthUnit': 'px',
		'min-width': '',
		'max-heightUnit': 'px',
		'max-height': '',
		heightUnit: 'px',
		height: '',
		'min-heightUnit': 'px',
		'min-height': '',
	},
	xxl: {
		'max-widthUnit': 'px',
		'max-width': '',
		widthUnit: 'px',
		width: '',
		'min-widthUnit': 'px',
		'min-width': '',
		'max-heightUnit': 'px',
		'max-height': '',
		heightUnit: 'px',
		height: '',
		'min-heightUnit': 'px',
		'min-height': '',
	},
	xl: {
		'max-widthUnit': 'px',
		'max-width': '',
		widthUnit: 'px',
		width: '',
		'min-widthUnit': 'px',
		'min-width': '',
		'max-heightUnit': 'px',
		'max-height': '',
		heightUnit: 'px',
		height: '',
		'min-heightUnit': 'px',
		'min-height': '',
	},
	l: {
		'max-widthUnit': 'px',
		'max-width': '',
		widthUnit: 'px',
		width: '',
		'min-widthUnit': 'px',
		'min-width': '',
		'max-heightUnit': 'px',
		'max-height': '',
		heightUnit: 'px',
		height: '',
		'min-heightUnit': 'px',
		'min-height': '',
	},
	m: {
		'max-widthUnit': 'px',
		'max-width': '',
		widthUnit: 'px',
		width: '',
		'min-widthUnit': 'px',
		'min-width': '',
		'max-heightUnit': 'px',
		'max-height': '',
		heightUnit: 'px',
		height: '',
		'min-heightUnit': 'px',
		'min-height': '',
	},
	s: {
		'max-widthUnit': 'px',
		'max-width': '',
		widthUnit: 'px',
		width: '',
		'min-widthUnit': 'px',
		'min-width': '',
		'max-heightUnit': 'px',
		'max-height': '',
		heightUnit: 'px',
		height: '',
		'min-heightUnit': 'px',
		'min-height': '',
	},
	xs: {
		'max-widthUnit': 'px',
		'max-width': '',
		widthUnit: 'px',
		width: '',
		'min-widthUnit': 'px',
		'min-width': '',
		'max-heightUnit': 'px',
		'max-height': '',
		heightUnit: 'px',
		height: '',
		'min-heightUnit': 'px',
		'min-height': '',
	},
};

export const background = {
	label: 'Background',
	activeMedia: '',
	layersOptions: {
		status: 0,
		layers: [],
	},
	colorOptions: {
		activeColor: '',
		color: '',
		gradient: '',
		gradientAboveBackground: false,
		clipPath: '',
		gradientOpacity: {
			opacity: {
				label: 'Opacity',
				general: {
					opacity: 1,
				},
			},
		},
	},
	imageOptions: {
		items: [
			{
				imageData: {
					mediaID: '',
					mediaURL: '',
					width: 100,
					widthUnit: '%',
					height: 100,
					heightUnit: '%',
					cropOptions: {
						image: {
							source_url: '',
							width: '',
							height: '',
						},
						crop: {
							unit: '',
							x: 0,
							y: 0,
							width: 0,
							height: 0,
							scale: 100,
						},
					},
				},
				sizeSettings: {
					size: '',
					widthUnit: '',
					width: '',
					heightUnit: '',
					height: '',
				},
				repeat: 'no-repeat',
				positionOptions: {
					position: 'center center',
					widthUnit: '%',
					width: 0,
					heightUnit: '%',
					height: 0,
				},
				origin: 'padding-box',
				clip: 'border-box',
				attachment: 'scroll',
			},
		],
		clipPath: '',
		opacity: {
			label: 'Opacity',
			general: {
				opacity: 1,
			},
		},
	},
	videoOptions: {
		mediaID: '',
		mediaURL: '',
		startTime: '',
		endTime: '',
		loop: 0,
		clipPath: '',
		fallbackID: '',
		fallbackURL: '',
		playOnMobile: 0,
		opacity: {
			label: 'Opacity',
			general: {
				opacity: 1,
			},
		},
	},
	SVGOptions: {
		SVGCurrentElement: '',
		SVGElement: '',
		SVGData: '{}',
		SVGMediaID: '',
		SVGMediaURL: '',
		position: {
			label: 'Background SVG position',
			general: {
				topUnit: '%',
				top: '',
				leftUnit: '%',
				left: '',
			},
		},
		size: '',
	},
};

export const backgroundHover = {
	label: 'Background Hover',
	activeMedia: '',
	layersOptions: {
		status: 0,
		layers: [],
	},
	status: 0,
	colorOptions: {
		activeColor: '',
		color: '',
		gradient: '',
		gradientAboveBackground: '',
		clipPath: '',
		gradientOpacity: {
			opacity: {
				label: 'Opacity',
				general: {
					opacity: 1,
				},
			},
		},
	},
	imageOptions: {
		items: [
			{
				imageData: {
					mediaID: '',
					mediaURL: '',
				},
				sizeSettings: {
					size: '',
					widthUnit: '',
					width: '',
					heightUnit: '',
					height: '',
				},
				repeat: '',
				positionOptions: {
					position: '',
					widthUnit: '',
					width: '',
					heightUnit: '',
					height: '',
				},
				origin: '',
				clip: '',
				attachment: '',
			},
		],
		clipPath: '',
		opacity: {
			label: 'Opacity',
			general: {
				opacity: 1,
			},
		},
	},
	videoOptions: {
		mediaID: '',
		mediaURL: '',
		startTime: '',
		endTime: '',
		loop: '',
		muted: '',
		clipPath: '',
		opacity: {
			label: 'Opacity',
			general: {
				opacity: 1,
			},
		},
		fallbackID: '',
		fallbackURL: '',
		playOnMobile: 0,
	},
	SVGOptions: {
		SVGElement: '',
		SVGData: '{}',
		SVGMediaID: '',
		SVGMediaURL: '',
		position: {
			label: 'Background SVG position',
			general: {
				topUnit: '%',
				top: '',
				leftUnit: '%',
				left: '',
			},
		},
		size: '',
	},
};

export const boxShadow = {
	label: 'Box Shadow',
	general: {
		shadowColor: '#ffffff',
		shadowHorizontal: '',
		shadowVertical: '',
		shadowBlur: '',
		shadowSpread: '',
	},
	xxl: {
		shadowColor: '',
		shadowHorizontal: '',
		shadowVertical: '',
		shadowBlur: '',
		shadowSpread: '',
	},
	xl: {
		shadowColor: '',
		shadowHorizontal: '',
		shadowVertical: '',
		shadowBlur: '',
		shadowSpread: '',
	},
	l: {
		shadowColor: '',
		shadowHorizontal: '',
		shadowVertical: '',
		shadowBlur: '',
		shadowSpread: '',
	},
	m: {
		shadowColor: '',
		shadowHorizontal: '',
		shadowVertical: '',
		shadowBlur: '',
		shadowSpread: '',
	},
	s: {
		shadowColor: '',
		shadowHorizontal: '',
		shadowVertical: '',
		shadowBlur: '',
		shadowSpread: '',
	},
	xs: {
		shadowColor: '',
		shadowHorizontal: '',
		shadowVertical: '',
		shadowBlur: '',
		shadowSpread: '',
	},
};

export const boxShadowHover = {
	label: 'Box Shadow',
	status: 0,
	general: {
		shadowColor: '#',
		shadowHorizontal: '',
		shadowVertical: '',
		shadowBlur: '',
		shadowSpread: '',
	},
	xxl: {
		shadowColor: '',
		shadowHorizontal: '',
		shadowVertical: '',
		shadowBlur: '',
		shadowSpread: '',
	},
	xl: {
		shadowColor: '',
		shadowHorizontal: '',
		shadowVertical: '',
		shadowBlur: '',
		shadowSpread: '',
	},
	l: {
		shadowColor: '',
		shadowHorizontal: '',
		shadowVertical: '',
		shadowBlur: '',
		shadowSpread: '',
	},
	m: {
		shadowColor: '',
		shadowHorizontal: '',
		shadowVertical: '',
		shadowBlur: '',
		shadowSpread: '',
	},
	s: {
		shadowColor: '',
		shadowHorizontal: '',
		shadowVertical: '',
		shadowBlur: '',
		shadowSpread: '',
	},
	xs: {
		shadowColor: '',
		shadowHorizontal: '',
		shadowVertical: '',
		shadowBlur: '',
		shadowSpread: '',
	},
};

export const typography = {
	label: 'Typography',
	general: {
		'font-family': 'Roboto',
		'font-options': {
			100: 'http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1MmgWxPKTM1K9nz.ttf',
			'100italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOiCnqEu92Fr1Mu51QrIzcXLsnzjYk.ttf',
			300: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmSU5vAx05IsDqlA.ttf',
			'300italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TjARc9AMX6lJBP.ttf',
			400: 'http://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf',
			italic:
				'http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1Mu52xPKTM1K9nz.ttf',
			500: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmEU9vAx05IsDqlA.ttf',
			'500italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51S7ABc9AMX6lJBP.ttf',
			700: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlvAx05IsDqlA.ttf',
			'700italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TzBhc9AMX6lJBP.ttf',
			900: 'http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmYUtvAx05IsDqlA.ttf',
			'900italic':
				'http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TLBBc9AMX6lJBP.ttf',
		},
		color: '#9b9b9b',
		'font-sizeUnit': 'px',
		'font-size': 16,
		'line-heightUnit': '',
		'line-height': 1.625,
		'letter-spacingUnit': 'px',
		'letter-spacing': 0,
		'font-weight': 400,
		'text-transform': 'none',
		'font-style': 'normal',
		'text-decoration': 'none',
		'text-shadow': '',
		'vertical-align': '',
	},
	xxl: {
		'font-family': '',
		'font-options': {},
		color: '',
		'text-align': '',
		'font-sizeUnit': 'px',
		'font-size': 20,
		'line-heightUnit': '',
		'line-height': 1.5,
		'letter-spacingUnit': 'px',
		'letter-spacing': '',
		'font-weight': '',
		'text-transform': '',
		'font-style': '',
		'text-decoration': '',
		'text-shadow': '',
		'vertical-align': '',
	},
	xl: {
		'font-family': '',
		'font-options': {},
		color: '',
		'font-sizeUnit': 'px',
		'font-size': 18,
		'line-heightUnit': '',
		'line-height': 1.35,
		'letter-spacingUnit': 'px',
		'letter-spacing': '',
		'font-weight': '',
		'text-transform': '',
		'font-style': '',
		'text-decoration': '',
		'text-shadow': '',
		'vertical-align': '',
	},
	l: {
		'font-family': '',
		'font-options': {},
		color: '',
		'font-sizeUnit': 'px',
		'font-size': 16,
		'line-heightUnit': '',
		'line-height': 1.625,
		'letter-spacingUnit': 'px',
		'letter-spacing': '',
		'font-weight': '',
		'text-transform': '',
		'font-style': '',
		'text-decoration': '',
		'text-shadow': '',
		'vertical-align': '',
	},
	m: {
		'font-family': '',
		'font-options': {},
		color: '',
		'font-sizeUnit': 'px',
		'font-size': '',
		'line-heightUnit': '',
		'line-height': '',
		'letter-spacingUnit': 'px',
		'letter-spacing': '',
		'font-weight': '',
		'text-transform': '',
		'font-style': '',
		'text-decoration': '',
		'text-shadow': '',
		'vertical-align': '',
	},
	s: {
		'font-family': '',
		'font-options': {},
		color: '',
		'font-sizeUnit': 'px',
		'font-size': '',
		'line-heightUnit': '',
		'line-height': '',
		'letter-spacingUnit': 'px',
		'letter-spacing': '',
		'font-weight': '',
		'text-transform': '',
		'font-style': '',
		'text-decoration': '',
		'text-shadow': '',
		'vertical-align': '',
	},
	xs: {
		'font-family': '',
		'font-options': {},
		color: '',
		'font-sizeUnit': 'px',
		'font-size': '',
		'line-heightUnit': '',
		'line-height': '',
		'letter-spacingUnit': 'px',
		'letter-spacing': '',
		'font-weight': '',
		'text-transform': '',
		'font-style': '',
		'text-decoration': '',
		'text-shadow': '',
		'vertical-align': '',
	},
	textAlign: {
		label: 'Alignment',
		general: {
			alignment: 'left',
		},
		xxl: {
			alignment: '',
		},
		xl: {
			alignment: '',
		},
		l: {
			alignment: '',
		},
		m: {
			alignment: '',
		},
		s: {
			alignment: '',
		},
		xs: {
			alignment: '',
		},
	},
	customFormats: {},
};

export const typographyHover = {
	label: 'Typography',
	status: 0,
	general: {
		'font-family': '',
		'font-options': '',
		color: '#',
		'font-sizeUnit': 'px',
		'font-size': '',
		'line-heightUnit': '',
		'line-height': '',
		'letter-spacingUnit': 'px',
		'letter-spacing': '',
		'font-weight': '',
		'text-transform': '',
		'font-style': '',
		'text-decoration': '',
		'text-shadow': '',
		'vertical-align': '',
	},
	xxl: {
		'font-family': '',
		'font-options': {},
		color: '',
		'text-align': '',
		'font-sizeUnit': 'px',
		'font-size': '',
		'line-heightUnit': '',
		'line-height': '',
		'letter-spacingUnit': 'px',
		'letter-spacing': '',
		'font-weight': '',
		'text-transform': '',
		'font-style': '',
		'text-decoration': '',
		'text-shadow': '',
		'vertical-align': '',
	},
	xl: {
		'font-family': '',
		'font-options': {},
		color: '',
		'font-sizeUnit': 'px',
		'font-size': '',
		'line-heightUnit': '',
		'line-height': '',
		'letter-spacingUnit': 'px',
		'letter-spacing': '',
		'font-weight': '',
		'text-transform': '',
		'font-style': '',
		'text-decoration': '',
		'text-shadow': '',
		'vertical-align': '',
	},
	l: {
		'font-family': '',
		'font-options': {},
		color: '',
		'font-sizeUnit': 'px',
		'font-size': '',
		'line-heightUnit': '',
		'line-height': '',
		'letter-spacingUnit': 'px',
		'letter-spacing': '',
		'font-weight': '',
		'text-transform': '',
		'font-style': '',
		'text-decoration': '',
		'text-shadow': '',
		'vertical-align': '',
	},
	m: {
		'font-family': '',
		'font-options': {},
		color: '',
		'font-sizeUnit': 'px',
		'font-size': '',
		'line-heightUnit': '',
		'line-height': '',
		'letter-spacingUnit': 'px',
		'letter-spacing': '',
		'font-weight': '',
		'text-transform': '',
		'font-style': '',
		'text-decoration': '',
		'text-shadow': '',
		'vertical-align': '',
	},
	s: {
		'font-family': '',
		'font-options': {},
		color: '',
		'font-sizeUnit': 'px',
		'font-size': '',
		'line-heightUnit': '',
		'line-height': '',
		'letter-spacingUnit': 'px',
		'letter-spacing': '',
		'font-weight': '',
		'text-transform': '',
		'font-style': '',
		'text-decoration': '',
		'text-shadow': '',
		'vertical-align': '',
	},
	xs: {
		'font-family': '',
		'font-options': {},
		color: '',
		'font-sizeUnit': 'px',
		'font-size': '',
		'line-heightUnit': '',
		'line-height': '',
		'letter-spacingUnit': 'px',
		'letter-spacing': '',
		'font-weight': '',
		'text-transform': '',
		'font-style': '',
		'text-decoration': '',
		'text-shadow': '',
		'vertical-align': '',
	},
	textAlign: {
		label: 'Alignment',
		general: {
			alignment: 'left',
		},
		xxl: {
			alignment: '',
		},
		xl: {
			alignment: '',
		},
		l: {
			alignment: '',
		},
		m: {
			alignment: '',
		},
		s: {
			alignment: '',
		},
		xs: {
			alignment: '',
		},
	},
	customFormats: {},
};

export const margin = {
	label: 'Margin',
	general: {
		'margin-top': 0,
		'margin-right': 0,
		'margin-bottom': 0,
		'margin-left': 0,
		sync: true,
		unit: 'px',
	},
	xxl: {
		'margin-top': '',
		'margin-right': '',
		'margin-bottom': '',
		'margin-left': '',
		sync: true,
		unit: '',
	},
	xl: {
		'margin-top': '',
		'margin-right': '',
		'margin-bottom': '',
		'margin-left': '',
		sync: true,
		unit: '',
	},
	l: {
		'margin-top': '',
		'margin-right': '',
		'margin-bottom': '',
		'margin-left': '',
		sync: true,
		unit: '',
	},
	m: {
		'margin-top': '',
		'margin-right': '',
		'margin-bottom': '',
		'margin-left': '',
		sync: true,
		unit: '',
	},
	s: {
		'margin-top': '',
		'margin-right': '',
		'margin-bottom': '',
		'margin-left': '',
		sync: true,
		unit: '',
	},
	xs: {
		'margin-top': '',
		'margin-right': '',
		'margin-bottom': '',
		'margin-left': '',
		sync: true,
		unit: '',
	},
};

export const padding = {
	label: 'Padding',
	general: {
		'padding-top': 0,
		'padding-right': 0,
		'padding-bottom': 0,
		'padding-left': 0,
		sync: true,
		unit: 'px',
	},
	xxl: {
		'padding-top': '',
		'padding-right': '',
		'padding-bottom': '',
		'padding-left': '',
		sync: true,
		unit: '',
	},
	xl: {
		'padding-top': '',
		'padding-right': '',
		'padding-bottom': '',
		'padding-left': '',
		sync: true,
		unit: '',
	},
	l: {
		'padding-top': '',
		'padding-right': '',
		'padding-bottom': '',
		'padding-left': '',
		sync: true,
		unit: '',
	},
	m: {
		'padding-top': '',
		'padding-right': '',
		'padding-bottom': '',
		'padding-left': '',
		sync: true,
		unit: '',
	},
	s: {
		'padding-top': '',
		'padding-right': '',
		'padding-bottom': '',
		'padding-left': '',
		sync: true,
		unit: '',
	},
	xs: {
		'padding-top': '',
		'padding-right': '',
		'padding-bottom': '',
		'padding-left': '',
		sync: true,
		unit: '',
	},
};

export const cropOptions = {
	image: {
		source_url: '',
		width: '',
		height: '',
	},
	crop: {
		unit: '',
		x: 0,
		y: 0,
		width: 0,
		height: 0,
		scale: 100,
	},
};

export const divider = {
	label: 'Divider',
	general: {
		'border-color': '#ff4a17',
		'border-style': 'solid',
		widthUnit: '%',
		width: 100,
		heightUnit: '%',
		height: '',
		'border-top-widthUnit': 'px',
		'border-top-width': 2,
		'border-right-widthUnit': 'px',
		'border-right-width': '',
		'border-radius': '',
	},
	opacity: {
		label: 'Opacity',
		general: {
			opacity: 1,
		},
	},
};

export const container = {
	label: 'Container size',
	general: {
		'max-widthUnit': 'px',
		'max-width': 1784,
		widthUnit: '%',
		width: 92.9,
	},
	xxl: {
		'max-widthUnit': 'px',
		'max-width': 1784,
		widthUnit: '%',
		width: 92.9,
	},
	xl: {
		'max-widthUnit': 'px',
		'max-width': 1784,
		widthUnit: '%',
		width: 92.9,
	},
	l: {
		'max-widthUnit': 'px',
		'max-width': 1170,
		widthUnit: '%',
		width: 85.65,
	},
	m: {
		'max-widthUnit': 'px',
		'max-width': 940,
		widthUnit: '%',
		width: 91.8,
	},
	s: {
		'max-widthUnit': 'px',
		'max-width': 720,
		widthUnit: '%',
		width: 93.75,
	},
	xs: {
		'max-widthUnit': 'px',
		'max-width': 426,
		widthUnit: '%',
		width: 88.75,
	},
};

export const column = {
	label: 'Column size',
	general: {
		size: 90,
	},
	xxl: {
		size: '',
	},
	xl: {
		size: '',
	},
	l: {
		size: '',
	},
	m: {
		size: '',
	},
	s: {
		size: '',
	},
	xs: {
		size: '',
	},
};

export const shapeDivider = {
	label: 'Shape Divider',
	top: {
		status: 0,
		height: 100,
		heightUnit: 'px',
		opacity: {
			label: 'Opacity',
			general: {
				opacity: 1,
			},
		},
		shapeStyle: '',
		background: {
			...background,
		},
		effects: {
			status: 0,
		},
	},
	bottom: {
		status: 0,
		height: 100,
		heightUnit: 'px',
		opacity: {
			label: 'Opacity',
			general: {
				opacity: 1,
			},
		},
		shapeStyle: '',
		background: {
			...background,
		},
		effects: {
			status: 0,
		},
	},
};

export const position = {
	label: 'Position',
	general: {
		position: '',
	},
	xxl: {
		position: '',
	},
	xl: {
		position: '',
	},
	l: {
		position: '',
	},
	m: {
		position: '',
	},
	s: {
		position: '',
	},
	xs: {
		position: '',
	},
	options: {
		label: 'Position options',
		general: {
			top: '',
			right: '',
			bottom: '',
			left: '',
			sync: false,
			unit: 'px',
		},
		xxl: {
			top: '',
			right: '',
			bottom: '',
			left: '',
			sync: false,
			unit: '',
		},
		xl: {
			top: '',
			right: '',
			bottom: '',
			left: '',
			sync: false,
			unit: '',
		},
		l: {
			top: '',
			right: '',
			bottom: '',
			left: '',
			sync: false,
			unit: '',
		},
		m: {
			top: '',
			right: '',
			bottom: '',
			left: '',
			sync: false,
			unit: '',
		},
		s: {
			top: '',
			right: '',
			bottom: '',
			left: '',
			sync: false,
			unit: '',
		},
		xs: {
			top: '',
			right: '',
			bottom: '',
			left: '',
			sync: false,
			unit: '',
		},
	},
};

export const display = {
	label: 'Display block',
	general: {
		display: '',
	},
	xxl: {
		display: '',
	},
	xl: {
		display: '',
	},
	l: {
		display: '',
	},
	m: {
		display: '',
	},
	s: {
		display: '',
	},
	xs: {
		display: '',
	},
};

export const hover = {
	label: 'Hover Effects',
	type: 'none',
	basicEffectType: 'zoom-in',
	textEffectType: 'fade',
	preview: 1,
	textPreset: 'center-center',
	borderStatus: 0,
	paddingStatus: 0,
	marginStatus: 0,
	border: { ...border },
	background: {
		...background,
		activeMedia: 'color',
		colorOptions: {
			...background.colorOptions,
			activeColor: 'rgba(0,0,0, 0.6)',
			color: 'rgba(0,0,0, 0.6)',
		},
	},
	margin: { ...margin },
	padding: { ...padding },
	titleTypography: {
		...typography,
		general: {
			...typography.general,
			'font-size': 30,
			color: '#fff',
		},
	},
	contentTypography: {
		...typography,
		general: {
			...typography.general,
			'font-size': 18,
			color: '#fff',
		},
	},
	titleStatus: 0,
	contentStatus: 0,
	titleText: 'Add your Hover Title here',
	contentText: 'Add your Hover Content here',
};

export const motion = {
	label: 'Motion Effects',
	interaction: {
		interactionStatus: 0,
		timeline: {},
		activeTimeline: {
			time: 0,
			index: 0,
		},
		transformOrigin: {
			xAxis: 'center',
			yAxis: 'center',
		},
		presetStatus: 0,
		previewStatus: 0,
		tabletStatus: 1,
		mobileStatus: 1,
	},
	entrance: {
		type: '',
		duration: 1,
		delay: 1,
	},
	parallax: {
		status: 0,
		speed: 2,
		direction: 'up',
	},
};

export const arrow = {
	label: 'Arrow',
	active: 0,
	general: {
		active: 0,
		side: 'bottom',
		position: 50,
		width: 80,
		widthUnit: 'px',
	},
	xxl: {
		side: '',
		position: '',
		width: '',
		widthUnit: '',
	},
	xl: {
		side: '',
		position: '',
		width: '',
		widthUnit: '',
	},
	l: {
		side: '',
		position: '',
		width: '',
		widthUnit: '',
	},
	m: {
		side: '',
		position: '',
		width: '',
		widthUnit: '',
	},
	s: {
		side: '',
		position: '',
		width: '',
		widthUnit: '',
	},
	xs: {
		side: '',
		position: '',
		width: '',
		widthUnit: '',
	},
};

export const transform = {
	label: 'Transform',
	general: {
		scaleX: '',
		scaleY: '',
		translateXUnit: '%',
		translateX: '',
		translateYUnit: '%',
		translateY: '',
		rotateX: '',
		rotateY: '',
		rotateZ: '',
		originX: 'center',
		originY: 'center',
	},
	xxl: {
		scaleX: '',
		scaleY: '',
		translateXUnit: '%',
		translateX: '',
		translateYUnit: '%',
		translateY: '',
		rotateX: '',
		rotateY: '',
		rotateZ: '',
		originX: '',
		originY: '',
	},
	xl: {
		scaleX: '',
		scaleY: '',
		translateXUnit: '%',
		translateX: '',
		translateYUnit: '%',
		translateY: '',
		rotateX: '',
		rotateY: '',
		rotateZ: '',
		originX: '',
		originY: '',
	},
	l: {
		scaleX: '',
		scaleY: '',
		translateXUnit: '%',
		translateX: '',
		translateYUnit: '%',
		translateY: '',
		rotateX: '',
		rotateY: '',
		rotateZ: '',
		originX: '',
		originY: '',
	},
	m: {
		scaleX: '',
		scaleY: '',
		translateXUnit: '%',
		translateX: '',
		translateYUnit: '%',
		translateY: '',
		rotateX: '',
		rotateY: '',
		rotateZ: '',
		originX: '',
		originY: '',
	},
	s: {
		scaleX: '',
		scaleY: '',
		translateXUnit: '%',
		translateX: '',
		translateYUnit: '%',
		translateY: '',
		rotateX: '',
		rotateY: '',
		rotateZ: '',
		originX: '',
		originY: '',
	},
	xs: {
		scaleX: '',
		scaleY: '',
		translateXUnit: '%',
		translateX: '',
		translateYUnit: '%',
		translateY: '',
		rotateX: '',
		rotateY: '',
		rotateZ: '',
		originX: '',
		originY: '',
	},
};

export const highlight = {
	label: 'Highlight',
	backgroundHighlight: 0,
	textHighlight: 0,
	borderHighlight: 0,
	color1Highlight: 0,
	color2Highlight: 0,
};
