const SVGDefaults = [
    '../wp-content/plugins/maxi-blocks/src/icons/shape-icons/shape1.svg',
    '../wp-content/plugins/maxi-blocks/src/icons/shape-icons/shape2.svg',
    '../wp-content/plugins/maxi-blocks/src/icons/shape-icons/shape3.svg',
    '../wp-content/plugins/maxi-blocks/src/icons/shape-icons/shape4.svg',
    '../wp-content/plugins/maxi-blocks/src/icons/shape-icons/shape5.svg',
    '../wp-content/plugins/maxi-blocks/src/icons/shape-icons/shape6.svg',
    '../wp-content/plugins/maxi-blocks/src/icons/shape-icons/shape7.svg',
    '../wp-content/plugins/maxi-blocks/src/icons/shape-icons/shape8.svg',
    '../wp-content/plugins/maxi-blocks/src/icons/shape-icons/shape9.svg',
    '../wp-content/plugins/maxi-blocks/src/icons/shape-icons/shape10.svg',
    '../wp-content/plugins/maxi-blocks/src/icons/shape-icons/shape11.svg',
    '../wp-content/plugins/maxi-blocks/src/icons/shape-icons/shape12.svg',
    '../wp-content/plugins/maxi-blocks/src/icons/shape-icons/shape13.svg',
    '../wp-content/plugins/maxi-blocks/src/icons/shape-icons/shape14.svg',
    '../wp-content/plugins/maxi-blocks/src/icons/shape-icons/shape15.svg',
    '../wp-content/plugins/maxi-blocks/src/icons/shape-icons/shape16.svg',
    '../wp-content/plugins/maxi-blocks/src/icons/shape-icons/shape17.svg',
    '../wp-content/plugins/maxi-blocks/src/icons/shape-icons/shape18.svg',
    '../wp-content/plugins/maxi-blocks/src/icons/shape-icons/shape19.svg',
    '../wp-content/plugins/maxi-blocks/src/icons/shape-icons/shape20.svg',
    '../wp-content/plugins/maxi-blocks/src/icons/shape-icons/shape21.svg',
    '../wp-content/plugins/maxi-blocks/src/icons/shape-icons/shape22.svg',
    '../wp-content/plugins/maxi-blocks/src/icons/shape-icons/shape23.svg',
    '../wp-content/plugins/maxi-blocks/src/icons/shape-icons/shape24.svg',
    // '../wp-content/plugins/maxi-blocks/src/icons/shape-icons/shape25.svg',
    '../wp-content/plugins/maxi-blocks/src/icons/shape-icons/shape26.svg',
    '../wp-content/plugins/maxi-blocks/src/icons/shape-icons/shape27.svg',
    '../wp-content/plugins/maxi-blocks/src/icons/shape-icons/shape28.svg',
    '../wp-content/plugins/maxi-blocks/src/icons/shape-icons/shape29.svg',
    '../wp-content/plugins/maxi-blocks/src/icons/shape-icons/shape30.svg',
    '../wp-content/plugins/maxi-blocks/src/icons/shape-icons/shape31.svg',
    '../wp-content/plugins/maxi-blocks/src/icons/shape-icons/shape32.svg',
    '../wp-content/plugins/maxi-blocks/src/icons/shape-icons/shape33.svg',
];

export default SVGDefaults;