import getOrganizedAttributes from '../getOrganizedAttributes';
import cleanStyleAttributes from '../cleanStyleAttributes';
import { default as imageMaxiMapping } from '../../../blocks/image-maxi/copy-paste-mapping';

describe('getOrganizedAttributes', () => {
	it('Ensure getOrganizedAttributes and cleanStyleAttributes work correctly', () => {
		const object = {
			defaultBlockStyle: 'maxi-def-light',
			customLabel: 'Image',
			fullWidth: 'normal',
			'alignment-general': 'right',
			imageRatio: 'original',
			captionType: 'custom',
			captionContent: 'Basket Ball',
			captionPosition: 'bottom',
			'caption-gap-general': 2,
			'caption-gap-unit-general': 'em',
			imageSize: 'full',
			isImageUrl: false,
			altSelector: 'title',
			imgWidth: 82,
			'clip-path-status-general': false,
			'link-palette-status-general': true,
			'link-palette-color-general': 4,
			'link-hover-palette-status-general': true,
			'link-hover-palette-color-general': 6,
			'link-active-palette-status-general': true,
			'link-active-palette-color-general': 6,
			'link-visited-palette-status-general': true,
			'link-visited-palette-color-general': 6,
			'palette-status-general': true,
			'palette-color-general': 3,
			'font-size-unit-general': 'px',
			'line-height-unit-general': 'px',
			'letter-spacing-unit-general': 'px',
			'text-indent-unit-general': 'px',
			'hover-type': 'none',
			'hover-preview': true,
			'hover-extension': false,
			'hover-basic-effect-type': 'zoom-in',
			'hover-text-effect-type': 'fade',
			'hover-text-preset': 'center-center',
			'hover-transition-easing': 'easing',
			'hover-transition-duration': 0.5,
			'hover-basic-zoom-in-value': 1.3,
			'hover-basic-zoom-out-value': 1.5,
			'hover-basic-slide-value': 30,
			'hover-basic-rotate-value': 15,
			'hover-basic-blur-value': 2,
			'hover-background-status': false,
			'hover-background-palette-status-general': true,
			'hover-background-palette-color-general': 1,
			'hover-background-color-clip-path-status-general': false,
			'hover-background-gradient-opacity-general': 1,
			'hover-background-gradient-clip-path-status-general': false,
			'hover-border-palette-status-general': true,
			'hover-border-palette-color-general': 2,
			'hover-border-status': false,
			'hover-border-sync-radius-general': 'all',
			'hover-border-unit-radius-general': 'px',
			'hover-border-top-width-general': 2,
			'hover-border-right-width-general': 2,
			'hover-border-bottom-width-general': 2,
			'hover-border-left-width-general': 2,
			'hover-border-sync-width-general': 'all',
			'hover-border-unit-width-general': 'px',
			'hover-content-palette-status-general': true,
			'hover-content-palette-color-general': 1,
			'hover-content-font-size-unit-general': 'px',
			'hover-content-font-size-general': 18,
			'hover-content-line-height-unit-general': 'px',
			'hover-content-letter-spacing-unit-general': 'px',
			'hover-content-text-indent-unit-general': 'px',
			'hover-content-typography-status': false,
			'hover-content-typography-content': 'Add your Hover Title here',
			'hover-margin-sync-general': 'all',
			'hover-margin-top-unit-general': 'px',
			'hover-margin-right-unit-general': 'px',
			'hover-margin-bottom-unit-general': 'px',
			'hover-margin-left-unit-general': 'px',
			'hover-margin-status': false,
			'hover-padding-top-unit-general': 'px',
			'hover-padding-right-unit-general': 'px',
			'hover-padding-bottom-unit-general': 'px',
			'hover-padding-left-unit-general': 'px',
			'hover-padding-sync-general': 'all',
			'hover-padding-status': false,
			'hover-title-palette-status-general': true,
			'hover-title-palette-color-general': 1,
			'hover-title-font-size-unit-general': 'px',
			'hover-title-font-size-general': 30,
			'hover-title-line-height-unit-general': 'px',
			'hover-title-letter-spacing-unit-general': 'px',
			'hover-title-text-indent-unit-general': 'px',
			'hover-title-typography-status': false,
			'hover-title-typography-content': 'Add your Hover Title here',
			'image-border-palette-status-general': true,
			'image-border-palette-color-general': 7,
			'image-border-palette-status-general-hover': true,
			'image-border-palette-color-general-hover': 4,
			'image-border-status-hover': true,
			'image-border-sync-radius-general': 'all',
			'image-border-unit-radius-general': 'px',
			'image-border-unit-radius-general-hover': 'px',
			'image-border-top-width-general': 3,
			'image-border-right-width-general': 3,
			'image-border-bottom-width-general': 3,
			'image-border-left-width-general': 3,
			'image-border-sync-width-general': 'all',
			'image-border-unit-width-general': 'px',
			'image-box-shadow-palette-status-general': true,
			'image-box-shadow-palette-color-general': 8,
			'image-box-shadow-palette-color-general-hover': 6,
			'image-box-shadow-status-hover': false,
			'image-size-advanced-options': false,
			'image-max-width-unit-general': 'px',
			'image-width-unit-general': 'px',
			'image-width-fit-content-general': false,
			'image-min-width-unit-general': 'px',
			'image-max-height-unit-general': 'px',
			'image-height-unit-general': 'px',
			'image-min-height-unit-general': 'px',
			'image-padding-top-unit-general': 'px',
			'image-padding-right-unit-general': 'px',
			'image-padding-bottom-unit-general': 'px',
			'image-padding-left-unit-general': 'px',
			'image-padding-sync-general': 'all',
			blockFullWidth: 'normal',
			'block-background-hover-status': false,
			'border-palette-status-general': true,
			'border-palette-color-general': 2,
			'border-palette-status-general-hover': true,
			'border-palette-color-general-hover': 6,
			'border-status-hover': false,
			'border-sync-radius-general': 'all',
			'border-unit-radius-general': 'px',
			'border-unit-radius-general-hover': 'px',
			'border-top-width-general': 2,
			'border-right-width-general': 2,
			'border-bottom-width-general': 2,
			'border-left-width-general': 2,
			'border-sync-width-general': 'all',
			'border-unit-width-general': 'px',
			'box-shadow-palette-status-general': true,
			'box-shadow-palette-color-general': 5,
			'box-shadow-palette-color-general-hover': 6,
			'box-shadow-status-hover': false,
			'size-advanced-options': false,
			'max-width-unit-general': 'px',
			'width-unit-general': 'px',
			'width-fit-content-general': false,
			'min-width-unit-general': 'px',
			'max-height-unit-general': 'px',
			'height-unit-general': 'px',
			'min-height-unit-general': 'px',
			'margin-sync-general': 'all',
			'margin-top-unit-general': 'px',
			'margin-right-unit-general': 'px',
			'margin-bottom-unit-general': 'px',
			'margin-left-unit-general': 'px',
			'padding-top-unit-general': 'px',
			'padding-right-unit-general': 'px',
			'padding-bottom-unit-general': 'px',
			'padding-left-unit-general': 'px',
			'padding-sync-general': 'all',
			shortcutEffect: 0,
			'scroll-vertical-status-general': false,
			'scroll-vertical-preview-status-general': false,
			'scroll-vertical-easing-general': 'ease',
			'scroll-vertical-speed-general': 500,
			'scroll-vertical-delay-general': 0,
			'scroll-vertical-viewport-top-general': 'mid',
			'scroll-vertical-status-reverse-general': true,
			'scroll-vertical-offset-start-general': -400,
			'scroll-vertical-offset-mid-general': 0,
			'scroll-vertical-offset-end-general': 400,
			'scroll-horizontal-status-general': false,
			'scroll-horizontal-preview-status-general': false,
			'scroll-horizontal-easing-general': 'ease',
			'scroll-horizontal-speed-general': 500,
			'scroll-horizontal-delay-general': 0,
			'scroll-horizontal-viewport-top-general': 'mid',
			'scroll-horizontal-status-reverse-general': true,
			'scroll-horizontal-offset-start-general': -200,
			'scroll-horizontal-offset-mid-general': 0,
			'scroll-horizontal-offset-end-general': 200,
			'scroll-rotate-status-general': false,
			'scroll-rotate-preview-status-general': false,
			'scroll-rotate-easing-general': 'ease',
			'scroll-rotate-speed-general': 500,
			'scroll-rotate-delay-general': 0,
			'scroll-rotate-viewport-top-general': 'mid',
			'scroll-rotate-status-reverse-general': true,
			'scroll-rotate-rotate-start-general': 90,
			'scroll-rotate-rotate-mid-general': 0,
			'scroll-rotate-rotate-end-general': 0,
			'scroll-scale-status-general': false,
			'scroll-scale-preview-status-general': false,
			'scroll-scale-easing-general': 'ease',
			'scroll-scale-speed-general': 500,
			'scroll-scale-delay-general': 0,
			'scroll-scale-viewport-top-general': 'mid',
			'scroll-scale-status-reverse-general': true,
			'scroll-scale-scale-start-general': 70,
			'scroll-scale-scale-mid-general': 100,
			'scroll-scale-scale-end-general': 100,
			'scroll-fade-status-general': false,
			'scroll-fade-preview-status-general': false,
			'scroll-fade-easing-general': 'ease',
			'scroll-fade-speed-general': 500,
			'scroll-fade-delay-general': 0,
			'scroll-fade-viewport-top-general': 'mid',
			'scroll-fade-status-reverse-general': true,
			'scroll-fade-opacity-start-general': 0,
			'scroll-fade-opacity-mid-general': 100,
			'scroll-fade-opacity-end-general': 100,
			'scroll-blur-status-general': false,
			'scroll-blur-preview-status-general': false,
			'scroll-blur-easing-general': 'ease',
			'scroll-blur-speed-general': 500,
			'scroll-blur-delay-general': 0,
			'scroll-blur-viewport-top-general': 'mid',
			'scroll-blur-status-reverse-general': true,
			'scroll-blur-blur-start-general': 10,
			'scroll-blur-blur-mid-general': 0,
			'scroll-blur-blur-end-general': 0,
			'transform-translate-x-unit-general': '%',
			'transform-translate-y-unit-general': '%',
			'transform-origin-x-unit-general': '%',
			'transform-origin-y-unit-general': '%',
			'position-sync-general': 'all',
			'position-unit-general': 'px',
			'flex-basis-unit-general': 'px',
			'row-gap-unit-general': 'px',
			'column-gap-unit-general': 'px',
			uniqueID: 'image-maxi-331',
			isFirstOnHierarchy: true,
			blockStyle: 'maxi-light',
			parentBlockStyle: 'light',
			mediaID: 22,
			mediaURL:
				'http://localhost:8888/wp-content/uploads/2022/04/ball.jpg',
			mediaWidth: 225,
			mediaHeight: 225,
			mediaAlt: 'ball',
			'text-alignment-general': 'center',
			SVGElement:
				'<svg viewBox="0 0 36.1 36.1" class="heart-54-shape-maxi-svg" data-item="image-maxi-331__svg"><pattern id="image-maxi-331__428__img" class="maxi-svg-block__pattern" width="100%" height="100%" x="0" y="0" patternunits="userSpaceOnUse"><image class="maxi-svg-block__pattern__image" width="100%" height="100%" x="0" y="0" href="http://localhost:8888/wp-content/uploads/2022/04/ball.jpg" preserveaspectratio="xMidYMid slice"></image></pattern><path fill="url(#image-maxi-331__428__img)" data-fill="" fill-rule="evenodd" d="M2.2 6.2h0c2.7-2.7 7.2-2.7 10 0L18 12l5.8-5.8c2.7-2.7 7.2-2.7 10 0h0c2.7 2.7 2.7 7.2 0 10L18 32 2.2 16.2c-2.7-2.8-2.7-7.3 0-10h0z" style="fill: url(#image-maxi-331__428__img)"></path></svg>',
			SVGData: {
				'image-maxi-331__428': {
					color: '',
					imageID: 22,
					imageURL:
						'http://localhost:8888/wp-content/uploads/2022/04/ball.jpg',
				},
			},
			'image-border-style-general': 'dashed',
			'image-border-top-left-radius-general': 71,
			'image-border-top-right-radius-general': 71,
			'image-border-bottom-right-radius-general': 71,
			'image-border-bottom-left-radius-general': 71,
			'image-border-style-general-hover': 'dashed',
			'image-border-top-width-general-hover': 3,
			'image-border-right-width-general-hover': 3,
			'image-border-bottom-width-general-hover': 3,
			'image-border-left-width-general-hover': 3,
			'image-border-sync-width-general-hover': 'all',
			'image-border-unit-width-general-hover': 'px',
			'image-border-top-left-radius-general-hover': 71,
			'image-border-top-right-radius-general-hover': 71,
			'image-border-bottom-right-radius-general-hover': 71,
			'image-border-bottom-left-radius-general-hover': 71,
			'image-border-sync-radius-general-hover': 'all',
			'box-shadow-palette-opacity-general': 0.23,
			'box-shadow-horizontal-general': 0,
			'box-shadow-vertical-general': 30,
			'box-shadow-blur-general': 50,
			'box-shadow-spread-general': 0,
			'transform-scale-x-general': 65,
			'transform-scale-y-general': 110,
		};

		const result = getOrganizedAttributes(
			object,
			imageMaxiMapping,
			'image-'
		);
		expect(result).toMatchSnapshot();

		const result2 = cleanStyleAttributes(
			object,
			imageMaxiMapping,
			'image-'
		);
		expect(result2).toMatchSnapshot();
	});
});
