name: Check Blocks JSON

on:
    pull_request:
        branches: [master]

jobs:
    check-blocks-json:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 2
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.0'
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '16.x'
            - name: Cache Composer packages
              uses: actions/cache@v3
              with:
                  path: ~/.composer/cache
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-
            - name: Cache npm packages
              uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-
            - name: Install Composer dependencies
              run: composer install --prefer-dist --no-progress
            - name: Install Node.js dependencies
              run: npm install --legacy-peer-deps
            - name: Create .env file
              run: |
                  touch .env
                  echo "REACT_APP_TYPESENSE_API_KEY=${{ secrets.REACT_APP_TYPESENSE_API_KEY }}" >> .env
                  echo "REACT_APP_TYPESENSE_API_URL=${{ secrets.REACT_APP_TYPESENSE_API_URL }}" >> .env
                  echo "REACT_APP_MAXI_BLOCKS_CRISP_API_KEY=${{ secrets.REACT_APP_MAXI_BLOCKS_CRISP_API_KEY }}" >> .env
            - name: Install WordPress
              run: |
                  chmod -R 767 ./
                  npm run wp-env start
            - name: Build
              run: npm run build
            - name: Run update-blocks-json
              run: npm run update-blocks-json
            - name: Check for changes
              run: |
                  git config --global core.autocrlf false
                  echo "Checking for changes in JSON files"

                  if [[ $(git status --porcelain **/*.json) ]]; then
                    echo "Changes detected in JSON files:"
                    git diff --name-status **/*.json
                    echo "Changes detected in JSON files after running update-blocks-json"
                    exit 1
                  else
                    echo "No changes detected in JSON files after running update-blocks-json"
                    echo "Unexpected changes in other files:"
                    git status --porcelain
                  fi
