name: Performance Tests

on:
    pull_request:
        branches: [master]
    workflow_dispatch:

jobs:
    get-comparison-branch:
        runs-on: ubuntu-latest
        outputs:
            comparison_branch: ${{ steps.get_branch.outputs.branch }}
        steps:
            - name: Get comparison branch from latest PR comment
              id: get_branch
              uses: actions/github-script@v6
              with:
                  github-token: ${{secrets.GITHUB_TOKEN}}
                  script: |
                      async function getAllComments(owner, repo, issue_number) {
                        let allComments = [];
                        let page = 1;
                        const per_page = 100;

                        while (true) {
                          const { data: comments } = await github.rest.issues.listComments({
                            owner,
                            repo,
                            issue_number,
                            per_page,
                            page
                          });

                          allComments = allComments.concat(comments);

                          if (comments.length < per_page) {
                            break;
                          }

                          page++;
                        }

                        return allComments;
                      }

                      const allComments = await getAllComments(
                        context.repo.owner,
                        context.repo.repo,
                        context.issue.number
                      );
                      console.log(`Found ${allComments.length} comments on PR #${context.issue.number}`);

                      const setComparisonRegex = /comparison-branch:\s*(\S+)/i;
                      let comparisonBranch = 'master';

                      // Process comments from newest to oldest
                      for (const comment of allComments.reverse()) {
                        console.log(`Processing comment: ${comment.body}`);
                        const match = comment.body.match(setComparisonRegex);
                        if (match) {
                          comparisonBranch = match[1];
                          console.log(`Found comparison branch in latest matching comment: ${comparisonBranch}`);
                          break;
                        }
                      }

                      if (comparisonBranch === 'master') {
                        console.log('No comparison branch found in PR comments, defaulting to master');
                      }

                      core.setOutput('branch', comparisonBranch);

    performance-current:
        needs: get-comparison-branch
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
            - name: Cache node modules
              uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-build-v1.3-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-v1.3-${{ env.cache-name }}-
                      ${{ runner.os }}-build-v1.3-
                      ${{ runner.os }}-
              env:
                  cache-name: cache-node-modules
            - name: Install dependencies
              run: npm install --legacy-peer-deps
            - name: Create .env file
              run: |
                  cat << EOF > .env
                  REACT_APP_TYPESENSE_API_KEY=${{ secrets.REACT_APP_TYPESENSE_API_KEY }}
                  REACT_APP_TYPESENSE_API_URL=${{ secrets.REACT_APP_TYPESENSE_API_URL }}
                  REACT_APP_MAXI_BLOCKS_CRISP_API_KEY=${{ secrets.REACT_APP_MAXI_BLOCKS_CRISP_API_KEY }}
                  EOF
            - name: Build
              run: npm run build
            - name: Install WordPress
              run: |
                  chmod -R 767 ./
                  npm run wp-env start
            - name: Run performance test on current branch
              id: current_test
              run: |
                  npm run test:performance
                  mkdir -p $RUNNER_TEMP/performance_results
                  mv bin/performance-results.json $RUNNER_TEMP/performance_results/performance-results-current.json
            - name: Upload current results
              uses: actions/upload-artifact@v4
              with:
                  name: current-performance-results
                  path: ${{ runner.temp }}/performance_results/performance-results-current.json

    performance-comparison:
        needs: get-comparison-branch
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Checkout comparison branch
              uses: actions/checkout@v4
              with:
                  ref: ${{ needs.get-comparison-branch.outputs.comparison_branch }}
                  fetch-depth: 0
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
            - name: Cache node modules
              uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-build-v1.3-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-v1.3-${{ env.cache-name }}-
                      ${{ runner.os }}-build-v1.3-
                      ${{ runner.os }}-
              env:
                  cache-name: cache-node-modules
            - name: Install dependencies
              run: npm install --legacy-peer-deps
            - name: Create .env file
              run: |
                  cat << EOF > .env
                  REACT_APP_TYPESENSE_API_KEY=${{ secrets.REACT_APP_TYPESENSE_API_KEY }}
                  REACT_APP_TYPESENSE_API_URL=${{ secrets.REACT_APP_TYPESENSE_API_URL }}
                  REACT_APP_MAXI_BLOCKS_CRISP_API_KEY=${{ secrets.REACT_APP_MAXI_BLOCKS_CRISP_API_KEY }}
                  EOF
            - name: Build
              run: npm run build
            - name: Install WordPress
              run: |
                  chmod -R 767 ./
                  npm run wp-env start
            - name: Run performance test on comparison branch
              id: comparison_test
              run: |
                  npm run test:performance
                  mkdir -p $RUNNER_TEMP/performance_results
                  mv bin/performance-results.json $RUNNER_TEMP/performance_results/performance-results-comparison.json
            - name: Upload comparison results
              uses: actions/upload-artifact@v4
              with:
                  name: comparison-performance-results
                  path: ${{ runner.temp }}/performance_results/performance-results-comparison.json

    compare-results:
        needs: [performance-current, performance-comparison]
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
        steps:
            - uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
            - name: Install dependencies
              run: npm install --legacy-peer-deps
            - name: Download current results
              uses: actions/download-artifact@v4
              with:
                  name: current-performance-results
                  path: ${{ runner.temp }}/performance_results
            - name: Download comparison results
              uses: actions/download-artifact@v4
              with:
                  name: comparison-performance-results
                  path: ${{ runner.temp }}/performance_results
            - name: Compare performance results
              run: npm run compare-performance -- --file1 ${{ runner.temp }}/performance_results/performance-results-comparison.json --file2 ${{ runner.temp }}/performance_results/performance-results-current.json
            - name: Read comparison results
              id: read_comparison
              run: |
                  echo "content<<EOF" >> $GITHUB_OUTPUT
                  cat bin/performance_comparison.md >> $GITHUB_OUTPUT
                  echo "EOF" >> $GITHUB_OUTPUT
            - name: Create new comment
              uses: peter-evans/create-or-update-comment@v3
              with:
                  issue-number: ${{ github.event.pull_request.number }}
                  body: |
                      ## Performance Test Results
                      ${{ steps.read_comparison.outputs.content }}
