name: Performance Tests

on:
    pull_request:
        branches: [master]
    workflow_dispatch:

jobs:
    performance-js:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 2
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
            - name: Cache node modules
              uses: actions/cache@v2
              with:
                  # npm cache files are stored in `~/.npm` on Linux/macOS
                  # to clear the cache, change `v1.3` for any other random number, github will destroy
                  # the old cache within 7 days 👌
                  # Note: don't change the `actions/setup-node@v1` or any other dependency version by error
                  path: ~/.npm
                  key: ${{ runner.os }}-build-v1.3-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-v1.3-${{ env.cache-name }}-
                      ${{ runner.os }}-build-v1.3-
                      ${{ runner.os }}-
              env:
                  cache-name: cache-node-modules
            - name: Use Node.js 16.x
              uses: actions/setup-node@v1
              with:
                  node-version: 16.x
            - name: Install dependencies
              run: npm install --legacy-peer-deps
            - name: Create .env file
              run: |
                  cat << EOF > .env
                  REACT_APP_TYPESENSE_API_KEY=${{ secrets.REACT_APP_TYPESENSE_API_KEY }}
                  REACT_APP_TYPESENSE_API_URL=${{ secrets.REACT_APP_TYPESENSE_API_URL }}
                  REACT_APP_MAXI_BLOCKS_CRISP_API_KEY=${{ secrets.REACT_APP_MAXI_BLOCKS_CRISP_API_KEY }}
                  EOF
            - name: Build
              run: npm run build
            - name: reset package-lock.json
              run: git checkout package-lock.json
            - name: Install WordPress
              run: |
                  chmod -R 767 ./
                  npm run wp-env start
            - name: Cache performance results
              uses: actions/cache@v3
              id: cache-results
              with:
                  path: |
                      ${{ runner.temp }}/performance_results
                  key: ${{ runner.os }}-performance-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-performance-
            - name: Run performance test on current branch
              id: current_test
              if: steps.cache-results.outputs.cache-hit != 'true'
              run: |
                  CURRENT_HASH=$(git rev-parse --short HEAD)
                  npm run test:performance
                  mkdir -p $RUNNER_TEMP/performance_results
                  mv bin/performance-results-$CURRENT_HASH.json $RUNNER_TEMP/performance_results/performance-results-current.json
                  echo "current_results=$RUNNER_TEMP/performance_results/performance-results-current.json" >> $GITHUB_OUTPUT
            - name: Set current results path from cache
              if: steps.cache-results.outputs.cache-hit == 'true'
              run: echo "current_results=$RUNNER_TEMP/performance_results/performance-results-${{ github.sha }}.json" >> $GITHUB_OUTPUT
            - name: Checkout master branch
              uses: actions/checkout@v4
              with:
                  ref: master
            - name: Check for performance test on master
              id: check_master_test
              run: |
                  if [ -f "package.json" ] && grep -q "test:performance" package.json; then
                    echo "has_test=true" >> $GITHUB_OUTPUT
                  else
                    echo "has_test=false" >> $GITHUB_OUTPUT
                  fi
            - name: Determine comparison branch
              id: determine_branch
              run: |
                  if [ "${{ steps.check_master_test.outputs.has_test }}" == "true" ]; then
                    echo "branch=master" >> $GITHUB_OUTPUT
                    echo "results_file=bin/performance-results-master.json" >> $GITHUB_OUTPUT
                  else
                    echo "branch=${{ github.head_ref }}" >> $GITHUB_OUTPUT
                    echo "results_file=bin/performance-results-current-2.json" >> $GITHUB_OUTPUT
                  fi
            - name: Checkout comparison branch
              uses: actions/checkout@v4
              with:
                  ref: ${{ steps.determine_branch.outputs.branch }}
            - name: Recreate .env file
              run: |
                  cat << EOF > .env
                  REACT_APP_TYPESENSE_API_KEY=${{ secrets.REACT_APP_TYPESENSE_API_KEY }}
                  REACT_APP_TYPESENSE_API_URL=${{ secrets.REACT_APP_TYPESENSE_API_URL }}
                  REACT_APP_MAXI_BLOCKS_CRISP_API_KEY=${{ secrets.REACT_APP_MAXI_BLOCKS_CRISP_API_KEY }}
                  EOF
            - name: Cache comparison results
              uses: actions/cache@v3
              id: cache-comparison-results
              with:
                  path: |
                      ${{ runner.temp }}/performance_results
                  key: ${{ runner.os }}-performance-${{ steps.determine_branch.outputs.branch }}-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-performance-${{ steps.determine_branch.outputs.branch }}-
            - name: Install dependencies for comparison branch
              if: steps.cache-comparison-results.outputs.cache-hit != 'true'
              run: npm install --legacy-peer-deps
            - name: Build comparison branch
              if: steps.cache-comparison-results.outputs.cache-hit != 'true'
              run: npm run build
            - name: Run performance test on comparison branch
              id: comparison_test
              if: steps.cache-comparison-results.outputs.cache-hit != 'true'
              run: |
                  npm run test:performance
                  HASH=$(git rev-parse --short HEAD)
                  mkdir -p $RUNNER_TEMP/performance_results
                  mv bin/performance-results-$HASH.json $RUNNER_TEMP/performance_results/${{ steps.determine_branch.outputs.results_file }}
                  echo "comparison_results=$RUNNER_TEMP/performance_results/${{ steps.determine_branch.outputs.results_file }}" >> $GITHUB_OUTPUT
            - name: Set comparison results path from cache
              if: steps.cache-comparison-results.outputs.cache-hit == 'true'
              run: echo "comparison_results=$RUNNER_TEMP/performance_results/${{ steps.determine_branch.outputs.results_file }}" >> $GITHUB_OUTPUT
            - name: Compare performance results
              run: npm run compare-performance -- --file1 ${{ steps.current_test.outputs.current_results }} --file2 ${{ steps.comparison_test.outputs.comparison_results }}
            - name: Read comparison results
              id: read_comparison
              run: |
                  echo "content<<EOF" >> $GITHUB_OUTPUT
                  cat bin/performance_comparison.md >> $GITHUB_OUTPUT
                  echo "EOF" >> $GITHUB_OUTPUT
            - name: Create comment with performance results
              uses: peter-evans/create-or-update-comment@v3
              with:
                  issue-number: ${{ github.event.pull_request.number }}
                  body: ${{ steps.read_comparison.outputs.content }}
